### ISSUE TITLE
TypeScript: copy to DefinitelyTyped?

### ISSUE THREAD

**Issue by gobsmack** [Esri/jsapi-resources#10]
I'm new to TypeScript, but so far it's been amazing, and I'm really thankful that we have ESRI bindings. I copied the d.ts. file to my local project, and that's been good. But, now I'm using TSD to manage my d.ts files. As far as I know, you can point TSD to a different repo, but that will be for ALL of your d.ts, not just one. A limitation of the tool, I think. But, is there anything stopping ESRI from pushing this t.ds to the DefinitelyTyped repo, which is the de facto resource to rule them all?

**Comment by dasa** [comment]
PR submitted at: https://github.com/borisyankov/DefinitelyTyped/pull/3818

**Comment by dasa** [comment]
A copy is now available at: https://github.com/borisyankov/DefinitelyTyped/tree/master/arcgis-js-api
