### ISSUE TITLE
DPI set is not the DPI send

### ISSUE THREAD

**Issue by GalllyNet** [Esri/jsapi-resources#101]
When we create a new `MapImageLayer`, the `dpi` send to the MapServer is not the one defined.
By default, the dpi is `96` but the one send to the http GET is `108`.  
_(witch make our servers not sending the correct data)_

To have the correct dpi send, we are obliged to set the dpi to `(96*96)/108`.

Why the `dpi` can't stay the same ? Why is it modified ?

**Comment by bsvensson** [comment]
Hi @GalllyNet 

This repo contains various resources for developers using the JSAPI - creating custom API builds with Bower, TypeScript definitions, Sass, jshint, OAuth etc.

As mentioned in [CONTRIBUTING.md](https://github.com/Esri/jsapi-resources/blob/master/CONTRIBUTING.md) the best way to get support for using the JSAPI itself is to:

* Contact [Esri Tech Support](https://support.esri.com/contact-tech-support)
* Ask the Esri community on [GeoNet](https://geonet.esri.com/community/developers/web-developers/arcgis-api-for-javascript)

Hope this helps,
thank you

**Comment by GalllyNet** [comment]
Ok, I gonna try the esri Tech Support.
