### ISSUE TITLE
Layer List Widget's eyeball icon not honoring layer visibility 

### ISSUE THREAD

**Issue by Abexdatl** [Esri/jsapi-resources#102]
Before 4.5 the Layer List Widget was not totally honoring layer visibility in a map service.  That seem to be fixed in 4.5 . However there is another issue that we are facing now . This is related to the eyeball icon for toggling layer in the list is not honoring the layer visibility . 

Any idea ? or is this a known bug being worked ?

**Comment by bsvensson** [comment]
Hi @Abexdatl 
As for the specific issue, it's not a known bug being worked on. It's probably related to a specific case/layer that you are using.  

In general, there are several ways you can ask for assistance or provide feedback on the [ArcGIS API for Javascript](http://js.arcgis.com) from [Esri](https://www.esri.com/).

* Contact [Esri Tech Support](https://support.esri.com/contact-tech-support)
* Ask the Esri community on [GeoNet](https://geonet.esri.com/community/developers/web-developers/arcgis-api-for-javascript)

**Comment by Abexdatl** [comment]
Well I found out that the LayerList widget's eyeball icon does not honer layer visibility if the map service is designed in such a way that a specific layer is not visible at certain scale . It always uses .esri-icon-visible rather than .esri-icon-non-visible when that layer is not supposed to be visible . This is a bug I guess
