### ISSUE TITLE
Collection.splice items parameter has incorrect type

### ISSUE THREAD

**Issue by jeff-tenhave** [Esri/jsapi-resources#106]
Collection.splice items parameter has incorrect type.

Should be:
splice(start: number, deleteCount: number, ...items: T[]): T[];
and not:
splice(start: number, deleteCount: number, items: T[] | Collection<T>): T[];

If you pass a collection object to splice, it will insert the entire collection object into the result, and not the items in the collection as expected.

**Comment by jkieboom** [comment]
Thanks for reporting this! It is fixed in the upcoming 4.6 typings.
