### ISSUE TITLE
[v4.6.0] Typings - IPromise interface

### ISSUE THREAD

**Issue by nickcam** [Esri/jsapi-resources#109]
Hi Guys,
The typings in 4.6.0 for the IPromise interface doesn't contain the new `when()` function.
Thanks!

**Comment by dasa** [comment]
The `IPromise` interface represents the Dojo Promise which doesn't include a `when` function.

**Comment by nickcam** [comment]
Ok cool, got it.
There's still no mention of `when` anywhere else in the typings though?

**Comment by dasa** [comment]
`when` is part of the `corePromise` interface on line 1309.

**Comment by nickcam** [comment]
So it is :). My bad....I was looking for it the other day and for the life of me couldn't find it! Must have been using 4.5.1 still. You're a champion - thanks!
