### ISSUE TITLE
Videos for the EmberJS page

### ISSUE THREAD

**Issue by hhkaos** [Esri/jsapi-resources#112]
I'm missing a couple of videos in the [ember page](https://github.com/Esri/jsapi-resources/tree/master/frameworks/ember): [ArcGIS API for JavaScript Using it with EmberJS](http://www.esri.com/videos/watch?videoid=5026&channelid=LegacyVideo&isLegacy=true&title=arcgis-api-for-javascript-using-it-with-emberjs) and [ArcGIS API for JavaScript with Ember](https://www.youtube.com/watch?v=9wbGhr6wdwE), do you want me to make a PR to include them?.

Could also a link to the [ArcGIS Search](https://esri-es.github.io/arcgis-search/?search=emberjs) at additional resources? (it is a [GCS engine](https://cse.google.com/cse/) that search in [+40 different domains](https://github.com/esri-es/arcgis-search/blob/master/README.md#which-are-the-arcgis-search-project-sources))

Cheers!

**Comment by hhkaos** [comment]
And maybe we could also add a link to the [EmberJS experts](https://esri-es.github.io/arcgis-experts/?topic=EmberJS), right?

**Comment by hhkaos** [comment]
@tomwayson @dasa ^_^

**Comment by tomwayson** [comment]
@hhkaos - a couple of great ideas here.

Re: arcgis-experts and arcgis-search links - I'd say yes, please make a PR that adds links to each of these under the **Additional Resources** section of each framework page.

Should the same PR also update links for each framework to the corresponding awesome-arcgis readme to point to the page on the built site instead? (i.e. https://esri-es.github.io/awesome-arcgis/front-end/technologies/angular/, https://esri-es.github.io/awesome-arcgis/front-end/technologies/emebr/, etc)?

Re: the videos

The [ArcGIS API for JavaScript with Ember](https://www.youtube.com/watch?v=9wbGhr6wdwE) is already on the page here: https://github.com/Esri/jsapi-resources/tree/master/frameworks/ember#ember-cli-amd and I think that's the best place for it.

re: the DevSummit video

I was planning to start adding links to talks/presentations under the **Additional Resources** section for each framework in the way that I just did for Angular (#111). However, now that I'm thinking about it, I'd prefer for each framework page to have a new **Presentations** section under **Example Applications** and above **Additional Resources** b/c ideally for each talk we'd want to  have 2 links, one to the slides, one to the videos, etc. I'll make a separate issue for that w/ my take on a format etc.

**Comment by hhkaos** [comment]
> @hhkaos - a couple of great ideas here.

Thanks! 😁 

> Re: arcgis-experts and arcgis-search links - I'd say yes, please make a PR that adds links to each of these under the **Additional Resources** section of each framework page.
> 
> Should the same PR also update links for each framework to the corresponding awesome-arcgis readme to point to the page on the built site instead? (i.e. https://esri-es.github.io/awesome-arcgis/front-end/technologies/angular/, https://esri-es.github.io/awesome-arcgis/front-end/technologies/emebr/, etc)?

Sure I'll do it right know!. We could use one hosted at `esri-es` or  at `hhkaos` (right now they are ... siblings?), my idea is transfer the ownership of the original repo (hhkaos) to github.com/esri, but until then, I'll use the esri-es branded, ok?

> Re: the videos
>
> The ArcGIS API for JavaScript with Ember is already on the page here: https://github.com/Esri/jsapi-resources/tree/master/frameworks/ember#ember-cli-amd and I think that's the best place for it.

You are right, sorry I didn't see it before. 😅 

> re: the DevSummit video
>
> I was planning to start adding links to talks/presentations under the **Additional Resources** section for each framework in the way that I just did for Angular ([#111](https://github.com/Esri/jsapi-resources/pull/111)). However, now that I'm thinking about it, I'd prefer for each framework page to have a new **Presentations** section under **Example Applications** and above **Additional Resources** b/c ideally for each talk we'd want to have 2 links, one to the slides, one to the videos, etc. I'll make a separate issue for that w/ my take on a format etc.

I like that idea too 👍  😄

**Comment by tomwayson** [comment]
This can be closed. It was resolved in #115

**Comment by dasa** [comment]
Thanks!
