### ISSUE TITLE
Add a Presentations section to each framework page

### ISSUE THREAD

**Issue by tomwayson** [Esri/jsapi-resources#113]
Would include links to slides/videos for DevSummit/UC presentations re: using the framework w/ the JSAPI. Sorted from most recent to oldest.

See #112 for the back story.

Here's my idea for the format:

### Audacious Enterprise GIS Apps with EmberJs
2017 International Developer Summit, David Bouwman, Mike Juniper
[Video](https://youtu.be/7Bvr7cEQNCg)

### ArcGIS API for JavaScript Using it with EmberJS
2016 International Developer Summit, Frederic Aubry, Rene Rubalcava
[Slides](http://proceedings.esri.com/library/userconf/devsummit16/papers/dev_int_186.pdf) | [Video](http://www.esri.com/videos/watch?videoid=5026&channelid=LegacyVideo&isLegacy=true&title=arcgis-api-for-javascript-using-it-with-emberjs)

@hhkaos lmk what you think about format. if it's good, I can PR that adds the above for Ember and then does it for the other frameworks pages too.

**Comment by hhkaos** [comment]
It's nice, but I think I prefer tables, don't you?:

## Presentations

|Event|Title|Authors|Video|Slides|
|---|---|---|---|---|
|[DevSummit](http://www.esri.com/events/devsummit) 2017|Audacious Enterprise GIS Apps with EmberJs|[David Bouwman](https://esri-es.github.io/arcgis-experts/#expert=dave-bouwman) & [Mike Juniper](https://esri-es.github.io/arcgis-experts/#expert=mike-juniper)|[Video](https://youtu.be/7Bvr7cEQNCg)|n.a.|
|[DevSummit](http://www.esri.com/events/devsummit) 2016|ArcGIS API for JavaScript Using it with EmberJS|[Frederic Aubry](https://esri-es.github.io/arcgis-experts/#expert=frederic-aubry) & [Rene Rubalcava](https://esri-es.github.io/arcgis-experts/#expert=rene-rubalcava)|[Video](http://www.esri.com/videos/watch?videoid=5026&channelid=LegacyVideo&isLegacy=true&title=arcgis-api-for-javascript-using-it-with-emberjs)|[Slides](http://proceedings.esri.com/library/userconf/devsummit16/papers/dev_int_186.pdf)

**Comment by tomwayson** [comment]
@hhkaos why don't you make a PR for the ember page in that format (since I don't have push access to this repo, I can't get your markdown source). I know I'm being lazy, but no point in me re-formatting it all.

I can then make a PR based on your markdown for the other frameworks.

**Comment by hhkaos** [comment]
hahah, sure! [there you have](https://github.com/Esri/jsapi-resources/pull/115/commits/11207f03b2053504b27af098e3f4064583260d41) 😄  

cheers!!

**Comment by tomwayson** [comment]
Thanks @hhkaos! I'll update the angular pages to use the new format and add the others.
