### ISSUE TITLE
Create a frameworks page for Vue.js

### ISSUE THREAD

**Issue by tomwayson** [Esri/jsapi-resources#114]
This is mostly a note to self. I've already started on this, but it keeps dropping off my list. Probably should wait until PRs are in for in #113 and #112 since those will affect all framework pages. Until then, this is what I have so far:

# Using the ArcGIS API for JavaScript in Vue.js Applications

Below are links to tools that will help you use the [ArcGIS API for JavaScript] in applications built with [Vue.js], as well as examples of how to use those tools.

### [esri-loader](https://github.com/Esri/esri-loader)
A tiny library to help load ArcGIS API for JavaScript modules in non-Dojo applications (not specific to Vue.js)

### [vue-jsapi4](http://odoe.net/blog/arcgis-api-4-for-js-with-vue-cli-and-nuxt/)
Demonstrate how you can add the ArcGIS API 4 for JS to a vue-cli / Nuxt.js app.
<br /> [Blog post](http://odoe.net/blog/arcgis-api-4-for-js-with-vue-cli-and-nuxt/) | [Video](https://youtu.be/hqJzzgM8seo)

## Additional Resources
- [Using VueJS in an ArcGIS API for JavaScript application](http://odoe.net/blog/using-vuejs-arcgis-api-javascript/)
- [Using the ArcGIS API for JavaScript with Frameworks](../)
- [Awesome ArcGIS: Vue.js ](https://github.com/hhkaos/awesome-arcgis/tree/master/front-end/technologies/vuejs)
- [Vue.js]

[ArcGIS API for JavaScript]:https://developers.arcgis.com/javascript/
[Vue.js]:https://vuejs.org/

**Comment by terenceng2010** [comment]
In my experience, when switching bewteen routings of vue-router, the dojo widgets of a jsapi map needs to be torn down first. Otherwise, these widgets cannot be loaded again due to double initialization. May be it would be helpful to mention similar quirks like this in the framework page you are preparing?

**Comment by tomwayson** [comment]
Thanks @terenceng2010 

I'd say, no matter which framework you're using, in most cases it is a good idea to destroy the ArcGIS widgets before destroying the component that contains them, and/or remove event and watch handles as [odoe does here](https://github.com/odoe/vue-jsapi4/blob/45cc05d6d928a3e3ee189f32a388163a11ca98f0/pages/map.vue).

That said, I accidentally neglected to do that in my [example app that uses vue-router](https://github.com/tomwayson/esri-vue-cli-example/blob/583d5555cad6ba115139190b0a00fe4ef9e35706/src/LocateButton.vue), and that app doesn't seem to have the problems you describe above. I'll admit that's a very simple, contrived app. I guess it it depends on which widgets you're using and how you're using them.

**Comment by terenceng2010** [comment]
I was using the measurement widget in JSAPI 3.21 with vue-router, if I get the time, I may try to reproduce it with minimal code. Thanks.

**Comment by tomwayson** [comment]
Good to know. Were you loading modules in the route itself, or just in the components like I do in my example?
