### ISSUE TITLE
typescript demo does not work

### ISSUE THREAD

**Issue by vu-dang** [Esri/jsapi-resources#12]
I'm getting the following error from Chrome

Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.

**Comment by dasa** [comment]
I do see that warning but the map does load at http://esri.github.io/jsapi-resources/typescript/demo.html What version of Chrome are you testing with?

**Comment by vu-dang** [comment]
I'm not seeing the map using ie11 in windows 8 either.  Maybe it is a windows 8 issue.

**Comment by vu-dang** [comment]
I got the older version 3.13 and its working.
