### ISSUE TITLE
Issues with trying the webpack demo

### ISSUE THREAD

**Issue by roemhildtg** [Esri/jsapi-resources#126]
I'm running into several issues running the web pack plugin demo. 

1. Cannot find module 'arcgis-webpack-plugin' when doing build or serve.

This one was pretty obvious. Change the 1st line in `webpack.config.js` to 
```javascript
const ArcGISPlugin = require("@arcgis/webpack-plugin");
```

Build completes now. 

2. ReactDom is not defined when opening in a web browser. Following [the guide here](https://www.typescriptlang.org/docs/handbook/react-&-webpack.html) a bit, I was able to locate the necessary lines to add to my index.html. 

```html
  <script src="./node_modules/react/umd/react.development.js"></script>
  <script src="./node_modules/react-dom/umd/react-dom.development.js"></script>
```

These errors go away after adding these. 

3. I'm now encountering a maquette.js error. Not sure where to go from here.
![image](https://user-images.githubusercontent.com/5471079/39150372-c5eddaac-4707-11e8-8e16-10ab7d5d45c2.png)

I'm sure its something simple, but any guidance would be appreciated. Good work so far on webpack builds! I'm really excited to get this working.

**Comment by odoe** [comment]
This was fixed in the webpack-plugin and the sample was currently updated.
https://github.com/Esri/arcgis-webpack-plugin/issues/3

Thanks!

**Comment by roemhildtg** [comment]
Cool! A fresh install is working now! Thanks @odoe! This is super exciting :tada:
