### ISSUE TITLE
Running the demo code verbatim results in an error

### ISSUE THREAD

**Issue by jbailey-spatialbridge** [Esri/jsapi-resources#13]
Copying the demo files, compiling using VS2015, and running in Visual Studio results in the following error:

>Unhandled exception at line 143, column 273 in http://js.arcgis.com/3.14/
>
>0x800a138f - JavaScript runtime error: Unable to get property 'id' of undefined or null reference

This error is encountered when the following line is called:
```javascript
this.map = new Map(this.mapDiv, mapOptions);
```

**Comment by tomrippetoe** [comment]
I am getting the same error call the same line of code (Visual Studio 2013). IE and Chrome

> Unhandled exception at line 143, column 273 in http://js.arcgis.com/3.14/
> 
> 0x800a138f - JavaScript runtime error: Unable to get property 'id' of undefined or null reference

```javascript
self._esriMap = new Map(divId, options);
```
The error is thrown in both IE and Chrome

**Comment by tomrippetoe** [comment]
Whoops! this one is 100% on me.  I had assigned the class name to the map div, but not the ID.  Once i added in the id value to the div, all worked fine.
