### ISSUE TITLE
Loading json files with webpack plugin

### ISSUE THREAD

**Issue by RalucaNicola** [Esri/jsapi-resources#130]
I am using the webpack plugin and I am not sure what's the right way to load json files.

I've added the `json-loader` plugin: https://github.com/RalucaNicola/edge-rendering/blob/master/webpack.config.js#L36 but I get the following error:

```
Error: Cannot find module '/Library/WebServer/Documents/edge-rendering/node_modules/json-loader/index.js!/Library/WebServer/Documents/edge-rendering/node_modules/dojo/package.json'
```
Should I add something else to the webpack config or should I load it differently?

**Comment by odoe** [comment]
Can you try it with `import novaStyle from '../../basemap-styles/nova.json';`

**Comment by odoe** [comment]
ah, I think you need to update the config for the json loader to exclude node_modules

```js
      {
        test: /\.json$/,
        loader: 'json-loader',
        exclude: /node_modules/  // add this
      },
```

**Comment by odoe** [comment]
I got this build without layers and it consoles the json correctly, but not sure it's updating the app right.

```js
// webpack.config.js
      {
        test: /\.json$/,
        type: "javascript/auto",
        loader: 'json-loader',
        exclude: /node_modules/
      },
```

```ts
// night.ts
import * as novaStyle from '../../basemap-styles/nova.json';

console.log("nova", novaStyle, "style");
```

Webpack 4 handles JSON natively, but since we have to go through the Dojo loader to process the file, things get tricky.

Let me know if that helps.

**Comment by RalucaNicola** [comment]
yes, it helps a lot, thanks a lot @odoe!! The app works.

Ok, so import whole module using es6 syntax and in webpack config exclude node_modules and add the `type` property. I was trying to figure out what the `type` property does, but it's not in the webpack doc: https://webpack.js.org/configuration/module/#module-rules ?

Anyways, happy that it works though, thanks! Feel free to close this ticket.

**Comment by odoe** [comment]
Yeah, I don't know where `type` is doc'd. I just came across it in this issue https://github.com/webpack/webpack/issues/6357

Thanks!
