### ISSUE TITLE
3.x/bower/dojo: Tag/branch v1.2.1/esri-3.23.0 does not exist

### ISSUE THREAD

**Issue by gavinr** [Esri/jsapi-resources#132]
## I am reporting an issue with 

- [ ] TypeScript definitions
- [x] another resource in this repository

## Issue:

When i run `npm install` on a fresh copy of the `3.x/bower/dojo` code in this repo, I get an error:

`bower dgrid1#v1.2.1/esri-3.23.0     ENORESTARGET Tag/branch v1.2.1/esri-3.23.0 does not exist`

Here's a screenshot:
![image](https://user-images.githubusercontent.com/209355/39816634-6ca1e388-5361-11e8-851a-72ab6ebd3dcc.png)

## Replication Steps

1. Download the ZIP of this repository
2. Browse to `\jsapi-resources-master\3.x\bower\dojo`
3. Run `npm install`

**Comment by odoe** [comment]
Should be fixed in https://github.com/Esri/jsapi-resources/commit/aed195d1fe581c78c836ef101eb26d06a0d8fa65

Had to update the bower resolutions.

Thanks!

**Comment by davewilton** [comment]
@odoe same issue on https://developers.arcgis.com/javascript/3/jshelp/inside_bower_custom_builds.html

Thanks!
