### ISSUE TITLE
Webpack Plugin - Error when loading a non-public web map from AGOL

### ISSUE THREAD

**Issue by nick-romano** [Esri/jsapi-resources#135]
I am reporting an issue with 
- [ x] another resource in this repository

Demo app is up and running, accepts any public webmap as the portalItem id (tested with multiple public webmap ids), but when loading a portal item that is not a public I get this error:

dojo.js:1754 GET http://localhost:8080/dojo/request/watch.js 404 (Not Found)
dojo.js:1754 GET http://localhost:8080/dojo/request/util.js 404 (Not Found)
dojo.js:1754 GET http://localhost:8080/dojo/request/kernel.js 404 (Not Found)

..etc

Shouldn't these files be inside the bundle?

My guess is my bundle is missing some modules needed for the authentication window...

**Comment by odoe** [comment]
Correction, now I see the issue.

It happens with the IdentityManager popup, but not if you use OAuth as described here.
https://developers.arcgis.com/javascript/latest/sample-code/identity-oauth-basic/index.html

Let me look at this a little further, because it may require some more involved steps.

**Comment by odoe** [comment]
This should be fixed by updating the `@arcgis/webpack-plugin` to `4.7.8`
https://github.com/Esri/arcgis-webpack-plugin/releases/tag/4.7.8

Can you please verify @nick-romano

**Comment by nick-romano** [comment]
I'll update and let you know tomorrow. thanks for the quick response.

**Comment by nick-romano** [comment]
This worked, but now I am getting an error with the calcite module. Webpack is throwing a compilation error on .svg, .eot, .woff, and .ttf files, logging that there is no loader set to handle those file extensions.

I set up a rule to have those files loaded with the file-loader, just to see that the previous fix worked, but that's not a good solution. Could just be an error on my end at this point as well. Let me know if that seems odd to you.

But the private web map ID now loads successfully, so thanks for that.

**Comment by odoe** [comment]
ha, ya, i think i screwed up the regex again, testing some more and will update today.

I think you can add this to your `modules.rules` of the webpack config to fix it, but I'm still testing

```js
      {
        test: /\.(jpe?g|png|gif|webp)$/,
        loader: "url-loader",
        options: {
          // Inline files smaller than 10 kB (10240 bytes)
          limit: 10 * 1024,
        }
      },
      {
        test: /\.(wsv|ttf|otf|eot|svg|woff(2)?)(\?[a-z0-9]+)?$/,
        use: [
          {
            loader: "file-loader",
            options: {
              name: "build/[name].[ext]"
            }
          }
        ]
      },
```

**Comment by nick-romano** [comment]
ah, yeah that looks right to me. Thanks @odoe
