### ISSUE TITLE
@ ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/css/main.scss

### ISSUE THREAD

**Issue by mymhj** [Esri/jsapi-resources#136]
npm install   is ok .
but npm  start.  Error:
 @ ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/css/main.scss

    ERROR in ./node_modules/arcgis-js-api/themes/base/fonts/avenir-next/Avenir_Next_W00_Italic_400.woff2
    Module parse failed: Unexpected character ' ' (1:4)
    You may need an appropriate loader to handle this file type.
    (Source code omitted for this binary file)
     @ ./node_modules/css-loader!./node_modules/arcgis-js-api/themes/light/main.css 7:1353-1422
     @ ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/css/main.scss

    ERROR in ./node_modules/arcgis-js-api/themes/base/fonts/avenir-next/Avenir_Next_W00_Italic_600.woff2
    Module parse failed: Unexpected character ' ' (1:4)
    You may need an appropriate loader to handle this file type.
    (Source code omitted for this binary file)
     @ ./node_modules/css-loader!./node_modules/arcgis-js-api/themes/light/main.css 7:2759-2828
     @ ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/css/main.scss

**Comment by odoe** [comment]
I assume you are using the Webpack demo app in this repo?
Are you on Windows?
What version of Node are you using?
What version of NPM are you using?

There's an issue with either the css or sass loader on Windows and I haven't gotten around to find a fix yet.
https://github.com/Esri/arcgis-js-cli/issues/2

**Comment by odoe** [comment]
@mymhj this should work on Windows with cygwin or bash/linux on Windows

**Comment by odoe** [comment]
Fix is in https://github.com/Esri/arcgis-webpack-plugin/releases/tag/4.7.8

Please verify @mymhj

**Comment by odoe** [comment]
Currently addressing this issue in https://github.com/Esri/arcgis-webpack-plugin/issues/15
