### ISSUE TITLE
Should `drawOptions` be optional?

### ISSUE THREAD

**Issue by COV-GIS** [Esri/jsapi-resources#137]
I am reporting an issue with 

- [X ] TypeScript definitions
- [ ] another resource in this repository

Should `drawOptions` be optional?

Line 37854: `create(drawAction: string, drawOptions: DrawCreateDrawOptions): DrawAction;`

**Comment by dasa** [comment]
Yes, this will be fixed in the next release. Thank your for reporting this issue.
