### ISSUE TITLE
Geometry/Polygon typescript error

### ISSUE THREAD

**Issue by COV-GIS** [Esri/jsapi-resources#138]
I am reporting an issue with 

- [x] TypeScript definitions
- [ ] another resource in this repository

I'm getting the error `Argument of type 'Geometry' is not assignable to parameter of type 'Polygon'. Property 'centroid' is missing in type 'Geometry'.` on the `simplifiedPolygon` argument of `geodesicArea()` as used here...

```typescript
let area = geometryEngine.geodesicArea(polygon, this.areaUnit);
if (area < 0) {
  const simplifiedPolygon = geometryEngine.simplify(polygon);
  if (simplifiedPolygon) {
    area = geometryEngine.geodesicArea(simplifiedPolygon, this.areaUnit);
  }
}
```

Am I messing something up or...?

**Comment by dasa** [comment]
`simplify` is typed as taking a Geometry and returning a Geometry, so you'll need to use type assertion like this:

`const simplifiedPolygon = geometryEngine.simplify(polygon) as Polygon;`

**Comment by COV-GIS** [comment]
Thanks @dasa!
