### ISSUE TITLE
4.7\bower\requirejs   build err

### ISSUE THREAD

**Issue by liqiao6884** [Esri/jsapi-resources#140]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'E:\\NodeJS\\node_global\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.0.1
3 info using node@v8.11.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle arcgis-js-api-sample-app@1.0.0~prebuild: arcgis-js-api-sample-app@1.0.0
6 info lifecycle arcgis-js-api-sample-app@1.0.0~build: arcgis-js-api-sample-app@1.0.0
7 verbose lifecycle arcgis-js-api-sample-app@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle arcgis-js-api-sample-app@1.0.0~build: PATH: E:\NodeJS\node_global\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;E:\Work\API\arcgis\jsapi-resources-master\4.x\bower\requirejs\node_modules\.bin;D:\app\JOE\product\11.2.0\client_1;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\nodejs\;C:\Program Files\Git\bin;C:\Program Files\Git\cmd;E:\NodeJS\node_global
9 verbose lifecycle arcgis-js-api-sample-app@1.0.0~build: CWD: E:\Work\API\arcgis\jsapi-resources-master\4.x\bower\requirejs
10 silly lifecycle arcgis-js-api-sample-app@1.0.0~build: Args: [ '/d /s /c', 'grunt build' ]
11 silly lifecycle arcgis-js-api-sample-app@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle arcgis-js-api-sample-app@1.0.0~build: Failed to exec build script
13 verbose stack Error: arcgis-js-api-sample-app@1.0.0 build: `grunt build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (E:\NodeJS\node_global\node_modules\npm\node_modules\npm-lifecycle\index.js:283:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (E:\NodeJS\node_global\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid arcgis-js-api-sample-app@1.0.0
15 verbose cwd E:\Work\API\arcgis\jsapi-resources-master\4.x\bower\requirejs
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "E:\\NodeJS\\node_global\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v8.11.1
19 verbose npm  v6.0.1
20 error code ELIFECYCLE
21 error errno 1
22 error arcgis-js-api-sample-app@1.0.0 build: `grunt build`
22 error Exit status 1
23 error Failed at the arcgis-js-api-sample-app@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by odoe** [comment]
4x bower builds with rjs optimizer are deprecated. It's not going to work.

**Comment by liqiao6884** [comment]
I can build 4.3、4.5 with rjs，but build 4.6 、4.7 unsuccessful. Is it the reason for ES6

**Comment by odoe** [comment]
No, the API has just gotten far too big to use the r.js optimizer. There are some internal loader plugins that r.js doesn't understand.

I'm not sure if the specific error you posted is fully related, but the number of files that need to ignored in the r.js build makes it troublesome.

**Comment by odoe** [comment]
As I said, you're only going to run into those errors more often in 4x with rjs. That's why we deprecated the support.
