### ISSUE TITLE
Unable to retrieve packages for determining optional package support in dstore

### ISSUE THREAD

**Issue by laidaxian** [Esri/jsapi-resources#143]
er,I have a problem when i use 4.x demo width npm. Throw error 'Unable to retrieve packages for determining optional package support in dstore' when I do 'npm run build'.
我用4.x的npm demo,clone 下来以后，‘npm install' -> 'npm run build'。然后报错了，是什么原因:
![selection_045](https://user-images.githubusercontent.com/26853867/41599689-86811358-7406-11e8-87df-9c67043e1bdb.png)

**Comment by odoe** [comment]
Could you try a reinstall of `npm`? I can't repro and saw someone with a similar issue solve it by installing `npm` again.

**Comment by GeoFredMan** [comment]
I had the same error but after inspecting the build-report.txt I found other errors that caused my build to fail. When I fixed these error's the above mentioned "error" message can be found as a info message when the dojo built starts (use grunts -v option):

Building Dojo...
Dojo build parameters:
        dojoConfig.js
        load=build
        --basePath ./dist
        --profile profiles/build.profile.js
        --profile profiles/build.profile.js
        --releaseDir ../built
processing profile resource l:/egeoplugin4-trunk/src/main/webapp/profiles/build.profile.js
processing profile resource l:/egeoplugin4-trunk/src/main/webapp/profiles/build.profile.js
info(107) Package Version: package: egeoplugin; version: 0.1.0
processing profile resource l:/egeoplugin4-trunk/src/main/webapp/dist/egeoplugin/egeoplugin.profile.js
info(107) Package Version: package: gvrapp; version: 0.1.0
processing profile resource l:/egeoplugin4-trunk/src/main/webapp/dist/gvrapp/gvrapp.profile.js
info(107) Package Version: package: dijit; version: 1.13.0
processing profile resource l:/egeoplugin4-trunk/src/main/webapp/node_modules/dijit/dijit.profile.js
info(107) Package Version: package: dojo; version: 1.13.0
processing profile resource l:/egeoplugin4-trunk/src/main/webapp/node_modules/dojo/dojo.profile.js
info(107) Package Version: package: dojox; version: 1.13.0
processing profile resource l:/egeoplugin4-trunk/src/main/webapp/node_modules/dojox/dojox.profile.js
info(107) Package Version: package: dstore; version: 1.1.2
**>> Unable to retrieve packages for determining optional package support in dstore**
processing profile resource l:/egeoplugin4-trunk/src/main/webapp/node_modules/dojo-dstore/package.js 

Inspect your build-report carefully and fix all errors and this error goes away (but I don't know why... ;-)

**Comment by odoe** [comment]
I have had instances where I've had to do `npm install` twice as not all packages would get installed the first time. I don't know why, and it rarely happens, but it has happened.

**Comment by schontz** [comment]
If you run the build task in verbose mode `npm build -v` you will get much output to your console and see your other errors. I'm getting the same error, btw, but I'm not sure what my root issue is yet.

**Comment by schontz** [comment]
I am able to get my builds working but I cannot get that error to go away. I wasn't too bothered by it because I added `ignoreErrors` to my `grunt-dojo` config. But when a change to one of my files caused a legitimate error everything was failing silently. Is there any way we can resolve the `Unable to retrieve packages for determining optional package support in dstore` issue?

**Comment by odoe** [comment]
If someone has a sample project I can test with, I can try to debug, but as of now, I can't replicate. I suspect it is/was an npm issue. I'll reopen if this comes up again.

**Comment by qtang3** [comment]
@odoe 
I can repro this issue as well on two of my machines. One has npm ```6.1.0``` and the other has npm ```6.9.0``` and I work at esri redlands office.
![image](https://user-images.githubusercontent.com/2990406/57048233-ffa46900-6c27-11e9-9580-d84e4dbdd954.png)

**Comment by COV-GIS** [comment]
Double check any css paths if you are using dojo build css optimization (`targetStylesheet: 'app/css/main.css'`). No idea why it throws a dstore error. But any paths the build can't resolve cause the dstore error. I spent like two weeks figuring that out. I can't recall the code in the build report but methinks it's `314` and shows not as an error but as a warning making it harder debug.

**Comment by gavinr** [comment]
I have a simple replicable test case that will cause this issue to happen: just include and use `esri/identity/IdentityManager` in `main.js`  - [example here](https://github.com/gavinr/jsapi-resources/blob/de4628e414f6dd0bfeb51909f521e98594688fd8/4.x/npm/demo/src/app/main.js) ([diff vs master](https://github.com/gavinr/jsapi-resources/commit/de4628e414f6dd0bfeb51909f521e98594688fd8)).

This will cause the error below when running `npm run build`. @odoe does this happen for you? Thanks!

```
Building Dojo...
>> dojo build error: Error: Unable to retrieve packages for determining optional package support in dstore
Warning: Task "dojo:dist" failed. Use --force to continue.

Aborted due to warnings.
```

**Comment by gavinr** [comment]
Looks like me example case [above](https://github.com/Esri/jsapi-resources/issues/143#issuecomment-497791415) is due to the use of [ES6 arrow functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions). When I [remove those](https://github.com/gavinr/jsapi-resources/blob/5e646d52f375acc666bff643367f78eb2f23dae7/4.x/npm/demo/src/app/main.js), the build works. @schontz @laidaxian is it possible this is what was causing the error for you?

**Comment by carsnwd** [comment]
Bit of grave digging up this issue...but it's the first result on Google for the error.

This error can come up if you have orphaned left over JS files in your build when using TS. So say you have AppUtils.ts and rename to appUtils.ts , the AppUtils.js file may be left over and Dojo will try to pick it up and cause build errors.

Delete the orphaned JS files and it should work again, in my case at least.
