### ISSUE TITLE
Webpack demo: Typescript Sourcemaps Support

### ISSUE THREAD

**Issue by ech-beku** [Esri/jsapi-resources#145]
I am reporting an issue with 

- [ ] TypeScript definitions
- [x] another resource in this repository

The provided demo app for webpack does not support source-maps for tsx? files. I activated the webpack option
```javascript
...
devtool: "source-map"
...
```
But only the index.ts, which is the entry point, is mapped correctly in the chrome-dev tools. All other modules like ./widgets/App.tsx are somehow mapped but show already transpiled content (I guess thats the output of the arcgis webpack plugin / dojo webpack plugin:

`./app/App.tsx`:
```javascript
define(["require", "exports", "tslib", "esri/core/accessorSupport/decorators", "esri/widgets/support/widget", "esri/views/MapView", "esri/widgets/Widget", "./App/AppViewModel", "./Header"], function (require, exports, tslib_1, decorators_1, widget_1, MapView_1, Widget_1, AppViewModel_1, Header_1) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    MapView_1 = tslib_1.__importDefault(MapView_1);
    Widget_1 = tslib_1.__importDefault(Widget_1);
    AppViewModel_1 = tslib_1.__importDefault(AppViewModel_1);
    var CSS = {
        base: "main",
        webmap: "webmap"
    };
    var App = (function (_super) {
        tslib_1.__extends(App, _super);
        function App(params) {
            var _this = _super.call(this, params) || this;
            _this.viewModel = new AppViewModel_1.default();
            debugger;
            return _this;
        }
...

```

Debugging with the output is very inconvenient, especially in combination of ES5 output and async/await. Is there a way that sourcemaps show the original TS sourcefile?

**Comment by odoe** [comment]
I haven't been able to get it to work yet, but I'll keep trying.
