### ISSUE TITLE
Dojo build failing with JSAPI 3.25

### ISSUE THREAD

**Issue by apatriz** [Esri/jsapi-resources#148]
I am reporting an issue with 

- [ ] TypeScript definitions
- [x ] another resource in this repository

Using the settings given in 3.x/bower/dojo/build.profile.js , the dojo build is failing when optimizing css because it cannot find the relative path in calcite.css and esri.css (../fonts/avenir-next/<font-file>).
It looks like in 3.24, these fonts were hosted on CDN, but have now changed to relative paths. 
Should these fonts be added to the bower package?

**Comment by odoe** [comment]
That's odd, the `esri/themes/calcite/fonts` folder didn't make it into the 3.25 build, but doesn't fail on my mac or windows VM.

There's a new `3.25.1` release now and the project in this repo has been updated too.

Thanks!

**Comment by apatriz** [comment]
That fixed it! Thanks!
