### ISSUE TITLE
Dojo build WebGL rendering error

### ISSUE THREAD

**Issue by apatriz** [Esri/jsapi-resources#149]
I am reporting an issue with 

- [ ] TypeScript definitions
- [x ] another resource in this repository

WebGL rendering works fine when not doing a build, using the bower 3.25.1 package.

But after doing a build with WebGL enabled (using the build.profile in this repo), feature layers are not rendered on the map. The layers are initialized and hasWebGLSurface is true, but nothing is rendered on the map. Also get these WebGL errors in the Chrome dev console:

![image](https://user-images.githubusercontent.com/13872923/42973475-20362592-8b68-11e8-864c-e8d80d63bb49.png)

**Comment by odoe** [comment]
That's a weird one. What version of Chrome are you running? I tried this on Mac and Windows without issue. I'm currently using Chrome `67.0.3396.99` on Mac. Were there any odd build errors?

**Comment by apatriz** [comment]
Also using `67.0.3396.99`, but on Windows 10. 
I get the same issue in latest Edge (no layers are rendered), but no warnings in the console.
No build errors, but there are build warnings, though nothing odd.

I'm trying to play with the build.profile settings -- I removed all my custom layer files (just built the dojo custom base layer), which didn't resolve the issue. 
One difference from the default build.profile is that i'm compiling from ES6 to ES5 (closure compiler)  though i'm not sure how that would cause the issue.

I'm not even sure where to debug -- since the layers are initialized and added to the map without error. I've tried debugging some of the webgl code in esri/layers/support, but i'm not sure where to look.

**Comment by odoe** [comment]
Are you using `languageIn: "ECMASCRIPT6"`?

I assume you're still using `define()`, just `const`, `let`, and so on.

I can't reproduce yet, but if you could create a simple sample, that would be great.

**Comment by apatriz** [comment]
Thanks for looking into this. 
Yes, `languageIn: "ECMASCRIPT6", languageOut: "ECMASCRIPT5"`
Still using define() , and arrow functions, const, let, etc.

I will see if i can make a simple repro sample, but i suspect it has something to do with all our dependencies. I'm going to try turning off the dojo build js optimizer next.

**Comment by alaacs** [comment]
I think I am running into the same problem. Which is probably causing my FeatureLayer not to show its symbols. The FeatureLayer is loading properly, however, no symbols are shown on the map- everything is working perfectly before the build.
