### ISSUE TITLE
RequireJS demo application fails to build when dojox is a dependency

### ISSUE THREAD

**Issue by JGSimko** [Esri/jsapi-resources#15]
(Sorry if this is the wrong place) Would you be able to update the demo to show it working with dojox? I'm trying to get this running in my application and it fails when it trys to load in "dojox.js" (which doesn't exist). I'm thinking the same would occur when adding a dependency to it in this project (something in my applications dependency chain ends up relying on "dojox/json/query" which is what depends on "dojox" . 

I intend to test this out myself when I have some more time but please let me know if I'm missing something obvious here.

Thanks

**Comment by JGSimko** [comment]
I injected "esri/tasks/PrintTask" into the main.js of the RequireJS demo application and as suspected it failed to build.

Running "requirejs:single" (requirejs) task
>> Error: ENOENT, no such file or directory
>> 'K:\workspace\jsapi-resources\bower\requirejs\src\dojox.js'
>> In module tree:
>>     app/main
>>       esri/tasks/PrintTask
>>         dojox/json/query
Warning: RequireJS failed. Use --force to continue.

Aborted due to warnings.

**Comment by odoe** [comment]
That's odd.
It looks like RequireJS doesn't understand to look for a "main.js" file when looking for a package.
So in `dojox/json/query` it asks for `dojox`, but RequireJS doesn't know to look for `dojox/main`.
https://github.com/dojo/dojox/blob/master/json/query.js#L1

You can fix that by adding a packages property to the RequireJS Config. Be sure to also add this to the build profile in the Gruntfile for your app.
```
requirejs.config({                                                        
  packages: [{                                                            
    name: 'dojox',                                                        
    main: 'main'                                                          
  }],                                                                     
  deps: ['app/main']                                                      
});     
```

**Comment by JGSimko** [comment]
Thanks, it appears to be building now. However I'm confused as to where this code is built to. I thought all the JavaScript was supposed to compile to app/main.js but if I search the contents of that file there is no mention of several keywords that I grabbed from the un-built main.js ("measureDiv", "map-area", "esri/dijit/Measurement", "esri/tasks/PrintTask", etc...).
