### ISSUE TITLE
Npm build for 3.x

### ISSUE THREAD

**Issue by mvied** [Esri/jsapi-resources#151]
I am reporting an issue with 

- [ ] TypeScript definitions
- [x] another resource in this repository

I have laid out the basics for a 3.x npm build. I've used this method on many applications, but would love to see it officially supported. Please let me know if this is possible.

https://github.com/mvied/jsapi-resources/tree/master/3.x/npm/demo

I know that 3.x is not the preferred version to begin building new applications, however I have run into a few scenarios where I had to stick with 3.x. Beyond building new applications, I have quite a few, fairly large applications built on 3.x that I would like to make sure the build process is at least modern so that it one day does not stop working because I'm using an antiquated build setup.

There are a couple of outlying issues:
1. The Dojo build always reports back that it has failed, although the resulting build works fine. I would like to figure out what's causing this and have the build come back as successful. In the meantime I have set force=true in Gruntfile.js so that it completed all the build steps.
2. The SASS explanation and files still point at the 4.x file structure and need to be updated to specify 3.x.

**Comment by odoe** [comment]
The main issue with 3x via npm is that `dgrid` and `dgrid1` can't be installed via npm the way that 3x needs them. 3x has a dependency on both for various reasons.

Something like this works for Bower, it does not work for npm.

```
  "dependencies": {
    "dgrid": "git+https://github.com/Esri/dgrid.git#0.3.17-esri",
    "dgrid1": "git+https://github.com/Esri/dgrid.git#1.2.1-esri",
  }
}
```

Because these dependencies are missing, the Dojo build errors out. Forcing it works for apps that don't need any dgrid, but if you use FeatureTable, it won't. They way you are doing it with `--force` is really the only way to get it to work with apps that don't need any dgrid, because there are parts of the 3x API that have deps on it and will break.

I need to remove the sass parts in the 3x gruntfile, we don't have sass for 3x.

Thanks!

**Comment by mvied** [comment]
@odoe That makes sense. That is exactly what I ended up doing. https://github.com/mvied/jsapi-resources/blob/master/3.x/npm/demo/package.json#L29

What about just using a git submodule? I know it's low tech, but it would work, right?

**Comment by mvied** [comment]
It probably be too weird to mix git and npm, but we could do a pure git submodule solution, which is what I've used in the past.

**Comment by mvied** [comment]
I put together a git-based build in my fork. This version requires git to be installed locally. I mostly just want to document this for others in case they run into the same scenario. I can understand if ESRI does not want to officially support it.

https://github.com/mvied/jsapi-resources/tree/master/3.x/git/demo

**Comment by COV-GIS** [comment]
@mvied What build errors are listed in `build-report.txt` just out of curiosity. That should tell you what build processes failed.

When I switched from bower I could never get a build to work using npm without editing dgrid v1 package to reflect the `dgrid1` dojo package name. Esri has a dgrid v1 package with the `dgrid1` dojo package name. npm was still having issues, so I tried yarn and it's been working fine FWIW. Here's the deps.

```json
{
  "dependencies": {
    "arcgis-js-api": "Esri/arcgis-js-api#3.24.0",
    "dgrid": "Esri/dgrid#0.3.17/esri-3.20.0",
    "dgrid1": "Esri/dgrid#v1.2.1/esri-3.22.0",
    "dijit": "Esri/dijit#v1.13.0/esri-3.23.0",
    "dojo": "Esri/dojo#v1.13.0/esri-3.23.0",
    "dojo-dstore": "1.1.2",
    "dojo-util": "1.13.0",
    "dojox": "1.13.0",
    "moment": "2.22.1",
    "pouchdb": "6.4.3",
    "proj4": "2.4.4"
  },
  "resolutions": {
    "dojo": "Esri/dojo#v1.13.0/esri-3.23.0",
    "xstyle": "0.1.4"
  }
}
```

**Comment by mvied** [comment]
@COV-GIS I had to fork Esri/dgrid and update the 0.3.17 branch's dependency versions and the 1.2.1's branch's name to 'dgrid1`.
https://github.com/mvied/dgrid/blob/0.3.17-esri/package.json#L21
https://github.com/mvied/dgrid/blob/1.2.1-esri/package.json#L2

I had to ignore the node_modules folder in the build for dstore and the older dgrid. The older dependencies were causing errors.
https://github.com/mvied/jsapi-resources/blob/master/3.x/npm/demo/package.json#L30
https://github.com/mvied/jsapi-resources/blob/master/3.x/npm/demo/build.profile.js#L68

After all that I was able to get a successful build with both versions of dgrid using only npm.
