### ISSUE TITLE
Domain property of Field should be optional

### ISSUE THREAD

**Issue by gavinr** [Esri/jsapi-resources#155]
I am reporting an issue with 

- [x] TypeScript definitions (3.x)
- [ ] another resource in this repository

I think `Domain` should be an _optional_ property on `esri/layers/Field`.

Example change here:
https://github.com/Esri/jsapi-resources/pull/154/commits/b6d4a82f50c2b8886e280883ddfb0b72996477ba#diff-f3a4784a663d44608d3432155ab0061aL10406

**Comment by dasa** [comment]
None of the class properties are defined as optional in the 3.x definition file. It would require increasing the minimum supported version of TypeScript to 2.0 from 1.4.
