### ISSUE TITLE
`type` and `symbol` not RendererProperties?

### ISSUE THREAD

**Issue by COV-GIS** [Esri/jsapi-resources#156]
I am reporting an issue with 

- [x] TypeScript definitions
- [ ] another resource in this repository

The following results in `type does not exist in type RendererProperties`. Same for symbol.

```typescript
this._pointLayer = new FeatureLayer({
  geometryType: 'point',
  spatialReference: {
    wkid: 4326
  },
  fields: [{
    name: 'ObjectID',
    type: 'oid'
  }],
  objectIdField: 'ObjectID',
  source: [],
  renderer: {
    type: 'simple',
    symbol: {
      type: 'simple-marker',
      size: 10,
      color: 'white',
      outline: {
        color: 'black',
        width: 1
      }
    }
  }
});
```

To pass linting...

```typescript
const renderer = new SimpleRenderer({
  symbol: {
    type: 'simple-marker',
    size: 10,
    color: 'white',
    outline: {
      color: 'black',
      width: 1
    }
  }
});

this._pointLayer = new FeatureLayer({
  renderer: renderer
});
```

`renderer` autocasts in JS. Why not in in TS? Am I missing something?

**Comment by Maju-EA** [comment]
Staff at the 2019 DevCon mentioned that autocasts won't work in TS. It may be a TS bug.

**Comment by dasa** [comment]
The TypeScript limitation is that getter and setters can not have different types, so we've typed for what the getter returns.
