### ISSUE TITLE
Can't import JSON using recommended TypeScript compiler options

### ISSUE THREAD

**Issue by mojimi** [Esri/jsapi-resources#159]
I am reporting an issue with 

- [x] TypeScript definitions
- [ ] another resource in this repository

Starting from TS 2.9, you can use the "resolveJsonModule": true option to import .json files.

I could not get this to work at all, I think its due to the "module" : "amd" option.

We really would like to use .json as config files in our app, following Web Appbuilder's design, but with the 4.X API

**Comment by dasa** [comment]
I believe this is for Node.js apps: https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#new---resolvejsonmodule

You can use `esri/request` to load the JSON file.
