### ISSUE TITLE
Bower RequireJS demo fails to build "[e.add is not a function] Cannot read property normalize of undefined"

### ISSUE THREAD

**Issue by Barryrowe** [Esri/jsapi-resources#16]
The grunt build for the bower/requirejs demo fails with the following error using node 5.1:

Running "requirejs:single" (requirejs) task
[TypeError: e.add is not a function]
>> TypeError: Cannot read property 'normalize' of undefined
>> In module tree:
>>     app/main
>>       esri/map
>>         esri/_coremap
>>           esri/layers/GraphicsLayer
>>             esri/layers/gfxSniff
{ [Error: TypeError: Cannot read property 'normalize' of undefined
In module tree:
    app/main
      esri/map
        esri/_coremap
          esri/layers/GraphicsLayer
            esri/layers/gfxSniff

    at Object.<anonymous> (/Users/barry/git-repos/jsapi-resources/bower/requirejs/node_modules/requirejs/bin/r.js:1221:35)
]
  originalError: 
   { [TypeError: Cannot read property 'normalize' of undefined]
     moduleTree: 
      [ 'esri/layers/gfxSniff',
        'esri/layers/GraphicsLayer',
        'esri/_coremap',
        'esri/map',
        'app/main' ],
     fileName: '/Users/barry/git-repos/jsapi-resources/bower/requirejs/src/esri/layers/gfxSniff.js' } }

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/5.1.0/bin/node" "/Users/barry/.npm-packages/bin/npm" "run" "build"
npm ERR! node v5.1.0
npm ERR! npm  v3.5.1
npm ERR! code ELIFECYCLE
npm ERR! arcgis-js-api-sample-app@1.0.0 build: `grunt build`
npm ERR! Exit status 1

**Comment by odoe** [comment]
This is fixed in latest commit
https://github.com/Esri/jsapi-resources/commit/9fdd25a18fc5c53bcbd0cf8ce10dcb88dd43b857
