### ISSUE TITLE
BasemapGalleryProperties `source` TypeScript definition autocast missing

### ISSUE THREAD

**Issue by schontz** [Esri/jsapi-resources#160]
I am reporting an issue with 

- [x] TypeScript definitions
- [ ] another resource in this repository

According to index.d.ts, `BasemapGalleryProperties` has the following:
```
    source?: LocalBasemapsSourceProperties | PortalBasemapsSourceProperties;
```
But the [docs](https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-BasemapGallery.html#source) for `source` clearly state that it can take an array or Collection and autocast it.

**Comment by dasa** [comment]
autocasting isn't supported in TS code since we have to type the getter and can't type the setter separately.

**Comment by schontz** [comment]
How unfortunate.

**Comment by dasa** [comment]
Yes, we recommend using imports, which are made easier in VS Code with it's auto-importing.

**Comment by schontz** [comment]
Howso? I'm actually using the TS defs in a JavaScript project. VS Code reads them in so long as I JSDoc the AMD function at the top.

**Comment by dasa** [comment]
Ah, I was referring to a TS project. Have you tried writing your JS code as ES Modules, and then using Babel to transform to AMD?
