### ISSUE TITLE
Search Widget: typing "esri/widgets/Search/SearchResultRenderer" missing

### ISSUE THREAD

**Issue by Biboba** [Esri/jsapi-resources#161]
I am reporting an issue with 

- [X] TypeScript definitions
- [ ] another resource in this repository

Overwriting the search widget [view](https://github.com/Esri/arcgis-js-api/blob/d66ad6043901dd53fadab711d07d4c2d348b060d/widgets/Search.tsx#L98), I noticed that the typing of the module "esri/widgets/Search/SearchResultRenderer" is missing.

Thanks

**Comment by dasa** [comment]
Thank you for reporting this. It has been fixed in the 4.10 release.
