### ISSUE TITLE
4.10 not installed

### ISSUE THREAD

**Issue by sasteigerwald** [Esri/jsapi-resources#163]
I've run npm install @types/arcgis-js-api, but it still says 4.9.0. The page indicates it has been updated for 4.10. Has it actually been updated to 4.10?

**Comment by jgravois** [comment]
> Has it actually been updated to 4.10?

it doesn't look like it.

https://www.npmjs.com/package/@types/arcgis-js-api

![screenshot 2018-12-14 09 00 34](https://user-images.githubusercontent.com/3011734/50016696-c3c17d80-ff7e-11e8-9a56-06d0eb4d838b.png)

**Comment by sasteigerwald** [comment]
OK. I was going by the note at top: @dasa Update for ArcGIS API for JavaScript version 4.10

**Comment by jgravois** [comment]
yup. the [4.10 typings](https://github.com/Esri/jsapi-resources/blob/1fc5e7196c01017b4157c79ea6484a347dcef872/4.x/typescript/arcgis-js-api.d.ts) are on GitHub, but they haven't been published to npm yet.

**Comment by dasa** [comment]
The file in this repo has been updated, but the PR to update DefinitelyTyped is pending at:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/31370

**Comment by jgravois** [comment]
the typings for 4.10.0 have been released :tada:

```bash
$ npm view @types/arcgis-js-api@4.10.0

@types/arcgis-js-api@4.10.0 | MIT | deps: none | versions: 37
TypeScript definitions for ArcGIS API for JavaScript

dist
.tarball: https://registry.npmjs.org/@types/arcgis-js-api/-/arcgis-js-api-4.10.0.tgz
.shasum: 0e702500904e473e57a2d6d4bdae179bf07fe676
.integrity: sha512-r8Ax7+s0+VbUw+dwROFFmdhLTeKBwECWIQQecTGDRR9VY02m8qVH++gZio52p5Av7DJi7IaYrwY3U5eU2brkxA==
.unpackedSize: 3.7 MB

maintainers:
- types <ts-npm-types@microsoft.com>

dist-tags:
latest: 4.10.0  ts2.1: 4.4.0    ts2.3: 4.8.1    ts2.5: 4.8.1    ts2.7: 4.10.0   ts2.9: 4.10.0   ts3.1: 4.10.0   ts3.3: 4.10.0
ts2.0: 4.4.0    ts2.2: 4.4.0    ts2.4: 4.8.1    ts2.6: 4.8.1    ts2.8: 4.10.0   ts3.0: 4.10.0   ts3.2: 4.10.0

published a minute ago by types <ts-npm-types@microsoft.com>
```
