### ISSUE TITLE
need example that uses both dojo/dijit and Esri classes/typings module

### ISSUE THREAD

**Issue by AbhinavJKJ** [Esri/jsapi-resources#165]
Hi
i need to create custom widget (.tsx) using ARCGIS API 4.9 and dojo libary (1.11)
import { subclass, declared, property } from "esri/core/accessorSupport/decorators";
import _WidgetBase = require("dijit/_WidgetBase");
import { renderable, tsx } from "esri/widgets/support/widget";
can any one suggest how can do this.

**Comment by COV-GIS** [comment]
Use dijits like...

```typescript
/// <amd-dependency path="dijit/Dialog" name="Dialog" />
declare const Dialog: any;
```

Not sure why you would mix `dijit/_WidgetBase` with `esri/widgets/Widget` and `esri/widgets/support/widget`. There's no need for `_WidgetBase` if you're writing a `tsx` widget.

**Comment by AbhinavJKJ** [comment]
Hi @COV-GIS ,

I have created a widget but facing issue and in this i am not mixing the dijit/_WidgetBase:

This is the line where i am getting the error:
@viewmodel: SmallToggleButtonViewModel= new SmallToggleButtonViewModel();

I am using ArcGis 4.9
Below is whole code containing above line for understanding the flow:

/// 
/// 
///

import { vmEvent, renderable, tsx, accessibleHandler, join } from "esri/widgets/support/widget";

import {
aliasOf,
subclass,
property,
declared
} from "esri/core/accessorSupport/decorators";

import Widget = require("esri/widgets/Widget");
import View = require("esri/views/View");
import SmallToggleButtonViewModel = require("./SmallToggleButtonViewModel");
import ToggleState = require("./ToggleState");

const i18nCommon_Alternative = {
tooltip1: "1",
tooltip2: "2",
title1: "T1",
title2: "T2"
}

const CSS: any = {
base: "esri-expand esri-widget",
noIcon: "",
container: "esri-expand__container",
panel: "esri-expand__panel",
button: "esri-widget-button",
text: "esri-icon-font-fallback-text"
};

@subclass("compass.widgets.SmallToggleButton")
class SmallToggleButton extends declared(Widget) {

public static toggleChangedEventName: string = SmallToggleButtonViewModel.toggleChangedEventName;

constructor(params?: any) {
   super();
}

@property()
@renderable()
public state: ToggleState = ToggleState.State1;

@property()
@renderable()
tooltip1: string = "";

@property()
@renderable()
tooltip2: string = "";


@property()
@renderable()
title1: string = "";

@property()
@renderable()
title2: string = "";


@property()
@renderable()
esriIconFont1: string = "";

@property()
@renderable()
esriIconFont2: string = "";

@property()
@renderable()
titleVisible = false;

@renderable()
view: View = null;

**vmEvent("smallToggleButtonClicked") 
property({ type: SmallToggleButtonViewModel })
viewModel: SmallToggleButtonViewModel= new SmallToggleButtonViewModel();**

@aliasOf("viewModel.toggle")
toggle(state: ToggleState): void {}

render() {
    const isState1 = (this.state == ToggleState.State1);

    const tooltip1Text = this.tooltip1 || i18nCommon_Alternative.tooltip1;
    const tooltip2Text = this.tooltip2 || i18nCommon_Alternative.tooltip2;
    const title1Text = this.title1 || i18nCommon_Alternative.title1;
    const title2Text = this.title2 || i18nCommon_Alternative.title2;
    const finalIconClass1 = this.esriIconFont1 || CSS.noIcon;
    const finalIconClass2 = this.esriIconFont2 || CSS.noIcon;

    const title = isState1 ? title1Text : title2Text;
    const tooltip = isState1 ? tooltip1Text : tooltip2Text;

    var iconStyle: string = "";
    if (
        ((finalIconClass1.length == 0) && isState1)
        ||
        ((finalIconClass2.length == 0) && !isState1)
        ) {
        iconStyle += "display: none;";
    }

    const titleStyle: string = (iconStyle.length == 0) ? "display: none;" : "";
    
    const expandIconClasses = {
        [finalIconClass1]: isState1 && (finalIconClass1.length > 0),
        [finalIconClass2]: !isState1 && (finalIconClass2.length > 0)
    };

    return (
        <div class={CSS.base}>
           
            <div class={CSS.container}>
                <div class={CSS.panel}>
                    <div aria-label={tooltip} title={tooltip} role="button" tabindex="0" class={CSS.button} bind={this} onclick={this._toggle} onkeydown={this._toggle}>
                        <span aria-hidden="true" classes={expandIconClasses} style={iconStyle}></span>
                        <span style={titleStyle}>{title}</span>
                    </div>
                </div>
            </div>
        </div>
    );

}


@accessibleHandler()
private _toggle() {
    this.state = (this.state == ToggleState.State1) ? ToggleState.State2 : ToggleState.State1;
    this.toggle(this.state);
}
}

export = SmallToggleButton;

And below is the view model of which we want to create instance:

///

/// 
///

import { subclass,declared} from "esri/core/accessorSupport/decorators";

import _WidgetBase = require("esri/widgets/Widget");

@subclass("compass.widgets.SmallActionButtonViewModel")

class SmallActionButtonViewModel extends declared(_WidgetBase) {

public static actionEventName: string = "smallActionButtonClicked";

constructor() {
    super();
}

protected action(): void {
    this.emit(SmallActionButtonViewModel.actionEventName, {});
}
}

export = SmallActionButtonViewModel;

Please help.

Thanks,
Abhinav

**Comment by jcfranco** [comment]
The [following example](https://github.com/jcfranco/4x-widget-patterns/blob/master/patterns/UsingDijit.tsx) shows how to do this.

If you'd like more help, [per our contributing guidelines](https://github.com/Esri/jsapi-resources/blob/master/CONTRIBUTING.md), I'd recommend you contact [Esri Support](https://support.esri.com/contact-tech-support).
