### ISSUE TITLE
Add popupTemplate property to GraphicsLayer

### ISSUE THREAD

**Issue by COV-GIS** [Esri/jsapi-resources#167]
I am reporting an issue with 

- [x] TypeScript definitions
- [ ] another resource in this repository

Prior to 4.10 setting `popupTemplate` on `GraphicsLayer` would not apply the popup template to graphics on a graphics layer. As of 4.10 it does.

It isn't documented in the reference, so maybe this functionality is just a test or not planned for public consumption. Either way...please consider adding `popupTemplate` property to `GraphicsLayer` so as not to have to extend an interface to avoid type errors. Thanks.

**Comment by driskull** [comment]
Thanks @COV-GIS.

Setting a `popupTemplate` on a `GraphicsLayer` shouldn't be supported since it has no schema so we will work on getting that removed. Each graphic should have a popupTemplate applied individually.

Does that make sense?

**Comment by COV-GIS** [comment]
Not entirely. It's a improvement IMHO. I'll be sad to see it backed out.

Thanks for the reply and heads up @driskull.
