### ISSUE TITLE
FeatureLayer

### ISSUE THREAD

**Issue by abdel-abdelrazek** [Esri/jsapi-resources#169]
Hello everyone,
I really have an issue, i spent alot of time trying to fix it but still not able to do so.
when I add **Featurelayer** to the map it is rendered correctly in **development mode** in **all browser**, but when I build the project it does so only in chrome and Edge but **not in IE11**,
So kindly if there is something I should do to have it working in **IE11**, I will be grateful if you let me know.

This happens when i use the following example
[webpack-Demo 4.10](https://github.com/Esri/jsapi-resources/tree/master/4.x/webpack/demo)

And also when i use **React-ArcGIS** package

It only works fine when i used this example
[webpack-Demo 4.9](https://github.com/odoe/jsapi-webpack)

but unfortunately it uses v 4.9 and i need to work with v 4.10

**Comment by odoe** [comment]
@abdel-abdelrazek does it throw any error messages or something else in the IE11 console? I thought it might be the Promise shim, but it is included in the demo app.

Thanks!

**Comment by abdel-abdelrazek** [comment]
@odoe , thank you so much for your reply, i really appreciate it.

I want also to add that i have tried this new package  @esri/react-arcgis 
and unfortunately the same issue happens 

And yes there is a common error i receive in the IE11 console using this package and webpack demo.
which is "Object doesn't support this action"

Kindly you can also check this error here [error pic](https://pasteboard.co/HVYtqWQ.png)

Thanks again

**Comment by ycabon** [comment]
Hi @abdel-abdelrazek, this issue is likely due to the version of IE11. Can you update it through Windows update? Which version are you currently running?

**Comment by abdel-abdelrazek** [comment]
@ycabon thank you so much for your reply.
The version my organisation using is 11.407.17134.0.

Please let me know if it is supposed to be rendering on this version or we must update it,

kindly check this pic for full details about it.
[IE Version](https://pasteboard.co/HVYVLX5.png)

Thanks in advance.

**Comment by ycabon** [comment]
> Please let me know if it is supposed to be rendering on this version or we must update it,

I suggest to update it.

**Comment by abdel-abdelrazek** [comment]
It is really hard to be done, but i will give it a try with the IT department.

But what i really don't understand, is that the FeatureLayer renders perfectly in development mode.
But when i build the project and use it in production mode, the Featurelayer doesn't render ...!!

so if the problem related to the version i'm using, i think it shouldn't render in any modes.

Thank you any @ycabon  I really appreciate it.
