### ISSUE TITLE
RequireJS demo app "single" build is incomplete

### ISSUE THREAD

**Issue by JGSimko** [Esri/jsapi-resources#17]
Making a new ticket since my last comment in https://github.com/Esri/jsapi-resources/issues/15 was missed/ignored.

The single file build for the requireJS configuration doesn't contain all of the required files. You can reproduce this by running the build and then searching through the compiled main.js for any of the following keywords used in the non-compiled main.js:
- "measureDiv"
- "map-area"
- "esri/dijit/Measurement"

Am I missing something here? I've got a couple other issues I'm encountering with my own app specific code that'd I'd like to reproduce in this sample project but I can't if it doesn't build into a single file.

**Comment by odoe** [comment]
Sorry, closed your issue by mistake while fixing another.

I'm not able to reproduce this issue. When I search the compiled `main.js` file, I can find all those keywords.

Are you seeing any console errors that stop the build before it's complete? The fix that was just completed this morning fixed an issue with the build file related to not including the `esri/layers/GraphicsLayer` in the single file.

**Comment by JGSimko** [comment]
Ah, you're right. This does build correctly when checked out fresh from github. My issue is only relevant in the scope of issue #15 . When I added the following to Gruntfile.js (in the "options" section of the "requirejs:single" task) it stopped building correctly:
```
          packages: [{
            name: 'dojox',
            main: 'main'
          }],
          deps: ['app/main']
```

I also modified the main.js to the following (as noted in the other ticket):

```
define([
  "esri/map",
  "esri/dijit/Measurement",
  "esri/tasks/PrintTask",
  "dojo/domReady!"
], function (Map, Measurement, PrintTask) {
  var map = new Map("map-area", {
    basemap: "dark-gray",
    center: [-119.11, 36.65],
    zoom: 7,
    minZoom: 7,
    maxZoom: 9
  });
  map.on('load', function () {
    var measurement = new Measurement({
      map: map
    }, document.getElementById('measureDiv'));
    measurement.startup();
    console.log("PrintTask loaded: ", PrintTask);
  });
});
```

I wouldn't doubt that I did something wrong...

**Comment by JGSimko** [comment]
And I just realized the requireJs config for the demo is inline in the index.html. I also added the deps: line to the gruntfile which I think was incorrect as well.

**Comment by JGSimko** [comment]
I've done a bunch of tests and everything I need seems to be working in the scope of this demo application. I do have a difference with how it is running in my application though (not too big of a deal because I have a work around).

When I run the single file build the dijit template files get appended with an incorrect prefix. E.g. : "dojo/dijit/templates/MenuItem.html" instead of "dojo/text!/dijit/templates/MenuItem.html" and then when they are required elsewhere the dependency gets set up like "dojo/./templates/MenuItem.html" instead of "dojo/text!./templates/MenuItem.html". Any thoughts on why this would happen? I've got non-dojo templates getting defined/injected in other parts of the code that work fine.

Here are my requireJS "single" and "support" tasks (I honestly don't know what the support task is doing... It is pretty much a direct copy/paste of what this project has)  

```
            support: {
                options: {
                    baseUrl: '<%= appConfig.webapp %>/scripts/spatial-library',
                    dir: '<%= appConfig.dist %>/scripts/spatial-library',
                    optimize: 'uglify2',
                    optimizeCss: 'standard.keepLines.keepWhitespace',
                    throwWhen: { optimize: false  },
                    paths: {
                        'esri': 'empty:',
                        'dojo': 'empty:',
                        'dijit': 'empty:',
                        'dojox': 'empty:',
                        'dgrid': 'empty:',
                        'dstore': 'empty:',
                        'put-selector': 'empty:',
                        'xstyle': 'empty:'
                    },
                    fileExclusionRegExp: /test|tests|esri/g
                }
            },
            "single": {
                options: {
                    mainConfigFile: '<%= appConfig.webapp %>/scripts/spatial-library/main-build.js',
                    baseUrl: '<%= appConfig.webapp %>/scripts/spatial-library',
                    name: 'main',
                    out: '<%= appConfig.dist %>/scripts/spatial-library/main.js',
                    locale: 'en-us',
                    inlineText: true,
                    optimize: 'none', //'none' for debugging
                    has: {
                        'config-selectorEngine': 'acme',
                        'dojo-trace-api': 0,
                        'dojo-log-api': 0,
                        'dojo-publish-privates': 0,
                        'dojo-sync-loader': 0,
                        'dojo-xhr-factory': 0,
                        'dojo-test-sniff': 0,
                        'dom': 1,
                        'extend-esri': 0,
                        'dojo-has-api': 1,
                        'dojo-undef-api': 0
                    },
                    paths: {
                        requireLib: '../../bower_components/requirejs/require',
                        'dgrid': 'empty:',
                        'xstyle': 'empty:',
                        'esri/layers/GraphicsLayer': 'empty:',
                        'dojo/query': 'empty:', // becasue css selector engine is dynamically loaded
                        'dojox/gfx': 'empty:', // because this dynamically loads a renderer
                        'dojo/i18n': '../../bower_components/i18n/i18n', // only needed to get build working
                        'dojo/text': '../../bower_components/requirejs-text/text',
                        'dojo/domReady': '../../bower_components/requirejs-domReady/domReady'
                    },
                    include: [
                        'requireLib',
                        'esri/dijit/Attribution'
                    ],
                    exclude: [
                        'dojo/domReady',
                        'dojo/has',
                        'xstyle',
                        'dgrid',
                        'dojox',
                        'dojo/i18n' // some methods not available with RequireJS
                    ],
                    throwWhen: { optimize: false }
                }
            }
```

There is nothing special going on in the main config file. It just defines the esri/dojo packages, other dependencies, and shims for the other dependencies. It'd be great if you're able to notice anything odd otherwise I could just make a replace task to fix those lines.

Thanks again for your help, feel free to close this ticket whenever.
