### ISSUE TITLE
MapView missing takeScreenshot

### ISSUE THREAD

**Issue by shjusti** [Esri/jsapi-resources#170]
Looks like the takeScreenshot function on the MapView new to 4.10 hasn't made the typings file.  The Screenshot type that its promise returns also appears to be missing.

**Comment by dasa** [comment]
Are you sure you're using the 4.10 version? I see this line:

`takeScreenshot(options?: MapViewTakeScreenshotOptions): IPromise<Screenshot>;`

At: https://raw.githubusercontent.com/Esri/jsapi-resources/master/4.x/typescript/arcgis-js-api.d.ts

**Comment by shjusti** [comment]
That must be the issue, my package.json file says its supposed to be on 4.10, but I don't have that line in my file so npm install must be pulling something older.  Thanks for the quick response!

**Comment by dasa** [comment]
> npm install must be pulling something older.

OK, check the version shown on line 1.

**Comment by shjusti** [comment]
Yep, was getting 4.7, which is what I originally installed.  This was the first typescript project I worked on and I'm pretty sure I messed something up in my original install as my package.json at the root says 4.10 but I also have a package.json inside /node_modules/@types/arcgis-js-api and its half 4.7 and half 4.10.

**Comment by dasa** [comment]
Try running: `npm install @types/arcgis-js-api@latest --save-exact`

**Comment by shjusti** [comment]
That did it! though it took me 3 tries cause I didn't realize vs code was holding onto the old file contents in a tab and when I thought I was re-opening the file, it was just focusing the tab with 4.7 still in it.

Thanks a lot for the help
