### ISSUE TITLE
js-api is too big,can it be simplified

### ISSUE THREAD

**Issue by Amos-Zhao** [Esri/jsapi-resources#171]
the js file is too big and seperated thus make project package process add extra time and it can be 2min and more

**Comment by odoe** [comment]
Do you mean with the webpack-plugin or a Dojo build? Initial webpack build in development may take a minute or so depending on your machine, but subsequent development builds should be a couple of seconds.

A production webpack build could take up to 2 mins or more depending on your application, but remember a production webpack build is also optimizing all the code as well. Build bundles can range in size, from the initial bundle being maybe 256KB to smaller bundles at just 2KB-10KB. It just depends on your application. But there is no way to really get the initial bundle much smaller at the moment.

A dojo build can definitely take quite a while, but no way around that.
