### ISSUE TITLE
Clobbering the focus outline

### ISSUE THREAD

**Issue by tograh** [Esri/jsapi-resources#172]
In upgrading an app from an earlier 4.6/bower build, I've found that the 4.10 map gained a blue focus ring, when focussed.  To disable this (for reasons), I had to override the css like so:

.esri-view .esri-view-surface--inset-outline:focus::after {
  outline: none;
}

This is uncomfortably coupled with the underlying SDK css implementation.  Is there a better way?

**Comment by jgravois** [comment]
this is just an FYI, but the blue focus ring is an [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/) accessibility feature.

**Comment by tograh** [comment]
Right.  In our case, we're signaling focus differently (redundantly, in this particular case), but I didn't want get into that.
