### ISSUE TITLE
Webpack app and demo not working in IE-11

### ISSUE THREAD

**Issue by rbobbitt-gsi** [Esri/jsapi-resources#173]
I am reporting an issue with 

- [ ] TypeScript definitions
- [x ] another resource in this repository

I updated my 4.9 webpack app to use javascript api 4.10, and got an error in IE 11.
I just downloaded the Webpack demo using 4.10, ran npm install and get the same error.
The code works in Chrome, Edge, and Firefox.

The error in IE I am getting in my code and the demo is:

SCRIPT5009: 'Promise' is undefined
index.4348dc1f90743dc2b0e0.js (259,14)

And the code there is this (line 259 is if(has instanceof Promise) {

var has = findModule("dojo/has", null, true);
	if (has instanceof Promise) {             <=========== ERROR HERE
          return has.then(function(has) { return resolve(has); }); // eslint-disable-line no-shadow
	} else {
	return resolve(has);	}

**Comment by odoe** [comment]
I moved the Promise shim into the config of the sample. This might fix it, could you please check again. Thanks!

**Comment by rbobbitt-gsi** [comment]
I was able to fix it in IE-11 by including this in index.html

  <script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=es6"></script>

Found it here : https://github.com/Microsoft/TypeScript/issues/14308#issuecomment-390988909

It also fixed my app I was updating to 4.10 as well.

**Comment by rbobbitt-gsi** [comment]
Actually not a great solutions, I get a CERT_INVALID on my test machine.

**Comment by rbobbitt-gsi** [comment]
I had to use the @babel/polyfill to work on my locked down test system (mentioned a couple of posts later in the thread)

https://github.com/Microsoft/TypeScript/issues/14308#issuecomment-410825132

Which is just 

npm install --save @babel/polyfill

Then modifying web.config.ts to use this entry:

index: ["@babel/polyfill/noConflict", "./src/css/main.scss", "./src/index.ts"]

**Comment by odoe** [comment]
This works now. Had to move the Promise shim to the webpack config. Tested in IE11 on Win10.

Thanks!

**Comment by Biboba** [comment]
Hi @odoe,

Thanks for the fix.
I believe this fix should also be applied to arcgis-js-cli:
https://github.com/Esri/arcgis-js-cli

Thanks
