### ISSUE TITLE
How to include locale file in dojo custom build?

### ISSUE THREAD

**Issue by ghost** [Esri/jsapi-resources#174]
I am reporting an issue with 

- [ ] TypeScript definitions
- [x] another resource in this repository

I am following the guide [Using npm for Custom Builds](https://developers.arcgis.com/javascript/latest/guide/using-npm/index.html) to generate a custom build (Dojo).

I would like to include Japanese locale file in output build.
In build.profile.js sample, it describes that "You can define the locale for your application if you like".

```js
// You can define the locale for your application if you like
// includeLocales: ["en-us"]
```

So I add Japanese locale like this. Then I run `npm run build` script.

```js
// You can define the locale for your application if you like
includeLocales: ["ja-jp"]
```

When I open the output build file, I get an error.
It says that locale file is not found.

![error](https://user-images.githubusercontent.com/12059203/51964995-87ed6380-24ab-11e9-8923-624f7359e540.png)

Also the output folder does not have locale file which dojoLoader try to load.

![folder](https://user-images.githubusercontent.com/12059203/51965006-8cb21780-24ab-11e9-929f-3225894795ce.png)

When I change browser locale to English, the output build works.

**Comment by dasa** [comment]
Try adding this entry to the `moment` package definition in your profile:
https://github.com/Esri/jsapi-resources/blob/master/4.x/npm/demo/build.profile.js#L89

`        packageJson: {},`

This should make the Dojo build ignore this file, which makes Dojo ignore the locale files:
https://github.com/moment/moment/blob/master/package.js

/cc @odoe

**Comment by ej-asuzuki** [comment]
I tried, but build was failed.

Is the code below what you said?

```js
{
  name: "moment",
  location: DIR + "/moment",
  main: "moment",
  trees: [
    // don"t bother with .hidden, tests, min, src, and templates
    [".", ".", /(\/\.)|(~$)|(test|txt|src|min|templates)/]
  ],
  resourceTags: {
    amd: function(filename, mid) {
      return /\.js$/.test(filename);
    }
  },
  packageJson: {}
},
```

The error message thrown is below.

```cmd
> arcgis-js-api-sample-app@1.0.0 build C:\work\jsapi\product\custom-builds\esrijs-npm-dojo
> grunt build

Running "clean:build" (clean) task
>> 0 paths cleaned.

Running "dojo:dist" (dojo) task

Building Dojo...
>> dojo build error: Error: Unable to retrieve packages for determining optional package support in dstore
Warning: Task "dojo:dist" failed. Use --force to continue.

Aborted due to warnings.

npm ERR! Windows_NT 10.0.17134
npm ERR! argv "C:\\Program Files (x86)\\Nodist\\v-x64\\10.15.0\\node.exe" "C:\\Program Files (x86)\\Nodist\\npmv\\4.0.5\\bin\\npm-cli.js" "run" "build"
npm ERR! node v10.15.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! arcgis-js-api-sample-app@1.0.0 build: `grunt build`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the arcgis-js-api-sample-app@1.0.0 build script 'grunt build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the arcgis-js-api-sample-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs arcgis-js-api-sample-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls arcgis-js-api-sample-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\work\jsapi\product\custom-builds\esrijs-npm-dojo\npm-debug.log
```

**Comment by dasa** [comment]
Yes, that looks right, but it shouldn't have broken the build like that. Can you share your whole build profile?

**Comment by ej-asuzuki** [comment]
I was not able to attach build file because it was to large.
I created repository. Please check it.
https://github.com/ej-asuzuki/custom-builds

I haven't check all files in the folder, but index.html was not created.

**Comment by dasa** [comment]
Can you share your `build.profile.js`? I don't see that in the download.

**Comment by ej-asuzuki** [comment]
Sorry, I uploaded it in the repository.

**Comment by dasa** [comment]
I found this error in the build-report.txt file:

```
error(307) Failed to evaluate module tagged as pure AMD (fell back to processing with regular expressions).
	module: moment/ender; error: ReferenceError: $ is not defined
```

Try changing the `moment` package's `resourceTags` to this:

```js
        resourceTags: {
          miniExclude: function(filename, mid) {
            if (mid.indexOf("/min/") > -1 || mid.indexOf("/src/") > -1) {
              return true;
            }
            return [
              "moment/ender",
              "moment/package"
            ].indexOf(mid) > -1;
          }
        }
```
