### ISSUE TITLE
how can I integrate antd to my map built with dojo loader (4.x API) ?

### ISSUE THREAD

**Issue by TomBlackTan** [Esri/jsapi-resources#176]
Is that a good idea? how can I do that ?  Do I have to use webpack and some compilation tools?

**Comment by tomwayson** [comment]
> Do I have to use webpack and some compilation tools?

That depends. If you're bringing antd (and React) in to an ArcGIS app, see https://developers.arcgis.com/javascript/latest/sample-code/widgets-frameworks-react/index.html.

You'd likely need to add additional `packages` to the `dojoConfig` for whatever antd files you need to load (see: https://ant.design/docs/react/introduce#Import-in-Browser).

If you're bringing ArcGIS into a React app w/ antd, then you'd just add antd to your React app as normal using whatever build tools you want. Then you should go here to learn about how to add the ArcGIS API: https://github.com/Esri/jsapi-resources/tree/master/frameworks/react

**Comment by TomBlack01** [comment]
Thank u for your patience. 
  I're bringing antd (and React) in to an ArcGIS app.I`m not familiar with these build tools, while antd and react are usually coded with JSX which need to be converted to normal js by babel  before deployment . In this demo [https://developers.arcgis.com/javascript/latest/sample-code/widgets-frameworks-react/index.html](https://developers.arcgis.com/javascript/latest/sample-code/widgets-frameworks-react/index.html) it use babel.js to  converte it at runtime , that will cause performance problems. How can I compile the JSX to js  when  integrating antd (and React) into my ArcGIS app without using the  babel.js script  at runtime? If I need a build tool ,which one is better?

**Comment by tomwayson** [comment]
Wow. I never noticed that sample uses babel.js at runtime. I mean that makes sense, but @odoe is a sneaky little sunnovagun.

In that case, I suggest you use whatever build tools _you_ would normally use for a React/antd app, and then add the ArcGIS API using one of the resources listed here: https://github.com/Esri/jsapi-resources/tree/master/frameworks/react

Finally, it [won't bee too long](https://github.com/Esri/arcgis-js-cli/pull/16) before you can use the arcgis CLI to scaffold out a new project that uses React built w/ webpack like `arcgis create my-new-app --type=react`.
