### ISSUE TITLE
requirejs sample loads 164 individual .css files

### ISSUE THREAD

**Issue by jgravois** [Esri/jsapi-resources#18]
the dojo build sample produced what i'd expect, but i counted 164 unconcatenated stylesheets loading when i launched the built requirejs sample.  

STR:
1. clone repo
2. cd into `./bower/requirejs`
3. `npm install`
4. `npm build` (all green so far)
5. run `/dist/index.html` and inspect network traffic.

![screenshot 2016-02-16 16 11 32](https://cloud.githubusercontent.com/assets/3011734/13095620/fed58bee-d4c7-11e5-9ad1-51881828f8d3.png)

can anyone else confirm the behavior?

**Comment by odoe** [comment]
It looks like `r.js` needs separate tasks to build the css. For now you can add this to the `requirejs:` section of the `Gruntfile`.

```javascript
      esricss: {
        options: {
          cwd: './',
          cssIn: './src/esri/css/esri.css',
          out: './dist/esri/css/esri.css',
          optimizeCss: 'standard'
        }
      },
      dijitcss: {
        options: {
          cwd: './',
          cssIn: './src/dijit/themes/nihilo/nihilo.css',
          out: './dist/dijit/themes/nihilo/nihilo.css',
          optimizeCss: 'standard'
        }
      },
```

And update the `build` task.

`grunt.registerTask('build', ['clean', 'requirejs:support', 'requirejs:single', 'requirejs:esricss', 'requirejs:dijitcss', 'copy']);`

I'll test a little further before making the changes, but that should work.

Thanks!

**Comment by jgravois** [comment]
thanks for the help rene.  i'll test and PR this addition (along with a few other little things).
