### ISSUE TITLE
npm build Dojo building error

### ISSUE THREAD

**Issue by fabianm536** [Esri/jsapi-resources#180]
I'm trying to make a custom build using the 4.10 JS API, but I keep getting a build error:

18 verbose node v10.15.1 19 verbose npm  v6.9.0 20 error code ELIFECYCLE 21 error errno 3 22 error arcgis-js-api-sample-app@1.0.0 build: `grunt build` 22 error Exit status 3 23 error Failed at the arcgis-js-api-sample-app@1.0.0 build script. 23 error This is probably not a problem with npm. There is likely additional logging output above.

Before in the 'npm install'  I had this error:

verbose stack Error: node-sass@4.7.2 postinstall: `node scripts/build.js`

So, I changed the "node-sass" version by  "node-sass": "~4.9.0" in the package.json file.

**Comment by odoe** [comment]
I'm not seeing this errr with the latest samples. I've updated all node dependencies on the projects, so should be good to go. Feel free to let me know if this issue continues. Thanks.
