### ISSUE TITLE
Typings error in FeatureTemplatesViewModel

### ISSUE THREAD

**Issue by Biboba** [Esri/jsapi-resources#181]
I am reporting an issue with 

- [X] TypeScript definitions
- [ ] another resource in this repository

Using the featureTemplatesViewModel, I noticed that there is a typescript error when using the snippet provided from the documentation to listen to the template select event:
```js
templatesVM.on("select", function(evtTemplate) {})
```
https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-FeatureTemplates-FeatureTemplatesViewModel.html#events-summary

No "on" IHandle property is declared in the featureTemplatesViewModel.

Thanks,

Nicolas

**Comment by Biboba** [comment]
Also, I am under the impression that the template "items" property lacks array typings.
Indeed, when trying to iterate through the items, I have errors because neither "esri.TemplateItem" nor "esri.TemplateItemGroup" is an array:
https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-FeatureTemplates-FeatureTemplatesViewModel.html#items

Thanks !

**Comment by hgonzago** [comment]
This has been fixed for the next typings update. Thanks for bringing it to our attention.

**Comment by Biboba** [comment]
Great thanks for the update and the quick fix !
