### ISSUE TITLE
JSX.IntrinsicElements definition causes typescript build errors in React applications

### ISSUE THREAD

**Issue by tomwayson** [Esri/jsapi-resources#188]
I am reporting an issue with 

- [x] TypeScript definitions
- [ ] another resource in this repository

Reporting this on behalf of @tcatkins99 and @gpartida.

See: https://github.com/Esri/react-arcgis/issues/85#issuecomment-478093261

**Comment by ajturner** [comment]
Running into this issue using Storybook with a JSAPI component built with Stencil.js. 

Any progress on a resolution?

**Comment by jcfranco** [comment]
This should be fixed in the next release (4.15). We'll ping you when it's available in `arcgis-js-api@next`

**Comment by bchopson** [comment]
Temporary fix: https://medium.com/@elenasufieva/handling-type-declarations-clash-in-typescript-b05b10723f47

**Comment by odoe** [comment]
@tomwayson could you try the latest typings in jsapi-next as described here https://github.com/Esri/feedback-js-api-next#typescript-typings

Thanks
