### ISSUE TITLE
4.12 breaks my app on IE11 

### ISSUE THREAD

**Issue by Abexdatl** [Esri/jsapi-resources#189]
I am reporting an issue with 

- [ ] TypeScript definitions
- [X ] another resource in this repository

My application which is in production for more than a year now and is built using arcgis js 4.x and angular breaks once I upgrade it to use 4.12. 

The map and other esri widgets like layer, search and legend DO not load. 

This is the error that I get in the debugger "Object.getPrototypeOf: 'this' is not an Object" .

If I downgrade the arcgis js version from 4.12 to 4.10 the map and other widgets like layer, search and legend load fine. 

what changed to cause this?

FYI, I have all the IE 11 polyfills  .

============================================
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/weak-map';
import 'core-js/es6/set';
/** IE10 and IE11 requires the following for NgClass support on SVG elements */
import 'classlist.js';  // Run `npm install --save classlist.js`.
/** IE10 and IE11 requires the following for the Reflect API. */
import 'core-js/es6/reflect';
import 'core-js/es7/array';
import 'core-js/es7/object';
/** Evergreen browsers require these. **/
// Used for reflect-metadata in JIT. If you use AOT (and only Angular decorators), you can remove.
import 'core-js/es7/reflect';
/**
* Required to support Web Animations `@angular/platform-browser/animations`.
* Needed for: All but Chrome, Firefox and Opera. http://caniuse.com/#feat=web-animation
**/
import 'web-animations-js';  // Run `npm install --save web-animations-js`.
/***************************************************************************************************
* Zone JS is required by default for Angular itself.
*/
import 'zone.js/dist/zone';  // Included with Angular CLI.
==================================================

**Comment by odoe** [comment]
Is this with the CDN? Doing a custom local build?

**Comment by Abexdatl** [comment]
this is with the CDN

**Comment by andygup** [comment]
@Abexdatl since this is about the CDN and Angular can you open a new issue over on our Angular CLI repo: https://github.com/Esri/angular-cli-esri-map/issues? 

That way it's easier to track since this repo is more for folks doing custom builds.
