### ISSUE TITLE
PrintTemplateLayoutOptions -> legendLayers and customTextElements optional?

### ISSUE THREAD

**Issue by COV-GIS** [Esri/jsapi-resources#190]
I am reporting an issue with 

- [x] TypeScript definitions
- [ ] another resource in this repository

`customTextElements` is easy enough to provide an empty array but by the [absence](https://developers.arcgis.com/javascript/latest/api-reference/esri-tasks-support-PrintTemplate.html#layoutOptions) of `legendLayers` the api knows to include all ops layers.

**Comment by dasa** [comment]
Can you set `legendLayers` to `null` until this is fixed?

**Comment by COV-GIS** [comment]
`null` doesn't lint either. I've been using `any` type assertion. But really shouldn't be. Thanks for looking into this @dasa.

**Comment by jkieboom** [comment]
Are you using strict nullability? Unfortunately our typings are not strict nullability compatible at the moment.

**Comment by COV-GIS** [comment]
I've just been adding `?` to the definition file. Easy enough but not ideal. Thank you for your consideration @dasa.
