### ISSUE TITLE
TypeScript Definition findServerinfo case issue

### ISSUE THREAD

**Issue by sbills2** [Esri/jsapi-resources#193]
I am reporting an issue with 

- [x] TypeScript definitions
- [ ] another resource in this repository

In the 4.x TypeScript Definition, the findServerinfo method in the IdentityManager class seems to be capitalized incorrectly. When I call it as findServerinfo I am getting a runtime error. I am able to cast the IdentityManager as an any type and call it as findServerInfo which seems to work just fine. I'm currently using the 4.11 version.

**Comment by dasa** [comment]
Thanks, this doc issue will be fixed in the 4.13 release.

**Comment by dasa** [comment]
Fixed: https://developers.arcgis.com/javascript/latest/api-reference/esri-identity-IdentityManager.html#findServerInfo
