### ISSUE TITLE
Heat-map based on a new field which is sum of multiple fields

### ISSUE THREAD

**Issue by fnick851** [Esri/jsapi-resources#195]
I have read the issue guideline note but I am really having trouble reaching ArcGIS support in anyway. So I am posting a question here.

I have a service that gives a layer such as this one: https://services6.arcgis.com/Wwv1InPxRQv6NCzu/ArcGIS/rest/services/WIOA_Public__2_year/FeatureServer/0.

 

It has many fields. How do I use the JS API to dynamically display a heat-map with color based on the sum of two or more fields?

(E.g. say I want to add "Associate_s_degree" to "Bachelor_s_degree" resulting a sum field which will be used for determining color. It does not have to be strictly creating a new field on the fly if that's impossible. As long as I can display the color of polygon for each heat-map feature based on the sum of multiple fields for each feature.)  

 

Thanks.

**Comment by fnick851** [comment]
No longer relevant.

**Comment by bsvensson** [comment]
Hi @fnick851 - thank you for your interest in the ArcGIS API for JavaScript.

As mentioned in the issue guideline, if you have generic requests for assistance with the [ArcGIS API for Javascript](http://js.arcgis.com), it's better to use one the below avenues.

* Esri Tech Support - https://support.esri.com/contact-tech-support
* the Esri community on GeoNet - https://geonet.esri.com/community/developers/web-developers/arcgis-api-for-javascript

We welcome feedback and questions related to the TypeScript definitions and other files in this repository here.

Cheers,
Bjorn
