### ISSUE TITLE
apply webpack plugin in vue project

### ISSUE THREAD

**Issue by wuhuxiao** [Esri/jsapi-resources#200]
i used vue-cli to make my vue map project and at the begining i use esri-loader to import arcgis api.As i change my way to webpack-plugins,it is nice to aplly js apis.however when i import the scss style from webpacks,it does not work.
I am reporting an issue with 

- [ ] TypeScript definitions
- [ ] another resource in this repository

**Comment by wuhuxiao** [comment]
is there anyone who apply arcgis-webpack-plugins  to vue-cli projects totally?especially the scss style,what the webpack config like to apply main.scss.

**Comment by odoe** [comment]
Here is a repo that uses the webpack plugin with the output of a vue-cli app
https://github.com/crackernutter/arcgis-webpack-vue-calcite
