### ISSUE TITLE
Some feature layers are not loading after building app (dojo 3.31)

### ISSUE THREAD

**Issue by Ganeshmoorthi** [Esri/jsapi-resources#202]
I am reporting an issue with 

- [ ] TypeScript definitions
- [X ] another resource in this repository

I took the dojo (3.x) sample and added below feature layer to map. After building the application the below feature layer is not rendering on map.

var featureLayer = new FeatureLayer("https://services.arcgis.com/V6ZHFr6zdgNZuVG0/ArcGIS/rest/services/socal_precincts_points_2008/FeatureServer/0");
  featureLayer._hasLegend = true;
  map.addLayer(featureLayer);

**Comment by Ganeshmoorthi** [comment]
Do i need to include any additional package to display PBF format layers? 

After build i am able to view this featurelayer https://services.arcgis.com/V6ZHFr6zdgNZuVG0/ArcGIS/rest/services/superflightsWPoints/FeatureServer/0

But, this layer is not rendering and not seeing any error message in console or network tab. https://services.arcgis.com/V6ZHFr6zdgNZuVG0/ArcGIS/rest/services/socal_precincts_points_2008/FeatureServer/0

**Comment by odoe** [comment]
Still looking into this issue at the moment. It's just odd that it works unbuilt, but not built. Tricky one to track down. Thanks!

**Comment by Ganeshmoorthi** [comment]
Thanks @odoe for looking this issue. Will wait for your update.

**Comment by Ganeshmoorthi** [comment]
After disabling webgl, i am able to view the layer.

"esri-featurelayer-webgl": 0

**Comment by Ganeshmoorthi** [comment]
@odoe  Did you get any chance to test this issue? Please let me know if you found any solution.

**Comment by odoe** [comment]
This will be fixed in the next release in early April

**Comment by Ganeshmoorthi** [comment]
OK thanks
