### ISSUE TITLE
DrawPointActionEvent properties incorrectly typed at 4.16

### ISSUE THREAD

**Issue by tcatkins99** [Esri/jsapi-resources#213]
I am reporting an issue with 

- [x] TypeScript definitions
- [ ] another resource in this repository

The properties for `DrawPointActionEvent` have changed in 4.16 however the typings do not reflect this (nor does the JS API documentation either to be fair)

In 4.15, one could get the coordinates of the DrawPointAction using the `coordinates` property.
At 4.16, this property is now called `vertices`, however neither the documentation nor the Typescript typings reflect this change.

I have not investigated other draw action events so not sure if they are similarly affected or not, but just wanted to give a heads up so the docs and typings can be updated.

**Comment by SaschaBrunnerCH** [comment]
Thank you very much for reporting this. 
It is a bug in the version 4.16 of the API and will be fixed in the next release. In the meantime you can use the following workaround, instead of `evt.coordinates` use `evt.vertices[0]`

**Comment by SaschaBrunnerCH** [comment]
This got fixed with 4.17.
We appreciate you are reporting issues!
