### ISSUE TITLE
NPM Demo 4.16

### ISSUE THREAD

**Issue by leevers** [Esri/jsapi-resources#214]
Will the npm build demo be updated to the 4.16 API?

I tried doing it myself but have run into issues with tslib. I tried updating it to match the version in the webpack demo but I am still not getting a stable build.

I am reporting an issue with 

- [ ] TypeScript definitions
- [x] another resource in this repository

**Comment by odoe** [comment]
Forgot about that one. Updated, thanks!

**Comment by leevers** [comment]
I tried updating the package.json with the new api version.

It mostly works but I seem to have issues with geodesicBuffer after doing this.

I just throws an "Internal Error" when trying to do a geodesicBuffer

I have modified the app in the demo in git if you want to have a look. Just use the polygon sketch tool.

https://github.com/leevers/jsapi-resources/tree/master/4.x/npm/demo

**Comment by odoe** [comment]
Ah, thanks @leevers, I think I figured out the issue. Please bump the version to `arcgis-js-api@4.16.2`, that should work now.

**Comment by leevers** [comment]
Thank you, this seems to be working better now
