### ISSUE TITLE
Version of arcgis-js-api.d.ts in DefinitelyTyped out of date

### ISSUE THREAD

**Issue by amervitz** [Esri/jsapi-resources#217]
I am reporting an issue with 

- [x] TypeScript definitions
- [ ] another resource in this repository

Hi,

There appears to be a mismatch between the types of these items in this repository and the version in the DefinitelyTyped project that gets downloaded when installing the npm `@types/arcgis-js-api` module. 

I am specifically looking for updates to these properties to accept strings, which are correct in this repo but outdated in DefinitelyTyped's version.
- [SimpleMarkerSymbol.size](https://developers.arcgis.com/javascript/latest/api-reference/esri-symbols-SimpleMarkerSymbol.html#size)
- [PictureMarkerSymbol.height](https://developers.arcgis.com/javascript/latest/api-reference/esri-symbols-PictureMarkerSymbol.html#height)
- [PictureMarkerSymbol.width](https://developers.arcgis.com/javascript/latest/api-reference/esri-symbols-PictureMarkerSymbol.html#width)

Is there a schedule for when the file is updated in DefinitelyTyped?

**Comment by dasa** [comment]
The type for those properties is `number`. This is the type for the getter. TypeScript doesn't support having a different type for the setter and getter, so the typings match the getters, which limits auto-casting. You can workaround this using `sms.size = "12px" as any;`.

**Comment by dasa** [comment]
Another workaround is to use the constructors, where these are typed as `number | string`.

**Comment by amervitz** [comment]
Sorry, I mistakenly thought the properties on the interfaces for `SimpleMarkerSymbol` and `PictureMarkerSymbol` had been updated. Thanks for the workaround.
