### ISSUE TITLE
Wrong Url in packages.json?

### ISSUE THREAD

**Issue by dbened-denver-water** [Esri/jsapi-resources#22]
It looks like the old URL for this project is still present in the packages.json file.  The current information in the resources.json reads as follow:
"repository": {
    "url": "https://github.com/Esri/jsapi-resources/bower/dojo"
  }

It should point to the 3.x version:
"repository": {
    "url": "https://github.com/Esri/jsapi-resources/tree/master/3.x/bower/dojo"
  }

I was unable to get npm install to work until I made that change.

Thanks
Diana Benedict

**Comment by jgravois** [comment]
thanks for catching that Diana!  i've submitted a PR (#23) to resolve the problem.
