### ISSUE TITLE
WebPack 4.x demo - map height increases in an infinite loop

### ISSUE THREAD

**Issue by slead** [Esri/jsapi-resources#224]
This issues applies to the WebPack demo at https://github.com/Esri/jsapi-resources/tree/master/4.x/webpack/demo at version 4.17 of the JS API.

I cloned a new instance of the jsapi-resources repo, cd into /jsapi-resources/4.x/webpack/demo, ran `npm install` then `npm start`, with no other changes. When the page loads, the map appears to be panning, but this is because the height of the map's div is increasing automatically and uncontrollably. Note the scrollbar on the right-hand side:

https://imgur.com/hQx6yzU

**Comment by odoe** [comment]
Just had to add the css in the webpack config to get processed. Fixed
