### ISSUE TITLE
build fials when using npm for custom dojo builds

### ISSUE THREAD

**Issue by Brave-Jun** [Esri/jsapi-resources#227]
I am reporting an issue with 

- [ ] TypeScript definitions
- [ ] another resource in this repository

Hello Analyst, does this jsapi-resources-master\4.x\npm\demo  support the next version of js api. I want to use the next version of js api in an offline environment, so I'm trying to use this demo. I can install it successfully with the npm install --save arcgis-js-api@next command, or by changing the arcgis-js-api parameter in the package.json and then npm install. but the package fails, the log message is : Failed at the arcgis-js-api-sample-app@1.0.0 build script. I would like to know if this jsapi-resources-master\4.x\npm\demo supports the next version of the js api, or how to solve this problem.

Thanks, any help is appreciate!

**Comment by odoe** [comment]
It has bit been tested with it yet. It is still upcoming.

**Comment by Brave-Jun** [comment]
> It has bit been tested with it yet. It is still upcoming. It will work, but the build configuration needs updating.

Thank you Rene, will this build configuration file be updated only after the 4.18 api release?

**Comment by odoe** [comment]
Yes, it will only be updated after the 4.18 release.

**Comment by Brave-Jun** [comment]
> Yes, it will only be updated after the 4.18 release.

Ok, thank you so much!
