### ISSUE TITLE
esm-samples/webpack: npm start failed. ERROR in ./src/index.css

### ISSUE THREAD

**Issue by rayallen001** [Esri/jsapi-resources#235]
I am reporting an issue with 

- [ ] TypeScript definitions
- [x] another resource in this repository

Windows 10, Node v12.16.1

Do the following steps:
1. Download the source code.
2. cd esm-samples/webpack
3. npm install
4. npm run start

Encounter the error:
```
ERROR in ./src/index.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleParseError: Module parse failed: Unexpected character ' ' (1:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#load
ers
(Source code omitted for this binary file)
...
79 ERRORS in child compilations
webpack 5.11.0 compiled with 80 errors and 2 warnings in 1408 ms
```

**Comment by odoe** [comment]
Can you provide more info. OS, Node version, please.

**Comment by rayallen001** [comment]
> Can you provide more info. OS, Node version, please.

Windows 10, Node v12.16.1

**Comment by odoe** [comment]
Incoming PR for this one.
https://github.com/Esri/jsapi-resources/pull/236

**Comment by benelan** [comment]
Hi Team, 

This issue reemerged after commit a3b8b85.

Looks like the original solution (PR #236) caused some issues "loading fonts, css and sourcemaps", according to PR #256.

Tested on Windows on the following Node versions:
15.9.0
14.13.1
12.19.0

**Comment by odoe** [comment]
You can try and set the `defaultAssetLoaders` to `false` and see if that fixes it.
https://github.com/Esri/arcgis-webpack-plugin#options

Windows doesn't seem to like the plugin having asset loaders as well as main app. I think I'm just going to remove it from the plugin altogether and leave it up to the apps to handle.

**Comment by benelan** [comment]
Unfortunately, changing ``useDefaultAssetLoaders`` to ``false`` didn't fix it for me.

// webpack.config.js
```diff
-  new ArcGISPlugin({ locales: ['en'] }),
+ new ArcGISPlugin({ locales: ['en'], useDefaultAssetLoaders: false }),
```

Adding back the rule from commit 8deb4b6 did fix the issue:
``` js
rules: [
      {
        test: /\.(ttf|eot|svg|png|jpg|gif|ico|wsv|otf|woff(2)?)(\?[a-z0-9]+)?$/,
        use: [
          {
            loader: 'file-loader'
          }
        ]
      },
...
```

Not sure if the original solution caused a secondary issue which needed to be fixed. Jose is able to reproduce if you need someone to help test on Windows.

**Comment by odoe** [comment]
That's what I meant. Let the app handle the loader rather than the plugin. That's why I'm going to remove it.

**Comment by benelan** [comment]
Ahh, got it, thanks
