### ISSUE TITLE
4.x TypeScript demo doesn't seem to work with custom widgets

### ISSUE THREAD

**Issue by jccartwright** [Esri/jsapi-resources#238]
I am reporting an issue with 

- [ ] TypeScript definitions
- [X] another resource in this repository

Using the project at https://github.com/Esri/jsapi-resources/tree/master/4.x/typescript/demo, I am getting the error:
"Uncaught TypeError: HelloWorld is not a constructor"

when trying to use a custom widget as described in the User Guide (https://developers.arcgis.com/javascript/latest/sample-code/widgets-custom-widget/index.html).  Steps to reproduce:
1) clone repo; cd into 4.x/typescript/demo
2) npm install
3) add source for HelloWorld.tsx into ./app
4) npm tsc 
5) modify index.html to load new widget

**Comment by hgonzago** [comment]
This has been addressed for our next doc update. Thanks
