### ISSUE TITLE
Sublayers of MapImageLayersProperties Have No Optional Properties

### ISSUE THREAD

**Issue by sgreylyn** [Esri/jsapi-resources#24]
EDIT: This is an issue with the [4.x typescript definitions](https://github.com/Esri/jsapi-resources/blob/master/4.x/typescript/arcgis-js-api.d.ts#L5271-L5277).

When following the example for creating a MapImageLayer with sublayers from [https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-MapImageLayer.html#sublayers](here), my compiler complains because the 'sublayers' property does not match the signature expected by ArcGISDynamicServiceSublayers.

This is solved by changing the ArcGISDynamicServiceProperties' subLayers property from ArcGISDynamicServiceSublayers[] to ArcGISDynamicServiceSublayersProperties[], which is probably what was intended.

**Comment by jgravois** [comment]
forgive me, but i don't quite follow you.  I was able to manipulate the sublayer property of `MapImageLayer` subsequent to it being loaded without encountering errors.

```js
var layer = new MapImageLayer({
  url: "https://sampleserver6.arcgisonline.com/arcgis/rest/services/USA/MapServer",
  sublayers: [{ id: 1, visible: false }]
});

layer.then(function() {
  layer.sublayers = [{ id: 1, visible: true }];
});
```
can you clarify what you mean by *changing the subLayers property on ArcGISDynamicServiceProperties* in version 4.0 of the the API?
by compiler do you mean the developer console in the browser?

**Comment by dasa** [comment]
Fixed at: https://github.com/Esri/jsapi-resources/commit/d142a2785af86f61e157ea48973a280582dea97c#diff-a587935e7112bf84f26ea55418f03de1R5308
