### ISSUE TITLE
React example

### ISSUE THREAD

**Issue by kupe517** [Esri/jsapi-resources#244]
Can you please add an updated example of how to use ES Modules within React. An updated version of this guide:  http://140.207.158.228/latest/guide/react/

**Comment by kupe517** [comment]
Sorry, I found the documentation here: https://github.com/Esri/jsapi-resources/tree/master/esm-samples/jsapi-create-react-app

The root ReadMe has a broken link to these examples

**Comment by andygup** [comment]
We'll update the root README. Thanks @kupe517.
