### ISSUE TITLE
Working with frameworks section is broken

### ISSUE THREAD

**Issue by EricG66** [Esri/jsapi-resources#246]
The section called "Working with Framework" is broken and it give a 404 error:

You can access this link from the following page:

https://github.com/Esri/jsapi-resources

The broken link:
https://github.com/Esri/jsapi-resources/blob/master/frameworks/README.md

**Comment by andygup** [comment]
Thanks! We have a [pull request](https://github.com/Esri/jsapi-resources/pull/245) pending that updates the main README. The old `/frameworks` directory has been replaced with this https://github.com/Esri/jsapi-resources/tree/master/esm-samples. 

Closing as in-progress.
