### ISSUE TITLE
Webpack - No matching version found for @arcgis/webpack-plugin@4.18.1.

### ISSUE THREAD

**Issue by elake2018** [Esri/jsapi-resources#249]
Cloned the project, went to the webpack folder, ran npm i

PS C:\ESRI-JS-API_4-18\jsapi-resources\esm-samples\webpack> npm i
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @arcgis/webpack-plugin@4.18.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

I am reporting an issue with 

- [ ] TypeScript definitions
- [ ] another resource in this repository

**Comment by odoe** [comment]
Fixed, that was an oversight. Thanks!
