### ISSUE TITLE
Map not displaying in Ionic-Angular-Electron and Ionic-React-Electron apps when run on desktop

### ISSUE THREAD

**Issue by brentgti** [Esri/jsapi-resources#253]
I am reporting an issue with 

- [ ] TypeScript definitions
- [x] another resource in this repository

I'm trying to create an Ionic-Angular application with a map on its main page, using ArcGIS ES Modules. I've used the code from https://github.com/Esri/jsapi-resources/blob/master/esm-samples/jsapi-angular-cli/src/app/app.component.ts to display the map. 

This works OK when I build and run the app in Android. When I try to build and run a desktop app using Electron, though, the code errors here:

`if (t = h.url, "image" === (s = h.requestOptions).responseType) {
 if (Object(_core_has_js__WEBPACK_IMPORTED_MODULE_1__["default"])("host-webworker") || Object(_core_has_js__WEBPACK_IMPORTED_MODULE_1__["default"])("host-node"))
 throw M("request:invalid-parameters", new Error("responseType 'image' is not supported in Web Workers or Node environment"), h)`

When the basemap is set to some kind of vector map, a map does appear, but other maps just leave an empty area where the map should be. Here's what I see in the console of the app window:
![image](https://user-images.githubusercontent.com/43861121/105408300-659f0400-5bf4-11eb-82d2-6ea104b0ce9c.png)

The code to get the map is in the only layer I know that will result in it showing up in the app UI, but it seems that somehow when trying to run it in an Electron window it's running in an unsupported environment.

 I was told by @andygup that this is a problem between Angular and Chrome. However, the problem is occurring in both an Ionic-Angular project and an Ionic-React project. The former is here: https://github.com/brentgti/IonicUiEsriPoc, with the code for the map in /blob/main/src/app/home/home.page.ts. The latter is here: https://github.com/brentgti/ionicReactTest, with the code for the map here: /blob/main/src/components/Map.tsx.

**Comment by andygup** [comment]
>> When the basemap is set to some kind of vector map, a map does appear, but other maps just leave an empty area where the map should be. 

Have your tried getting a basic JS API app running in Electron, by itself, without Ionic and Angular? That's the best way to try and narrow down the problem. Sorry, we don't have a sample that demos this.

**Comment by andygup** [comment]
Hi @brentgti  I was able to get a simple project going in Electron and was able to repro the error you were seeing. When I disabled node integration then the errors went away and I was able to see both vector and raster maps just fine. Have you tried setting `nodeIntegration` to false?

```js
function createWindow() {
  const win = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: false
    }
  })

```

**Comment by brentgti** [comment]
Hi @andygup, thanks for the reply. I wasn't able to get a simple Electron project working because I couldn't seem to make Electron work with EcmaScript modules (I couldn't get past "Cannot use import statement outside a module"). Can you provide more of your code? 

I'm not sure what other implications setting nodeIntegration to false may have, but it may be OK. I also don't know how to set that when Electron is wrapped inside Ionic, since the BrowserWindow isn't created the same way in that scenario. Here's how I tried in Ionic:

```javascript
const myCapacitorApp = createCapacitorElectronApp({
  mainWindow: {
    windowOptions: {
      webPreferences: {
        nodeIntegration: false
      }
    }
  }
});
```

Doing that didn't help the problem with the map, though. Thanks again.

**Comment by andygup** [comment]
Hi @brentgti, I sent you a github invite to the private repo. I didn't want to share it publicly yet since it's just a testing prototype.

**Comment by andygup** [comment]
> I also don't know how to set that when Electron is wrapped inside Ionic, since the BrowserWindow isn't created the same way

I'm not sure what the problem might be with the combination of Ionic/Capacitor/Angular/Electron. The best we can do is try to figure out the "minimum viable test case". The private repo simply uses JS API with ES modules + Webpack 5 + Electron.

**Comment by brentgti** [comment]
> Hi @brentgti, I sent you a github invite to the private repo. I didn't want to share it publicly yet since it's just a testing prototype.

Hey @andygup, I'll check out the repo, though I can't find an invitation. I've seen this problem before. Please try inviting me using my email address instead of my user name: bgrossman@gti.energy. Thanks

**Comment by andygup** [comment]
@brentgti I sent the invite via your email, let me know if that doesn't work. I can always just zip it up and email it.

**Comment by brentgti** [comment]
Thanks, @andygup. I got the invitation and will clone, run, and try to understand it shortly.

**Comment by andygup** [comment]
Closing the issue for now, the problem reported is only partially resolved - the map still isn't able to display in Ionic/Angular/Electron. However, stand-alone webpack + JS API ESM works just fine with Electron (and so does our AMD CDN).

Conclusion: There's an issue somewhere in the multi-framework implementation - with the right combination of settings and configuration it can eventually be coaxed to work, but that's beyond the scope of simple troubleshooting.
