### ISSUE TITLE
geometryEngine import giving me errror

### ISSUE THREAD

**Issue by Cyberdada** [Esri/jsapi-resources#258]
Hi, 
if I try to import geometryEngine like this:
import geometryEngine from '@arcgis/core/geometry/geometryEngine';

and then try to use it like this;   (geo being an instance of Graphic)
 return geometryEngine.geodesicLength(geo, 'meters');

I get the following error: 

ERROR in ./src/app/esri-services/geometry.service.ts 34:15-29
"export 'default' (imported as 'geometryEngine') was not found in '@arcgis/core/geometry/geometryEngine'

I can bypass this by not importing geometryEngine, and when using it typing
 return __esri.geometryEngine.geodesicLength(geo, 'meters');

Then I get no errors, 
But I dont know if this actually works. Is this the correct way, or should I do something else?
(im having a similar issue with MapViewClickEvent, I cant import it in any way, but if I prefix with __esri it works)

I am reporting an issue with 

- [ x] TypeScript definitions
- [ ] another resource in this repository

**Comment by dasa** [comment]
`geometryEngine` doesn't have a default export, so try: `import * as geometryEngine from '@arcgis/core/geometry/geometryEngine';`

**Comment by Cyberdada** [comment]
Thanks, that worked =) 
What about MapViewClickEvent?
