### ISSUE TITLE
using query tool in esm

### ISSUE THREAD

**Issue by kpermenter** [Esri/jsapi-resources#259]
What would be the best way to query a feature layer in React using this jsapi-create-react-app template? I'm having some issues figuring out how to implement this with @arcgis/core/tasks/query. Any help would be much appreciated!

**Comment by odoe** [comment]
It's the same as you would use it with the CDN, just replace `esri/` paths with `@arcgis/core/` to import the modules using the import syntax.
https://developers.arcgis.com/javascript/latest/sample-code/sandbox/index.html?sample=tasks-query

**Comment by kpermenter** [comment]
Do you guys have any examples of this in React? I think that is where I'm getting stuck... Thanks again for your help

**Comment by odoe** [comment]
I'll see if I can whip one up by end of the day.

**Comment by kpermenter** [comment]
That would be AMAZING :)

**Comment by odoe** [comment]
Here you go, this should help
https://github.com/odoe/jsapi-query-react

**Comment by kpermenter** [comment]
Thank you so much!!!

**Comment by kpermenter** [comment]
Quick question- how would you remove the query function away from the initial render so that there can be multiple queries client side? Like a dropdown list where the selection renders a new layer with an event.
As of now, I am getting errors accessing the map and view component outside of the useEffect hook when I try to split the code. Sorry, newbie here...
