### ISSUE TITLE
Modified the ES Modules Example to Use Typescript, Keep Getting a Sign In Page on Map

### ISSUE THREAD

**Issue by allidoisace** [Esri/jsapi-resources#262]
I am reporting an issue with 

- [x] TypeScript definitions
- [ ] another resource in this repository

I had to add TS on top of the ES Module example for react since there don't seem to be anything for that combination. It appears all the TS examples use ADM.

Attached is a screenshot of the sign in that pops up when I try and use `basemap: "arcgis-topographic",`. If I use what is provided in the example, everything is fine. Any login I have does not work when attempting to sign in.

Do I need to provide an API Key when using ES Modules?

![Screenshot from 2021-01-28 18-19-19](https://user-images.githubusercontent.com/20326673/106223183-cb136780-6195-11eb-8f8c-35f406fb4e12.png)

**Comment by allidoisace** [comment]
Also, if I do a refresh on this page, I receive a bunch of errors in the console log which don't seem to make sense.

```
:3000/static/js/67.chunk.js:175600 [esri.widgets.Widget] widget-intl:locale-error esri.widgets.Attribution s
console.<computed> @ :3000/static/js/67.chunk.js:175600
:3000/static/js/67.chunk.js:175600 [esri.widgets.Widget] widget-intl:locale-error esri.widgets.Zoom s
console.<computed> @ :3000/static/js/67.chunk.js:175600
:3000/static/js/67.chunk.js:175600 [esri.widgets.Widget] widget-intl:locale-error esri.widgets.Popup s
console.<computed> @ :3000/static/js/67.chunk.js:175600
:3000/static/js/67.chunk.js:175600 [esri.widgets.Widget] widget-intl:locale-error esri.widgets.Popup s
console.<computed> @ :3000/static/js/67.chunk.js:175600
:3000/static/js/67.chunk.js:62462 Uncaught (in promise) TypeError: Cannot read property 'zoomIn' of null
    at p.render (:3000/static/js/67.chunk.js:62462)
    at C.render (:3000/static/js/67.chunk.js:62269)
    at u (:3000/static/js/67.chunk.js:29590)
    at Object.merge (:3000/static/js/67.chunk.js:29623)
    at p._attach (:3000/static/js/67.chunk.js:62362)
    at p.<anonymous> (:3000/static/js/67.chunk.js:62357)
    at p.<anonymous> (:3000/static/js/67.chunk.js:15674)
    at c (:3000/static/js/67.chunk.js:15648)
    at i (:3000/static/js/67.chunk.js:15673)
    at j (:3000/static/js/67.chunk.js:15735)
    at p._postInitialize (:3000/static/js/67.chunk.js:62356)
    at :3000/static/js/67.chunk.js:62274
    at async Promise.all (index 1)
:3000/static/js/67.chunk.js:175600 [esri.widgets.Widget] widget-intl:locale-error esri.identity.IdentityForm s
console.<computed> @ :3000/static/js/67.chunk.js:175600
:3000/static/js/67.chunk.js:175600 [esri.widgets.Widget] widget-intl:locale-error esri.identity.IdentityModal s
console.<computed> @ :3000/static/js/67.chunk.js:175600
:3000/static/js/82.chunk.js:1462 Uncaught (in promise) TypeError: Cannot read property 'close' of undefined
    at p.render (:3000/static/js/82.chunk.js:1462)
    at C.render (:3000/static/js/67.chunk.js:62269)
    at u (:3000/static/js/67.chunk.js:29590)
    at Object.merge (:3000/static/js/67.chunk.js:29623)
    at p._attach (:3000/static/js/67.chunk.js:62362)
    at p.<anonymous> (:3000/static/js/67.chunk.js:62357)
    at p.<anonymous> (:3000/static/js/67.chunk.js:15674)
    at c (:3000/static/js/67.chunk.js:15648)
    at i (:3000/static/js/67.chunk.js:15673)
    at j (:3000/static/js/67.chunk.js:15735)
    at p._postInitialize (:3000/static/js/67.chunk.js:62356)
    at :3000/static/js/67.chunk.js:62274
    at async Promise.all (index 1)
    ```

**Comment by andygup** [comment]
Yes that is correct, using `basemap: "arcgis-topographic"` requires an API key. You can see the list of basemaps that require or don't require a key here: https://developers.arcgis.com/javascript/latest/api-reference/esri-Map.html.

```js
import config from '@arcgis/core/config.js';
config.apiKey = "YOUR-API-KEY";
```

**Comment by andygup** [comment]
@allidoisace The other errors you are seeing might be related to the missing API key. I recommend setting up the key first and trying again. Then let us know if you still see the errors or not.

**Comment by allidoisace** [comment]
So, I actually have solved a lot of my issues. I have 1 remaining issue that I have no idea how to solve. It involves a refresh, the application can't load the Widgets from esri. Should I close this and make a new issue?

**Comment by andygup** [comment]
Awesome. Yes, it's best to stick to one problem per github issue. General questions about widgets should be directed to GeoNET. Did you already post your question there? I see there's a new question about Widgets: https://community.esri.com/t5/arcgis-api-for-javascript/erros-occurred-while-loading-widgets/m-p/1024673#M71695.

**Comment by allidoisace** [comment]
Okay. Yes, that is also my question. I have no idea why this is an issue and I am unsure if it is just because I am using ESM.

**Comment by andygup** [comment]
Gotcha, no worries. I answered your question over in GeoNET. I'll go ahead close this issue.
