### ISSUE TITLE
4.18 @arcgis/core ES modules in Angular app: module related error when running Jest

### ISSUE THREAD

**Issue by bsanti** [Esri/jsapi-resources#263]
I wanted to start looking into bringing in the beta ES modules but Im getting the following error when running Jest: **"Cannot use import statement outside a module"**
I noticed package.json does not have a "main" property which might be the cause.   Since the sample app did not use Jest, I have attached a sample app to reproduce the issue.
[sample.zip](https://github.com/Esri/jsapi-resources/files/5891490/sample.zip)

I am reporting an issue with 

- [x ] TypeScript definitions
- [ ] another resource in this repository

**Comment by andygup** [comment]
Hi @bsanti, I don't have any experience with jest but I can take a look. Can you share your sample as a github repo?

**Comment by bsanti** [comment]
Thanks for looking into: https://github.com/bsanti/angularJestSample

**Comment by andygup** [comment]
I did get jest working with the JS API, I'll try to post a github example today.  I basically did two things:

1. I create a new file named `babel.config.js`. Then I added this to the file:
 
```js
module.exports = function (api) {
  api.cache(true);

  const presets = ['@babel/preset-env'];
  const plugins = ['@babel/transform-runtime'];

  return {
    presets,
    plugins,
  };
};
```
 
2. And, I modified `jest.config.js` to include `babel-jest`. This allowed jest to parse the JS API ES modules:
 
```js
 transform: {
   '^.+\\.(ts|html)$': 'ts-jest',
   '^.+\\.js$': 'babel-jest' 
 }, 
```

**Comment by andygup** [comment]
@bsanti here's a link to my prototype repo: https://github.com/andygup/angular-jsapi-jest. In the README I outlined the various modifications I made to a basic Angular CLI hello world map app.

![image](https://user-images.githubusercontent.com/510440/106950205-4f607000-66eb-11eb-865f-f2ad06c04c60.png)

**Comment by bsanti** [comment]
Thank you @andygup. I'll look into making the necessary changes.

**Comment by andygup** [comment]
Sounds good. Since there is a working sample now, I'll go ahead and close this issue. If any other problems come up feel free to post them.
