### ISSUE TITLE
Graphics not displayed until refreshed

### ISSUE THREAD

**Issue by gauravsamudra** [Esri/jsapi-resources#264]
I am reporting an issue with 

- [ ] TypeScript definitions
- [x] another resource in this repository

Hello, I am facing an issue with Graphics when using ES modules with angular. I am referring to the jsapi-angular-cli sample application in this repository. I've updated the code to display a Point using Graphics. See gist [here](https://gist.github.com/gauravsamudra/ce7bdf9e1729432a75df9031f22631d4).
When  I execute the application, or refresh page, the API does not display the point. But when I zoom in, it appears.
See the screen capture [here](https://gist.github.com/gauravsamudra/a042d34120b63103c3f3ed746fe88c57).
As you can see, when I refresh the page, the Point does not appear. After a few seconds, I zoom in on the map and it shows up.

I've ended up with workaround, where I programmatically zoom in after a short delay - but that seems to have led to a subsequent issue in which part of graphics are rendered but not all.

If this is not the right repository to log this issue, I would appreciate if someone points me to the right one.

Thank you.

**Comment by andygup** [comment]
@gauravsamudra thanks for reporting. This is a known issue and we hope to have it fixed in 4.19 (April).  I'll go ahead and close this out.

**Comment by gauravsamudra** [comment]
Thanks @andygup. Appreciate about the April timeline information. Helps plan things better.

I'm not sure if this helps, but I'd like to mention that, as a workaround, I switched over to esri-loader - and its version 3.0.0 has the same issue. I downgraded to 2.16.0 and it works well.

**Comment by andygup** [comment]
@gauravsamudra we believe we fixed this bug. Can you retest using `npm install @arcgis/core@next`? `/next` is a preview build for the 4.19 production release in April.
