### ISSUE TITLE
Using webpack plugin

### ISSUE THREAD

**Issue by phanivaranasi** [Esri/jsapi-resources#265]
![image](https://user-images.githubusercontent.com/6230353/106716391-64be9700-6624-11eb-85c1-8669e85e082d.png)

I'm using react + typescript + webpack .. using ArcGIS webpack plugin , I'm trying to render map
But, unable to load the modules error is coming, let me know how to fix this error.

My repo https://github.com/phanivaranasi/mancycle

**Comment by odoe** [comment]
It looks like you're using the `arcgis-js-api` amd package. You are using the `esri/` path in your project, but that doesn't exist anywhere. You can add an alias to your webpack config.

https://github.com/Esri/jsapi-resources/blob/master/4.x/webpack/demo/webpack.config.js#L77-L79

```js
  resolve: {
    ...
    alias: {
      "esri": path.resolve(__dirname, 'node_modules/arcgis-js-api/')
    }
  }
```

**Comment by andygup** [comment]
Closing this out for now. @phanivaranasi let us know if you have any more issues.
