### ISSUE TITLE
Only map zoom controls can be seen on FireFox browser print

### ISSUE THREAD

**Issue by bsanti** [Esri/jsapi-resources#266]
What I'm trying to do is print a page containing a header/footer and map.  I'm aware browser printing can be difficult to do consistently across browsers and sometimes one needs to adjust scale options prior to print.  The Print widget, as I understand, will not print out the header/footer sections so that is not an option.  The map shows up when printing with Chrome or Edge.

![FireFoxPrint](https://user-images.githubusercontent.com/78181602/106843437-a32b7480-666b-11eb-9861-9eb009e1ad50.PNG)
I am reporting an issue with 

- [ ] TypeScript definitions
- [X ] another resource in this repository

**Comment by bsanti** [comment]
Just some more info, I was using Firefox v85 and ArcGis for Javascript v4.18.  I also attached the single html file used to generate the previously attached screenshot.
[SampleArcGISPrint.zip](https://github.com/Esri/jsapi-resources/files/5926835/SampleArcGISPrint.zip)

**Comment by andygup** [comment]
Hi @bsanti which resource in this repository relates to your question? My laptop isn't able to scan zip files right now, do you have a github repo, codepen or stackblitz that reproduces the issue?

Also, I noticed you are using `file:///`. Have you tried serving your app on your local web server? We recommend using a local web server as a best practice.

**Comment by bsanti** [comment]
Hi @andygup, I selected 'another resource in the repository' since I didn't know exactly which resource could be causing the map not to print in Firefox.  I was able to reproduce using the [jsapi-angular-cli](https://github.com/Esri/jsapi-resources/tree/master/esm-samples/jsapi-angular-cli) sample but I don't believe it is isolated to the ESM resource.  You can also reproduce by attempting to print the [map ](https://developers.arcgis.com/javascript/latest/display-a-map/)found in the esri tutorial.

**Comment by andygup** [comment]
Thanks @bsanti. We are looking into this and will post back here with any findings.

**Comment by NoashX** [comment]
Hi @bsanti, it seems this is a long-standing issue between Firefox and WebGL. There are issues open for mozilla going back 7-8 years ago, so this is not a new issue.

https://bugzilla.mozilla.org/show_bug.cgi?id=833623

https://bugzilla.mozilla.org/show_bug.cgi?id=976173

You can see this if you go to a WebGL enabled site and try to print in Firefox and Chrome (no cube will appear in Firefox printout): https://get.webgl.org/

As a workaround until Mozilla can address that, I would suggest the takeScreenshot() method. We have a sample using it in a 3D SceneView, and there is a super handy blog about how to configure and extend it.

Take a screenshot of a SceneView
https://developers.arcgis.com/javascript/latest/sample-code/sceneview-screenshot/

Screenshots with the ArcGIS API for JavaScript & HTML2Canvas
https://community.esri.com/t5/arcgis-configurable-apps-blogs/screenshots-with-the-arcgis-api-for-javascript-html2canvas/ba-p/904367

Hope this helps!

**Comment by bsanti** [comment]
Thanks @NoashX for the explanation and the provided workarounds.

**Comment by NoashX** [comment]
Closing as resolved.
