### ISSUE TITLE
React & @arcgis/core bundling errors

### ISSUE THREAD

**Issue by snobrdinrtiste** [Esri/jsapi-resources#267]
![image](https://user-images.githubusercontent.com/1531380/106923241-b7e72700-66c2-11eb-8624-859ae2611064.png)

I am running into this type of error in my React app.  
Can anyone shed light on this?  I checked the JSON  in the public/assets/esri folder and all looks good.
Also, since we are copying the ESRI files to the public/assets folder, is there any way to use relative paths instead of using an absolute path?  (as show in the error log above)

**Comment by odoe** [comment]
Are you using routing in your application? Depending on how your application is deployed and needs to reference the assets, you can set this yourself with the `@arcgis/core/config`, `config.assetsPath` property as shown here.

https://github.com/Esri/jsapi-resources/tree/master/esm-samples#copy-assets

**Comment by snobrdinrtiste** [comment]
yes i'm using routing with React Router and have tried the config.assetsPath initially... i'll see if I change somethings around to make it work.   thank you.

**Comment by odoe** [comment]
You can try `config.assetsPath = /assets` and that will always pull from the root, if you kept the folder names the same.

**Comment by snobrdinrtiste** [comment]
hmm... tried setting the `config.assetsPath` with different paths and still getting the same error(s)

**Comment by snobrdinrtiste** [comment]
I'm trying to integrate it into an established Admin template but its not deployed and i'm debugging in VS Code.  I'll work more on this and see where I get to.  I'll post my findings if I make progress.
Thank you!

**Comment by snobrdinrtiste** [comment]
One thing I noticed is that the http request to the @arcgis/core json files all have a null header.  Shouldn't the headers be something like:  
`headers : { 
        'Content-Type': 'application/json',
        'Accept': 'application/json'
}`

**Comment by snobrdinrtiste** [comment]
hi @odoe 
I tested a new create-react-app with React Router using HashRouter and BrowserRouter and both instances worked so I don't think the error has anything to do with routing in React.
I did try a fresh Admin Template [()](https://coreui.io/react/) and am running into the same errors.

**Comment by snobrdinrtiste** [comment]
ok finally decided to build and look at the debug console... the error that came back was a 404 error
so I modified the config assetsPath to `config.assetsPath = "./assets"` and the build version works!
not sure why it doesn't work in the VS Code chrome debug mode
