### ISSUE TITLE
ES modules: how to import watchUtils and Button?

### ISSUE THREAD

**Issue by losciur** [Esri/jsapi-resources#269]
Hi,
when I used esri-loader, to import watchUtils and Button I wrote:
```
  loadModules([
      "dijit/form/Button",
      "esri/core/watchUtils",
    ], options)
      .then(([
        Button,
        watchUtils,
      ]) => {})
```

How can I do with ES modules?
Writing:

```
import Button from '@arcgis/dijit/form/Button';
import watchUtils from "@arcgis/core/watchUtils";
```
I cannot do it.

Thanks for hekp.

**Comment by losciur** [comment]
I solved for watchUtils:
`import * as watchUtils from '@arcgis/core/core/watchUtils.js';`

Nothing for Button

**Comment by andygup** [comment]
Glad you got it figured out for watchUtils, there's no default export on that module.

Nope, we don't have anything equivalent for button that's part of the JS API.

**Comment by losciur** [comment]
Ok, I think I solved both problems.
For watchUtils:
`import * as watchUtils from '@arcgis/core/core/watchUtils.js';`

For button the best solution is (this example put as icon the esri-icon-collection):
```
var element = document.createElement('div');
element.className = "esri-icon-collection esri-widget--button esri-widget esri-interactive";
element.addEventListener('click', function(evt){
  console.log("clicked"); 
})
view.ui.add(element, "top-right");
```
If you are using ionic, you can put a ionic icon removing 'esri-icon-collection ' and adding a innerHTML, like;
```
var element = document.createElement('div');
element.className = "esri-widget--button esri-widget esri-interactive";
element.innerHTML = '<ion-icon name="expand"></ion-icon>'
element.addEventListener('click', function(evt){
  console.log("clicked"); 
})
view.ui.add(element, "top-right");
```

**Comment by andygup** [comment]
Followup note - for those reading this that aren't using Ionic, or Vanilla JavaScript, you just need a slight modification of the `element.innerHTML` to make this work:

```js
        let element = document.createElement('div');
        element.className = "esri-widget--button esri-widget esri-interactive";
        element.innerHTML = '<span aria-hidden="true" class="esri-collapse__icon esri-icon-expand"></span>'
        element.addEventListener('click', (evt) => {
           console.log("clicked");
        });
        
        view.ui.add(element, "top-right");

```
