### ISSUE TITLE
To use the ES modules for esri JS Api 4.18 requires ncp copy of node_modules for BUILD and START. what and where do I need to copy assets for working in storybook.js?

### ISSUE THREAD

**Issue by MatthewJStarr** [Esri/jsapi-resources#273]
To use the ES modules for esri JS Api 4.18 requires ncp copy of node_modules for BUILD and START. what and where do I need to copy assets for working in storybook.js?

Copy assets

You will need to copy the API’s assets, which includes styles, images, fonts, and localization files, from the @arcgis/core/assets folder to your build folder. A simple way to accomplish this is to configure an NPM script that runs during your build process. For example, use npm to install ncp and configure a script in package.json to copy the folder. Here’s a React example:

// package.json

    {
        "script": {
            "start": "npm run copy && react-scripts start",
            "build": "npm run copy && react-scripts build",
            "copy": "ncp ./node_modules/@arcgis/core/assets ./public/assets"
        }
    }

https://developers.arcgis.com/javascript/latest/es-modules/

I am reporting an issue with 

- [ ] TypeScript definitions
- [ ] another resource in this repository

**Comment by odoe** [comment]
Haven't really used Storybook, but you could just have a copy script like in that sample and I think in Storybook it could be copied to `stories/assets`. The copy doesn't have to be done each time, only once in most apps to a directory that holds assets that the build tools will copy for you like. Usually that is in a folder called `public`, like with create-react-app. It looks like Storybook uses `stories/assets` for a similar purpose.

**Comment by MatthewJStarr** [comment]
Yes you are right  here is what I did.

{
    "scripts": {
       "start-storybook": "npm run copy && start-storybook -s ./public -p 9001"
       "copy": "ncp ./node_modules/@arcgis/core/assets ./public/assets"
    }
}
