### ISSUE TITLE
Widgets in ES Modules

### ISSUE THREAD

**Issue by sasteigerwald** [Esri/jsapi-resources#277]
I have some custom widgets I've developed in Typescript. I have the compiled JS file from a TSX file, etc. I'm attempting to bring that into my Angular project that uses ES Modules and have made various edits to my tsconfig file in attempts to support importing my widgets. But I always receive various failures on compile, the latest being "TypeError: Recenter is not a constructor". How does one use custom widgets in Angular with ES Modules?

I am reporting an issue with 

- [ ] TypeScript definitions
- [ ] another resource in this repository

**Comment by andygup** [comment]
We don't have an official sample or doc, yet(!), for a custom widget built with ESM. It's on our TODOs, so you are on the bleeding edge. 

There is a repo with a very basic Hello World widget prototype that you are welcome to look at for hints. It uses TypeScript and Webpack: https://github.com/kellyhutchins/arcgis-core-demo-app.

**Comment by sasteigerwald** [comment]
Awesome, thanks @andygup!

**Comment by sasteigerwald** [comment]
I now have the "Recenter" widget sample working in my ESM Angular app. Awesome! Thanks again for the help. The key things I was missing was;
- use the TSX file straight-up instead of the compiled JS
- The paths in the include in tsconfig were wrong in mine, using what Kelly had worked

**Comment by andygup** [comment]
Sweet! Glad you got it working. I'll go ahead and close the issue.
