### ISSUE TITLE
LayerList widget problem with Angular and 4.18

### ISSUE THREAD

**Issue by andras-kiss-gdihu** [Esri/jsapi-resources#279]
Hi!

I modified the esm-samples/jsapi-angular-cli/ sample app to include the LayerList widget from the API.
It throws a promise rejection error related to zone.js (which is included with Angular) and displays this message in the console:
"No layerview has been found for the layer"

It looks like when the LayerList tries to load the layer resources, it doesn't wait for the layer to load (the layer's loaded prop is false if you check the exception details).

The slightly modified code:

```
  initializeMap(): Promise<any> {
    const container = this.mapViewEl.nativeElement;

    const USALayer : MapImageLayer = new MapImageLayer({
      url:
        'http://sampleserver6.arcgisonline.com/arcgis/rest/services/USA/MapServer',
      title: 'US Sample Data',
    });

    // Configure the Map
    const mapProperties = {
      basemap: "streets",
      layers: [USALayer]
    };

    const map = new Map(mapProperties);

    const view = new MapView({
      container,
      map: map
    });

    view.whenLayerView(USALayer).then(layerView => {
      console.log(USALayer.loaded);
      var layerList = new LayerList({
        view: view,
        //listItemCreatedFunction: defineActions,
      });
      view.ui.add(layerList, 'top-right');
    });


    this.view = view;
    return this.view.when();
  }
```

What could I do about this?

Thanks,
Andras

I am reporting an issue with 

- [x] another resource in this repository

**Comment by andygup** [comment]
@andras-kiss-gdihu thanks for reporting, I was able to reproduce the problem. We'll take a look.

**Comment by andygup** [comment]
@andras-kiss-gdihu. These errors are a general issue. They aren't specific to Angular.  and shouldn't affect ArcGIS JS API functionality. I checked and the LayerList widget appears to be functioning correctly. 

I'll open a ArcGIS JS API issue to see if we can track this one down, and I'll update the Angular sample's README.

Closing as a known issue. Thanks again for reporting.

**Comment by andygup** [comment]
@andras-kiss-gdihu this issue has been addressed. Try running `npm i @arcgis/core@next` and retesting.

**Comment by andras-kiss-gdihu** [comment]
@andygup  Thanks, it works! 👍 
May I ask how often is the next version is updated on the CDN? Currently it's 20210311.

**Comment by andygup** [comment]
It's typically released daily up until about a week before we do a production release, which will be in early April for 4.19. It sounds like it installed correctly if you aren't seeing the error anymore.

Are you looking in `package.json`? This morning I'm seeing: `4.19.0-next.20210316` when I install it. And, here's the home page for that release: https://www.npmjs.com/package/@arcgis/core/v/4.19.0-next.20210316.

**Comment by andras-kiss-gdihu** [comment]
Yes, it installed correctly, I see the same version in package.json.
I was asking about the CDN version, when I reference the next version using a normal script element in a traditional AMD way:

`<script src="https://js.arcgis.com/next/"></script>`

This link loads a version dated a few days back:
buildDate="20210311"
Console displays this:
Using ArcGIS API for JavaScript 4.19-next [Date: 20210311, Revision: 683c2714]

So I guess this version is not updated daily.
https://github.com/Esri/feedback-js-api-next

**Comment by andygup** [comment]
Correct, updates to the CDN releases of "next" are not guaranteed to be daily. This is also described in the README: https://github.com/Esri/feedback-js-api-next#arcgis-api-for-javascript---next
