### ISSUE TITLE
esm modules angular cli -  where to add additional code for layers and other map functions

### ISSUE THREAD

**Issue by pvitt** [Esri/jsapi-resources#281]
Hi - looking at the angular esm example, If I wanted to add code to add layers, graphics, widgets etc.., should the code be added after the zone.run return as shown below, or up in the initializeMap method?

Thanks

Pete

 this.zone.runOutsideAngular(() => {
      // Initialize MapView and return an instance of MapView
      this.initializeMap().then(() => {
        // The map has been initialized
        this.zone.run(() => {
          console.log('mapView ready: ');
//ADD ADDITIONAL CODE HERE
        });
      });

    });

**Comment by andygup** [comment]
@pvitt good question, and it's really all about how you want to handle Angular component change detection and that's an Angular design decision you'll need to make. It's not an ArcGIS JS API issue unless you have a specific performance problem. Many developers just let Angular automatically handle change detection, and others want fine grained control to get as close to 60fps (frames per second) performance as possible. 

Our example shows a very basic implementation for fine-grained control. Whether or not you need to use `runOutsideAngular()`, and even how you use it depends on your use cases, and is verified through performance testing. 

If you aren't familiar with `zone.runOutsideAngular( )` here's a good introductory blog post: https://blog.thoughtram.io/angular/2017/02/21/using-zones-in-angular-for-better-performance.html.

**Comment by andygup** [comment]
@pvitt thanks again for the question on this. To help simplify and reduce confusion, at the 4.19 release we removed `zone.runOutsideAngular()` from the Angular sample: https://github.com/Esri/jsapi-resources/blob/master/esm-samples/jsapi-angular-cli/src/app/app.component.ts#L67. This should make it much easier to work with as a getting started app.

I'll go ahead and close this issue out.
