### ISSUE TITLE
Mistyping of TrimExtendParametersProperties' extendHow Property

### ISSUE THREAD

**Issue by sgreylyn** [Esri/jsapi-resources#29]
The property [extendHow](https://github.com/Esri/jsapi-resources/blob/master/4.x/typescript/arcgis-js-api.d.ts#L4312) of TrimExtendParametersProperties is typed as 'void', when the [docs](https://developers.arcgis.com/javascript/latest/api-reference/esri-tasks-support-TrimExtendParameters.html#extendHow) strongly imply that it should be typed as 'string'.

**Comment by dasa** [comment]
Fixed at: https://github.com/Esri/jsapi-resources/blob/master/4.x/typescript/arcgis-js-api.d.ts#L4407
