### ISSUE TITLE
How can I import a node library into the typescript project?

### ISSUE THREAD

**Issue by ionara** [Esri/jsapi-resources#291]
How can I import a node library into the typescript project? Thanks

jsapi-resources/4.x/typescript/

**Comment by andygup** [comment]
Hi @ionara, do you have an example of what you are trying to do? Here's an article that might help you out: https://www.typescriptlang.org/docs/handbook/module-resolution.html.

**Comment by andygup** [comment]
It looks like this issue can be closed via https://community.esri.com/t5/arcgis-api-for-javascript/import-and-use-a-node-package/m-p/1054410/highlight/true#M72894. Closing.
