### ISSUE TITLE
When I run it I dont see the map 

### ISSUE THREAD

**Issue by ionara** [Esri/jsapi-resources#292]
When I run  the webpack plugin sample, there is no map. just an interface with:

Winter
Spring
Summer
Fall
Flash Floods by Season
Flash Flood Warnings (2002 - 2012)

**Comment by andygup** [comment]
Hi @ionara  try updating `webpack` and `webpack-cli` then trying again. 

Note that we also have an ES modules sample that you can try: https://github.com/Esri/jsapi-resources/tree/master/esm-samples/webpack.

**Comment by ionara** [comment]
I updated them and I got this error:

Using arcgis-js-api version: 4.18.1
[webpack-cli] TypeError: cli.isValidationError is not a function
    at Command.<anonymous> (E:\Projects\WebpackEsri\node_modules\@webpack-cli\serve\lib\index.js:97:25)
    at async Promise.all (index 1)
    at async Command.<anonymous> (E:\Projects\WebpackEsri\node_modules\webpack-cli\lib\webpack-cli.js:708:13)
PS E:\Projects\WebpackEsri> 

Here is the package.json

{
  "name": "demo",
  "version": "0.0.1",
  "devDependencies": {
    "@arcgis/webpack-plugin": "~4.18.0",
    "@types/sinon": "^9.0.7",
    "@typescript-eslint/eslint-plugin": "^4.9.0",
    "@typescript-eslint/parser": "^4.9.0",
    "clean-webpack-plugin": "~3.0.0",
    "copy-webpack-plugin": "~6.3.2",
    "css-loader": "~5.0.1",
    "eslint": "^7.14.0",
    "eslint-config-prettier": "^6.15.0",
    "eslint-plugin-prettier": "^3.1.4",
    "html-loader": "~1.3.2",
    "html-webpack-inline-source-plugin": "~0.0.10",
    "html-webpack-plugin": "~4.5.0",
    "husky": "~4.3.0",
    "lint-staged": "~10.5.2",
    "mini-css-extract-plugin": "~1.3.1",
    "prettier": "^2.2.1",
    "resize-observer-polyfill": "^1.5.1",
    "resolve-url-loader": "~3.1.2",
    "style-loader": "~2.0.0",
    "terser-webpack-plugin": "~5.0.3",
    "ts-loader": "~8.0.11",
    "tslib": "~2.0.3",
    "typescript": "~4.1.2",
    "webpack": "^5.9.0",
    "webpack-cli": "^4.3.1",
    "webpack-dev-server": "~3.11.0"
  },
  "license": "Apache-2.0",
  "scripts": {
    "precommit": "lint-staged",
    "start": "webpack serve --mode development",
    "build": "webpack --mode production",
    "prettier": "prettier --write \"src/**/*.ts?(x)\"",
    "lint": "eslint --fix \"src/**/*.ts?(x)\""
  },
  "lint-staged": {
    "*.{ts,tsx}": [
      "prettier --write",
      "eslint --fix"
    ]
  },
  "eslintConfig": {
    "parser": "@typescript-eslint/parser",
    "plugins": [
      "@typescript-eslint"
    ],
    "extends": [
      "eslint:recommended",
      "plugin:@typescript-eslint/eslint-recommended",
      "plugin:@typescript-eslint/recommended",
      "prettier/@typescript-eslint",
      "plugin:prettier/recommended"
    ]
  },
  "prettier": {
    "singleQuote": true,
    "tabWidth": 4
  },
  "arcgis": {
    "type": "jsapi"
  },
  "dependencies": {
    "arcgis-js-api": "~4.18.0"
  }
}

**Comment by andygup** [comment]
Awesome, I'll close this out. `TypeError: cli.isValidationError is not a function` is a known webpack-cli problem that was fixed at `webpack-cli@4.5.0`. We'll update the sample.
