### ISSUE TITLE
Bower Sample Application for 4.0 does not initially build

### ISSUE THREAD

**Issue by Robert-W** [Esri/jsapi-resources#30]
I was testing out the bower sample application under the folder `jsapi-resources/4.x/bower/dojo` and after I cloned the code and tried running the commands from the README, the build failed and the app would not load.  It ended up being a really easy fix.

When I ran `npm install` which triggers `bower install`, it installed all the bower components into a `bower_components` folder because there is no `.bowerrc` present.  The build commands look for the bower components in the `src` folder.  All I had to do was simply copy the contents from the `bower_components` folder into the `src` directory and then the app and build worked fine.  I have this working locally but just wanted to let you guys know incase you want to add a `.bowerrc` or a note in the README to let people know they need to move the bower installed components into the `src` folder.

**Comment by Robert-W** [comment]
Hmm, nevermind.  Just saw it in the repo. Not sure why it wasn't in my local folder after a clone but pretty sure this is a issue with something on my machine.

**Comment by odoe** [comment]
Is it possible you copy/pasted the files from somewhere? I was just about to say it's in there, and I double-checked the downloaded zipfile.

Let me know if it's some other weird issue.

Thanks!

**Comment by Robert-W** [comment]
Yup, grabbed the contents of the folder, realized a few minutes after I did it they were there and I left the hidden files behind(rookie move).  I was trying to get this closed before you guys spent any time on it.  Thanks for the example.
