### ISSUE TITLE
issue: jsapi-resources/esm-samples/jsapi-angular-cli/

### ISSUE THREAD

**Issue by forrestlin100** [Esri/jsapi-resources#305]
Try to compile project jsapi-angular-cli
> npm start

Got Error:
The Angular Compiler requires TypeScript >=4.2.3 and <4.3.0 but 4.3.2 was found instead.

**Comment by andygup** [comment]
@forrestlin100 you'll need to downgrade your typescript, for example:

```
npm uninstall typescript
npm i --save-dev typescript@4.2.3
```

**Comment by forrestlin100** [comment]
Got error when do "npm uninstall typescript"

PS C:\Projects\jsapi-angular-cli> npm uninstall typescript
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: ng-cli@0.0.0
npm ERR! Found: jasmine-core@3.6.0
npm ERR! node_modules/jasmine-core
npm ERR!   dev jasmine-core@"~3.6.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer jasmine-core@">=3.7.1" from karma-jasmine-html-reporter@1.6.0
npm ERR! node_modules/karma-jasmine-html-reporter
npm ERR!   dev karma-jasmine-html-reporter@"^1.5.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\parefl1\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\parefl1\AppData\Local\npm-cache\_logs\2021-05-27T19_53_13_335Z-debug.log

**Comment by andygup** [comment]
Hi @forrestlin100 the most likely cause of the dependency tree errors are `npm 7` bugs. It's not an issue with the ArcGIS JS API or the sample code. Note that this repo was built for `npm 6 (latest)`. The Angular CLI team recently considered [not allowing `npm 7` support](https://github.com/angular/angular-cli/issues/19957#issuecomment-773569798).  

Try using `npm install --legacy-peer-deps`, reference: 
- https://github.com/angular/angular-cli/issues/19957#issuecomment-774400406
- https://stackoverflow.com/questions/64573177/unable-to-resolve-dependency-tree-error-when-installing-npm-packages

As a last resort, you could downgrade to `npm 6 (latest)`.

**Comment by forrestlin100** [comment]
It is compiled successfully with npm 6.14.13.

Is it working with @ng-bootstrap/ng-bootstrap?

**Comment by andygup** [comment]
Good deal! it sounds like you can close this issue.

> Is this version (Angular 12) working with @ng-bootstrap/ng-bootstrap?

We don't specifically test with those widgets. We try to be platform agnostic.
