### ISSUE TITLE
4.19.3 @arcgis/core ES modules:  popupTemplate Not effective

### ISSUE THREAD

**Issue by a1067111756** [Esri/jsapi-resources#306]
I am reporting an issue with 

- [ ] TypeScript definitions
- [ ] another resource in this repository

`
    esriConfig.apiKey = 'xxxxxxxxxxxxxxxxxx'

    const template = {
      title: "Earthquake Info",
      content: "Magnitude {mag} {type} hit {place} on {time}",
      fieldInfos: [
        {
          fieldName: 'time',
          format: {
            dateFormat: 'short-date-short-time'
          }
        }
      ]
    };
    const vectorTileLayer = new VectorTileLayer({
      portalItem: {
        id: "6976148c11bd497d8624206f9ee03e30" // Forest and Parks Canvas
      },
      opacity: .75,
      popupTemplate: template,
    });

    const imageTileLayer = new TileLayer({
      portalItem: {
        id: "1b243539f4514b6ba35e7d995890db1d" // World Hillshade
      }
    });

    const basemap = new Basemap({
      baseLayers: [
        imageTileLayer,
        vectorTileLayer
      ]
    });

    const map = new Map({
      basemap: basemap
    });

    const view = new MapView({
      map: map,
      center: [-100,40], // Longitude, latitude
      zoom: 3, // Zoom level
      container: "arcMap" // Div element
    });  
`

description: 4.19.3 @arcgis/core ES modules:  popupTemplate Not effective, but the method introduced using <script> is effective

**Comment by andygup** [comment]
Hi @a1067111756 can you provide a codepen or github repo that reproduces the issue?

**Comment by a1067111756** [comment]
I have solved this problem because I added the layer to the basemap and the popupTemplate does not take effect

**Comment by andygup** [comment]
Glad you were able to solve it! I'll go ahead and close this issue.
