### ISSUE TITLE
@arcgis/core with Angular 12 - "Fatal" error at runtime with prod build using a specific web map and legend configuration

### ISSUE THREAD

**Issue by vitale232** [Esri/jsapi-resources#309]
I am reporting an issue with 

- [ ] TypeScript definitions
- [x ] another resource in this repository

I kind of stumbled into this one... There appears to be an Angular 12 `--prod` build issue when using a particular `WebMap` ID and `Legend` configuration.

## Replication 

I've replicated the issue by making a fork of this repo and updating the sample [`app.component.ts`](https://github.com/vitale232/jsapi-resources/blob/master/esm-samples/jsapi-angular-cli/src/app/app.component.ts) from the ESM build Angular demo.

You can see that I've swapped in a different WebMap id from the JS sample servers. Additionally, there is a new `addLegend` method, which adds a legend widget with the `style` property configured to render a stacked card style legend.

Run `ng build` on the forked repo. I've been using two different NPM local HTTP servers to test the prod build, and I get the same error using both servers:

Chrome
![image](https://user-images.githubusercontent.com/8504254/121009341-0afce380-c762-11eb-9d3e-37eab1549935.png)

Firefox
![image](https://user-images.githubusercontent.com/8504254/121009417-25cf5800-c762-11eb-9613-b6edabdf0a3c.png)

This error is "fatal" in the sense that it breaks many of the widgets on the map. The expand widget of the bookmarks will not collapse, the legend obviously doesn't render, add bookmarks doesn't work, popups aren't popping, etc... The API only throws this single error on initialization.

FWIW, removing the style property on the legend fixes the build. Using the original WebMapID with the "stacked card" legend also works okay.

Thanks.

**Comment by andygup** [comment]
Thanks @vitale232 we'll take a look.

**Comment by andygup** [comment]
@vitale232 Thanks for reporting this, I was able to reproduce the bug using `4.19.3` and `4.20-next`. I've gone ahead and opened an API issue.

**Comment by vitale232** [comment]
Looks good to me... Thanks!
