### ISSUE TITLE
Typo in ClosestFacilityParametersProperties Interface for 4.x

### ISSUE THREAD

**Issue by sgreylyn** [Esri/jsapi-resources#31]
The aforementioned interface [lists](https://github.com/Esri/jsapi-resources/blob/master/4.x/typescript/arcgis-js-api.d.ts#L3327) 'polylgon' as a property; this should be 'polygon'.

**Comment by dasa** [comment]
Thanks for reporting this. It's now fixed at: https://github.com/Esri/jsapi-resources/blob/master/4.x/typescript/arcgis-js-api.d.ts#L3527
