### ISSUE TITLE
@arcgis/core 4.19.3 - workers

### ISSUE THREAD

**Issue by qQsss777** [Esri/jsapi-resources#310]
I am reporting an issue with 

- [ ] TypeScript definitions
- [x] another resource in this repository

I have started a new project with @arcgis/core 4.19.3. I used arcgis-cli to create the project. I modified wbepack configuration to copy some static file with CopyPlugin. I installed React too. My problem is that I want to use worker from the ArcGIS API Javascript.  But i get an error in my console : 

![image](https://user-images.githubusercontent.com/37547382/121135150-84650680-c834-11eb-8664-f6a601b2d03c.png)

Here an exemple of my code : 

```import * as workers from '@arcgis/core/core/workers';

export const startWorker = () => {
  const workerpath = 'http://fqdn/calc.js';
  workers.open(workerpath).then((connection) => {
    // do something with connection
  });
};
```

with the following calc.js file : 

```define(["esri/core/promiseUtils"], function(promiseUtils) {

  // when loaded, the workers framework will create new `Calculator`
  let Calculator = function Calculator() {};

  // any method on "Calculator" module can be invoked
  // from the main thread
  Calculator.prototype.max = function(data) {
    return Math.max.apply(null, data.numbers)
  }

  return Calculator;
});
```

Thanks

**Comment by andygup** [comment]
Hi @qQsss777 sorry for the delay. We are looking into this issue.

**Comment by andygup** [comment]
@qQsss777 we now have a new sample that demonstrates how to use workers with @arcgis/core: https://github.com/Esri/jsapi-resources/tree/master/esm-samples/jsapi-custom-workers.

**Comment by qQsss777** [comment]
Thanks you @andygup !

**Comment by andygup** [comment]
Glad we could help, I'll close this out.
