### ISSUE TITLE
Need package.json file update

### ISSUE THREAD

**Issue by meghan2733** [Esri/jsapi-resources#311]
I forked angular project off of elm-samples/jsapi-angular-cli

Needed to update package.json file with packages as

"jasmine-core": "3.7.1" &

"karma-jasmine-html-reporter": "1.6.0"

StackOverflow link for more info

https://stackoverflow.com/questions/67433893/unable-to-resolve-dependency-tree-error-for-creating-new-angular-project

Hope this helps

Meghan Kulkarni

I am reporting an issue with 

- [ ] TypeScript definitions
- [ ] another resource in this repository

**Comment by andygup** [comment]
Hi @meghan2733 thanks for reporting. Any chance you are running Node v7? For reference see this note: https://github.com/Esri/jsapi-resources/issues/305#issuecomment-849921881

**Comment by meghan2733** [comment]
Thank you for reaching out Andy. I'm using latest LTS version of node (v14.17.0).

My Best,
Meghan Kulkarni

**Comment by andygup** [comment]
@meghan2733 oh sorry, I meant NPM 7. If you are running NPM 7 you may need to downgrade, see the link above. I changed the message directly on the forum, but the email messages don't reflect those updates.

**Comment by meghan2733** [comment]
I'm using node 7 (7.16.0). I believe it was default installation from dmg package I downloaded. I'll try to downgrade and see if it works.

Thanks again.

Meghan Kulkarni
