### ISSUE TITLE
how can i integrate umijs/antd to my map built with es modules

### ISSUE THREAD

**Issue by songfaqi** [Esri/jsapi-resources#319]
how can I integrate umijs/antd to my map built with es modules

**Comment by songfaqi** [comment]
Failed to compile
1.Errors, such as
Module not found: Error: Can't resolve 'C:/simplegis/jyjjport/node_modules/@umijs/babel-preset-umi/node_modules/@babel/runtime/helpers/esm/objectSpread2' in 'C:\simplegis\jyjjport\node_modules\@arcgis\core'
Did you mean 'objectSpread2.js'?
BREAKING CHANGE: The request 'C:/simplegis/jyjjport/node_modules/@umijs/babel-preset-umi/node_modules/@babel/runtime/helpers/esm/objectSpread2' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '*.mjs' file or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
2.Compile info
[BABEL] Note: The code generator has deoptimised the styling of C:\simplegis\jyjjport\node_modules\@esri\calcite-components\dist\custom-elements\index.mjs as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of C:\simplegis\jyjjport\node_modules\@arcgis\core\chunks\geometryEngineBase.js as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of C:\simplegis\jyjjport\node_modules\@arcgis\core\chunks\index.js as it exceeds the max of 500KB.
 ERROR  Failed to compile with 5000 errors (refer above)

**Comment by andygup** [comment]
Hi @songfaqi My suggestion is to tackle those errors one at a time. The errors seems to be configuration issues, for example:
* `Module not found: ` this looks like a babel configuration issue or a bug in babel
* `BREAKING CHANGE:` this looks like a possible webpack configuration issue, most likely need to specify a `module.rules.test`  object, for example:
```js
  module: {
    rules: [
           {
              test: /\.m?js/,
              resolve: {
                  fullySpecified: false
              }
            },
```

* Babel calcite-component deoptimization - that's just a warning as far as I'm aware. Check the docs for babel `compact` https://babeljs.io/docs/en/options#compact.
* `geometryEngineBase.js` size - same check the babel doc for `compact`
* `@arcgis\core\chunks\index.js` size - same, check the babel for `compact`

@odoe do you have any additional thoughts?

**Comment by dasa** [comment]
I'd also suggest not processing the modules with Babel unless you have to.

**Comment by odoe** [comment]
@dasa suggestion best, something like the object spread error might be fixable via browserlist using latest configuration.

**Comment by andygup** [comment]
Closing.
