### ISSUE TITLE
Using requirejs with arcgis js api (with CDN urls) 

### ISSUE THREAD

**Issue by Vikash2402** [Esri/jsapi-resources#32]
Well, 
Can we use arcgis js api with requirejs using cdn urls?

However its working fine with non amd or older versions of arcgis js api.

Similar issue:-
https://github.com/odoe/iLikeItHere/issues/1

Thanks,

**Comment by odoe** [comment]
This works by setting the `path` property for RequireJS config.
```html
    <script>
      window.require ={
        deps: ['app/main'],
        paths: {
          'esri': 'https://js.arcgis.com/4.0/esri',
          'dojo': 'https://js.arcgis.com/4.0/dojo',
          'dojox': 'https://js.arcgis.com/4.0/dojox',
          'dijit': 'https://js.arcgis.com/4.0/dijit'
        }
      };
    </script>
    <script src="requirejs/require.js"></script>
```

Note though that this will be slow as you will download individual modules instead of built files for the API.

**Comment by dasa** [comment]
The js.arcgis.com CDN now supports HTTP/2 as well.

**Comment by r-pankevicius** [comment]
RequireJS config works for 4.0, but doesn't for 4.12.

Repo is https://github.com/r-pankevicius/arcgis-js-api-with-requirejs

Folder 4.0 refers to v 4.0 that works according to @odoe tips for requirejs config.

Folder 4.12 has the same stuff, but refers v 4.12. I get errors like:
Error: Script error for "@dojo/framework/shim/Promise", needed by: esri/views/MapView

I suppose that there were some changes in dojo done, what is that "@dojo" namespace?...

**Comment by stephansamuel** [comment]
@r-pankevicius this worked for me with v4.24, but you must change the `/4.0/` in the `paths` object in the script from @odoe to match the version. For example, use `'https://js.arcgis.com/4.24/esri'`.
