### ISSUE TITLE
Possible Typing issue

### ISSUE THREAD

**Issue by devilsgeographer** [Esri/jsapi-resources#321]
I am reporting an issue with 

- [x] TypeScript definitions

Using this link:

https://developers.arcgis.com/javascript/latest/api-reference/esri-views-2d-layers-BaseLayerViewGL2D.html

There is example code starting with let CustomLayerView2D = BaseLayerViewGL2D.createSubclass({

createSubclass seems to be found in many custom layer examples across the API. 

In our angular app using ESM modules @arcgis/core 4.19.3

import BaseLayerViewGL2D from '@arcgis/core/views/2d/layers/BaseLayerViewGL2D';

We receive an error when trying to .createSubclass:

![image](https://user-images.githubusercontent.com/17552717/126550745-747c8790-6294-4ef0-97ac-3867671ea135.png)

When I open @arcgis\core\interfaces.d.ts   I don't see any reference to createSubclass for any interface.  

Can someone please help me understand why .createSubClass cannot be used here?    It seems to work in AMD modules based on the codepen examples:  
![image](https://user-images.githubusercontent.com/17552717/126551116-96a2236d-32a0-41e7-a7b6-30fa734b111d.png)

Thank you.

**Comment by andygup** [comment]
Thanks @devilsgeographer, we have an open issue to update the SDK documentation for base layers. 

For more info see issue https://github.com/Esri/jsapi-resources/issues/317 and also checkout this [comment](https://github.com/Esri/jsapi-resources/issues/317#issuecomment-867815092) on the differences between extending classes in JavaScript versus TypeScript.

**Comment by andygup** [comment]
@devilsgeographer I'll go ahead and close this issue as a duplicate.
