### ISSUE TITLE
ESM - Rollup - Livereload reloads before build is complete

### ISSUE THREAD

**Issue by gavinr** [Esri/jsapi-resources#325]
I am reporting an issue with 

- [ ] TypeScript definitions
- [x] another resource in this repository

When making a code change in the `esm-samples/rollup` sample, the livereload functionality reloads the page before the build is complete. This means that you don't see your results.

## Replicate

1. Open up the `esm-samples/rollup` sample
2. Run `npm run watch`
3. Open the browser to the url that it's serving at
4. Make a change to `src/main.js` - notice the browser reloads immediately instead of waiting until rollup creates the new build. Your changes are not visible in the browser until another manual refresh.

## Solution
I think this line should be changed back to `watch: "public/main.js"`:
https://github.com/Esri/jsapi-resources/commit/fee9972adf2f79da407520297d6e635a955a7be1#diff-a986b29e061aacf63dfdf0a257f1ed01cf388a5ded3827a3d2c99e630a574898L20

**Comment by andygup** [comment]
Thanks @gavinr, I was able to repro. Here's the PR: https://github.com/Esri/jsapi-resources/pull/326

**Comment by andygup** [comment]
Closing via PR https://github.com/Esri/jsapi-resources/pull/326

**Comment by gavinr** [comment]
Thanks!
