### ISSUE TITLE
ESM - Rollup - Speed

### ISSUE THREAD

**Issue by gavinr** [Esri/jsapi-resources#327]
When running the ESM Rollup example, the speed of the build is slow. For me on my laptop (which I think is an "average" developer laptop - see system info below):

- the initial start time for `npm run watch` is **~32 seconds**
- subsequent builds when a file is changed takes **~14 seconds**
![image](https://user-images.githubusercontent.com/209355/129737388-e70a39f2-c768-404f-8a73-db63fc24cf03.png)

Ideally the second number - the time it takes to build on file change, would be pretty quick (less than a few seconds) to allow for a good development workflow. Is there any way to speed this up? How fast does this run for others? Thanks!

## Environment

- npm v6.14.14
- node v14.17.1
- OS: Windows 10 v1909
- Processor: Intel core i7-8850H @ 2.60 GHz
- Memory: 16 GB

**Comment by andygup** [comment]
Is there a particular reason you chose rollup? Rollup always does a production build, in comparison there are workarounds that acknowledge the lack of HMR, for example: https://github.com/PepsRyuu/nollup

**Comment by dasa** [comment]
You can add `treeshake: false` to the config. This reduced the build times for me from times smiliar to yours, to ~20s for the initial build, to ~10s for the rebuild.

**Comment by gavinr** [comment]
Dasa and Andy, thank you very much for the help. 

> You can add `treeshake: false` to the config

That does indeed reduce the times for me. Thank you for this suggestion. It's a lot better but would still love to find other optimizations if possible to get the rebuild time down to a few seconds, if possible.

![image](https://user-images.githubusercontent.com/209355/129903646-9387b0a3-e153-4d13-8ff8-e1e46d52dee3.png)


> Is there a particular reason you chose rollup

I'm trying to use [Svelte](https://svelte.dev/) with the ArcGIS API for JavaScript. Svelte uses rollup for it build system. 

That being said, the new [SvelteKit](https://kit.svelte.dev/) uses Vite, which addresses the "rollup always does a production build" issue - so maybe I'll  try using SvelteKit (Vite) as a workaround. 

> workarounds .... for example nollup

I have never used nollup - thanks for the suggestion. If Rollup is not a valid use case for developers to use with the ArcGIS API for JavaScript due to the development build times, should we note that somewhere in the Rollup sample readme? ("Rollup certainly works fine for production builds, but for active development, Rollup with the ArcGIS API for JavaScript may be too slow. We recommend modern developer tooling helpers like Nollup or Vite")

**Comment by odoe** [comment]
vite 4 life

**Comment by andygup** [comment]
Hi @gavinr, Rollup.js does a decent job at what it was designed to do. It has been around a while (~2017) and its pluses and minuses are well documented and not unique to the ArcGIS JS API.

**Comment by andygup** [comment]
@gavinr I've gone ahead and updated the rollup sample's dev config to disable treeshaking in this PR: https://github.com/Esri/jsapi-resources/pull/328. Thanks for the suggestions and input!

**Comment by gavinr** [comment]
Thanks all! I'll close this as resolved:

1. Tree-shaking setting (#328) helps a lot
2. Using rollup only for production build and other options (vite?, nollup?) for development might be valid workarounds for certain situations.
3. Continued investigation into how to speed up the rollup build when using the ArcGIS API for JavaScript would still be appreciated though 😊
