### ISSUE TITLE
[arcgis-js-api.d.ts] PrintTask oncomplete event handler type def is different from what happens at runtime

### ISSUE THREAD

**Issue by vknez** [Esri/jsapi-resources#33]
I am using PrintTask from ArcGIS API for JavaScript 3.17. When the PrintTask completes, the argument passed to the event handler is different from what the type definition says:

**Current type definition:**
```typescript
on(type: "complete", listener: (event: { url: string; target: PrintTask }) => void): esri.Handle;
```
The current definition is correct as per ESRI official documentation: https://developers.arcgis.com/javascript/3/jsapi/printtask-amd.html#event-complete

**However, at runtime:**
```typescript
on(type: "complete", listener: (event: { result: { url: string; }; target: PrintTask }) => void): esri.Handle;
```

At runtime the url is wrapped into the `result` property of the callback argument.

Pull request will follow shortly...

Thanks for the definitions!

**Comment by dasa** [comment]
Thanks for reporting this. It's now fixed at 64abeb4df452a0ac712487f6133211b9a7bfe083
