### ISSUE TITLE
How come Development on TypeScript JSAPI keeps connecting to ESRI RemoteClient?

### ISSUE THREAD

**Issue by mannok** [Esri/jsapi-resources#330]
I am reporting an issue with 

- [v] TypeScript definitions
- [v] another resource in this repository

-------------

I am developing an online map with ArcGIS JSAPI TypeScript build. I used to keep the user from connecting outside to Internet. However, I found that when I build the website now (Webpack 4), my user keeps connecting to remote resource provided by ESRI.

Some remote clients and resources are stated below for your reference:
https://js.arcgis.com/4.19/@arcgis/core/assets/esri/t9n/common_en.json
https://js.arcgis.com/4.19/@arcgis/core/assets/esri/widgets/ScaleBar/t9n/ScaleBar_en.json
https://js.arcgis.com/4.19/@arcgis/core/assets/esri/core/workers/RemoteClient.js
https://js.arcgis.com/4.19/@arcgis/core/assets/esri/core/workers/chunks/ba193c302b87795eacb8.js
https://js.arcgis.com/4.19/@arcgis/core/assets/esri/core/workers/chunks/ba193c302b87795eacb8.js

Our user do not have Internet connection. Therefore, I must fix this issue, may I know how to get rid of it? Thanks in advance.

**Comment by andygup** [comment]
Closing.
