### ISSUE TITLE
Building Esri workers as esm module

### ISSUE THREAD

**Issue by lor11212** [Esri/jsapi-resources#331]
I am reporting an issue with 

- [ ] TypeScript definitions
- [x] another resource in this repository

Version: "@arcgis/core": "^4.20.2"

Hi there,
I have a question regarding the Esri workers and how to build them. I successfully built the workers as a `SystemJS` module using this example: https://github.com/Esri/jsapi-resources/tree/master/esm-samples/jsapi-custom-workers.

However, it would be better in Urban to build the worker as an `esm` module. From the documentation, it does not seem to be supported out of the box, but do you know if this is something that could be possible? And if so, what would be the loader url to set for `esriConfig.workers.loaderUrl` ?

Thanks and best,
Loris

**Comment by andygup** [comment]
Closing. @lor11212 if you have follow-up questions let us know?
