### ISSUE TITLE
VueJS 2.0 not support @arcgis/core?

### ISSUE THREAD

**Issue by kkbule** [Esri/jsapi-resources#332]
I am reporting an issue with :
I refer to an example of the official website, which works perfectly on the vue3.0 project using @ ArcGIS / core. But in vue2.0, it will report errors. Is there an example of vue2.0 for my reference???

![image](https://user-images.githubusercontent.com/37773741/131061294-41ed8cd9-618c-407b-a64c-5f70ec06dcb4.png)

- [ ] TypeScript definitions
- [ ] another resource in this repository

**Comment by andygup** [comment]
I'll go ahead and close this out. @kkbule if you have additional questions feel free to post back on the issue.
