### ISSUE TITLE
Update issue template

### ISSUE THREAD

**Issue by andygup** [Esri/jsapi-resources#333]
Update issue template to new template workflow. Consider doing something similar to what we did with the `next` repo: https://github.com/Esri/feedback-js-api-next/tree/master/.github/ISSUE_TEMPLATE.

**Comment by benelan** [comment]
If we are updating the issue templates we might as well use the newish [YAML form templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms). We [use them in CC](https://github.com/Esri/calcite-components/tree/master/.github/ISSUE_TEMPLATE). This is [what they look like](https://github.com/Esri/calcite-components/issues/new?assignees=&labels=bug%2C0+-+new%2Cneeds+triage&template=bug.yml).

**Comment by andygup** [comment]
Closing as completed. Thanks for the recommendations @benelan!
