### ISSUE TITLE
Bug: Memory Issues when using arcgis core (VueJS app) and importing modules individually

### ISSUE THREAD

**Issue by ornerymoose** [Esri/jsapi-resources#343]
**Describe the bug**
Putting arcgiscore in package.json is one thing, but when you start doing multiple imports such as:

`import Graphic from "@arcgis/core/Graphic";
import FeatureLayer from "@arcgis/core/layers/FeatureLayer";
import MapView from "@arcgis/core/views/MapView";
import Map from "@arcgis/core/Map";`

the JS loaded in the browser takes about 3 seconds and 6-7MB. Not the case when using esri-loader (given components setup I'd like to avoid using esri-loader at this stage in the application). Huge performance issue and Chrome has crashed a few times. 

![Screen Shot 2021-10-10 at 11 50 01 PM](https://user-images.githubusercontent.com/1296966/136739461-2de75455-82a5-413b-8927-0274680c121b.png)

Referenced here earlier this year:

- https://community.esri.com/t5/arcgis-api-for-javascript-questions/arcgis-core-webpack-build-running-out-of-memory/td-p/1045202

**Expected behavior**
- I should be able to import modules individually and not see a drastic decrease in performance. 

**Browser (check https://whatismybrowser.com/)** 
 - Browser: Version 94.0.4606.71 (Official Build) (x86_64)
 
**Operating System (check https://whatsmyos.com):**
 - OS: Catalina OS X 10.15.7m 16GB Memory

**Comment by andygup** [comment]
Hi @ornerymoose can you provide a github repo that reproduces the issue?

**Comment by andygup** [comment]
@ornerymoose quick update, I have been able to reproduce the issue and we'll take a closer look. 

We'll still need to know your package.json and any other configuration settings?

A couple of items to note:
* The app seems to run fine with Firefox. 
* I'm testing with these package.json settings: https://github.com/Esri/jsapi-resources/pull/345/files#diff-a1f05b890aac8a3404e46610c43a059e96c32092428518138e77e9f7943236b3
* The production build size that I'm getting is less than yours, for example:

![image](https://user-images.githubusercontent.com/510440/136829561-f33551f9-a906-4109-8603-76939c474a5b.png)

**Comment by andygup** [comment]
@ornerymoose Using the updated [.browserslistrc](https://github.com/Esri/jsapi-resources/blob/master/esm-samples/jsapi-vue-cli/.browserslistrc) file in this repo's VueJS sample I'm no longer experiencing performance issues with desktop Firefox or Chrome. 

I'll go ahead and close this out as verified. Let us know how your testing goes?
