### ISSUE TITLE
@arcgis/core: unable to set basemap center

### ISSUE THREAD

**Issue by t-zhai** [Esri/jsapi-resources#348]
**@arcgis/core version** 4.21.2

I was able to bring the `esm-samples\jsapi-angular-cli` project into my own angular project to display the map in a component.

I changed the "portalItem" base layer for the WebMap object to `basemap: 'hybrid'`, but it appears that all of the other common attributes are gone for web map, e.g. center, zoom etc. There doesn't seem to have anyway to set its center either after instantiation.

I tried to use `Map `object, but it doesn't have the `.when()` event handler.

Actually, is there a more significant example program using @arcgis/core beyond this simple map display? I mean that include loading layers, display attribute tables, select features, generate features etc.

**Comment by andygup** [comment]
Hi @t-zhai have you consulted the online API reference and samples? For example: https://developers.arcgis.com/javascript/latest/sample-code/. Note that the API functionality is same whether you are using the AMD modules or ES modules from @arcgis/core.

**Comment by t-zhai** [comment]
@andygup Yes, I have been on that page for many code examples, so far, pretty much all of the features that actually worked are using the AMD (require) way of loading the ArcGIS JavaScript API. I was able to get this angular example from you setup as a component in my asp.net/angular web app, but it has issues: first, it needs to have its container dimension set, otherwise the map won't show, i.e. `<div #mapViewNode style="width:800px; height:800px"></div>` , then the zoom in/out button are all out of place, like below:

![image](https://user-images.githubusercontent.com/12884627/142049939-87e329ec-8f90-4af3-8310-38df9cf9ed6c.png)

Then, I can't set its center in the component code, i.e. below doesn't work, it will just show the whole world map:

```
const view = new MapView({
      container,
      map: webmap,
      center: [-122.260544024, 37.81939394],
    });
```

The reason I ask for more complete angular example is that pretty much all example codes online are for AMD loading and I am not sure those code snippets can "just work" inside an angular component JS API code.

**Comment by odoe** [comment]
Can you provide a reproducible sample repo of the issue? I tested changing basemap and view center in the angular demo in this repo various ways and it seems to work ok.

```ts
const webmap = new WebMap({
  portalItem: {
    id: 'aa1d3f80270146208328cf66d022e09c',
  },
  basemap: 'streets'
});

const view = new MapView({
  container,
  map: webmap,
  center: [-122.260544024, 37.81939394]
});
```

This worked too.

```ts
ngOnInit(): any {
  // Initialize MapView and return an instance of MapView
  this.initializeMap().then((view) => {
    view.center = [-122.260544024, 37.81939394];
    // The map has been initialized
      console.log('The map is ready.');
  });
}
```

**Comment by t-zhai** [comment]
In general, angular is about reusable component. I am wondering if it is a good practice to have one instance of Map, WebMap, MapView, then these can be reused and inserted into different components? or are we just suppose to instantiate a Map and MapView in each component that uses map?

**Comment by andygup** [comment]
Hi @t-zhai have you been able to solve the first issue [that you reported above](https://github.com/Esri/jsapi-resources/issues/348#issuecomment-970587057)? As @odoe 
 mentioned, can you provide a simple/minimal github repository that demos your basic app? 

With regards to the buttons being out of place, it's possible the CSS isn't set, take a look at how we set it in our sample: https://github.com/Esri/jsapi-resources/blob/master/esm-samples/jsapi-angular-cli/src/app/app.component.css.

**Comment by t-zhai** [comment]
@odoe first of all, your code is not correct in that, it should be: **this.**`view.center = [-122.260544024, 37.81939394];`, so if your code works, I wonder what web app environment you are using? is it really angular? Anyway, your suggestions do not work. I attached the component in my test per this question here as a zip file
[analysis-crystallizer.zip](https://github.com/Esri/jsapi-resources/files/7550535/analysis-crystallizer.zip)

**Comment by t-zhai** [comment]
@andygup You are right, I didn't import the esri css in my component, I just added these import and it is working:
![image](https://user-images.githubusercontent.com/12884627/142083376-40792d5b-ffd5-4c89-9d43-1a4c4ff75720.png)

The centering is still not working though.

**Comment by benelan** [comment]
@t-zhai, depending on how you set up that side panel you may need to offset the map view. Here is an example:
https://developers.arcgis.com/javascript/latest/sample-code/view-padding/

**Comment by benelan** [comment]
Although in the screenshot above it does look centered on San Francisco which is `[-122.260544024, 37.81939394]`. Maybe you're looking for the [zoom property](https://developers.arcgis.com/javascript/latest/api-reference/esri-views-MapView.html#zoom)?

**Comment by t-zhai** [comment]
@benelan You are right about padding, I set a padding around the map div, so after removing it, it is filling the grid cell now.

No, that screen shot was just after my random zoom, I've tried many of other point locations, setting `this.view.center = []` doesn't work here.

**Comment by t-zhai** [comment]
As a side question, in an angular component, does the following code destroy all map elements (i.e. Map, MapView, Expand, FeatureLayer, LayerList, etc etc):

```
ngOnDestroy() {
    if (this.view) {
      this.view.destroy();
    }
}
```

**Comment by odoe** [comment]
@t-zhai the code is correct because in our sample, the `initializeMap` returns the view.
https://github.com/Esri/jsapi-resources/blob/master/esm-samples/jsapi-angular-cli/src/app/app.component.ts#L64

Again, if you provide a reproducible github repo of your issue, we can better help you, until then, we're just guessing.

**Comment by odoe** [comment]
@t-zhai I think @benelan is correct. Using your component you provided, the center does work, but if you don't change the zoom level, it's tough to tell. If you do it like this, it's much more noticeable that the center and zoom properties are updated correctly.

```ts
ngOnInit(): any {
  this.initializeMap().then(() => {
    this.view.center = [-122.260544024, 37.81939394];
    this.view.zoom = 6; // try this
    console.log('The map is ready.', this.view);
  });
}
```

**Comment by t-zhai** [comment]
@odoe I think this ultimately is because I didn't import the esri css file originally, which made the whole map layout a mess. 

Yes, setting the zoom level made the centering more visible now.
