### ISSUE TITLE
Deferred Return types

### ISSUE THREAD

**Issue by davewilton** [Esri/jsapi-resources#35]
The type on execute of esri/tasks/QueryTask is of type any. It should be of promise so that you are not forced to use callbacks (personal pref but I much prefer promises). There are many examples where this is the case other than query

I understand that you may not want to create a dependency on the dojo typings, but could an esriDeferred or similar not be included? I believe this is what has been done with esri.color

 execute(parameters: Query, callback?: Function, errback?: Function): dojo.promise.Promise<any>

interface Deferred<T> {

```
    /**
     * The public promise object that clients can add callbacks to.
     */
    promise: promise.Promise<T>;

    /**
     * Checks whether the deferred has been resolved.
     */
    isResolved(): boolean;

    /**
     * Checks whether the deferred has been rejected.
     */
    isRejected(): boolean;

    /**
     * Checks whether the deferred has been resolved or rejected.
     */
    isFulfilled(): boolean;

    /**
     * Checks whether the deferred has been canceled.
     */
    isCanceled(): boolean;

    /**
     * Emit a progress update on the deferred.
     */
    progress(update: any, strict?: boolean): promise.Promise<T>;

    /**
     * Resolve the deferred.
     */
    resolve(value?: T, strict?: boolean): promise.Promise<T>;

    /**
     * Reject the deferred.
     */
    reject(error?: any, strict?: boolean): promise.Promise<T>;

    /**
     * Add new callbacks to the deferred.
     */
    then<U>(callback?: promise.PromiseCallback<T, U>, errback?: promise.PromiseErrback<U>, progback?: promise.PromiseProgback): promise.Promise<U>;

    /**
     * Inform the deferred it may cancel its asynchronous operation.
     */
    cancel(reason?: any, strict?: boolean): any;

    /**
     * Returns `[object Deferred]`.
     */
    toString(): string;
}
```

**Comment by dasa** [comment]
> It should be of promise so that you are not forced to use callbacks (personal pref but I much prefer promises).

Have you tried to cast to Deferred?

**Comment by davewilton** [comment]
Yes you can cast to type deferred (code below). But I feel that as the [API documentation](https://developers.arcgis.com/javascript/3/jsapi/querytask-amd.html#execute) states that these are of type deferred explicitly then it should follow the API documentation

    <Deferred<any>>queryTask.execute(query).then((res) => {
               console.log(res);
     });

**Comment by dasa** [comment]
Fix in 4.x.
