### ISSUE TITLE
`applyEdits()` promise return type

### ISSUE THREAD

**Issue by COV-GIS** [Esri/jsapi-resources#359]
Why does `applyEdits()` return `Promise<any>` instead of an object interface with `FeatureEditResult[]` for `addFeatureResults`, etc. similar to the `FeatureLayerEditsEvent` interface?

It would be easier to work with if it was typed.

Thanks.

**Comment by lboyd93** [comment]
@COV-GIS - Thanks for your feedback! We updated the `applyEdits` method to return `Promise<EditsResult>` and added a new `EditsResult` type in the next release (4.23).
