### ISSUE TITLE
Esri ES6 modules inside Angular Elements with Shadow DOM

### ISSUE THREAD

**Issue by GeofoxCoding** [Esri/jsapi-resources#360]
Hi,

we are currently shifting parts of our applications / components to web componnents.

I tried to create a basic WebMap/MapView example inside an Angular component that get's transformed into an Angular Elements Web Component. 

This is how I register my component as web component in app.module.
```
export class AppModule implements DoBootstrap {

  constructor(private injector: Injector) {}

  // eslint-disable-next-line @angular-eslint/no-empty-lifecycle-method
  ngDoBootstrap() {

    // Initialize FIS-HWRM esri map viewer component
    const hwrmEsriMapComponent = createCustomElement(EsriMapComponent, {
      injector: this.injector
    });
    customElements.define("fis-hwrm-esri-map", hwrmEsriMapComponent);

  }
}
```

This is my component with shadowDom:

```
@Component({
  selector: 'hwrm-esri-map',
  templateUrl: './esri-map.component.html',
  styleUrls: ['./esri-map.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.ShadowDom
})
export class EsriMapComponent implements AfterViewInit {

  constructor() { }

  ngAfterViewInit(): void {

    const map = new WebMap({
      basemap: "topo-vector"
    });
  
    const view = new MapView({
      container: 'esri-map-container',
      map: map
    });
  }

}
```

It seems like Esri API can't attach to the components ShadowDom. No map gets rendered. If I change the strategy to ViewEncapsulation.None, the map appears.

It would be really great if I could encapsulte the map viewer DOM.

**Comment by andygup** [comment]
@GeofoxCoding thanks for the feedback. We don't have any near-term plans to support third-party framework's ShadowDOM with the ArcGIS API for JavaScript. However, if are able to solve the issue on your end please post your findings along with your Angular and ArcGIS JS API version info.

**Comment by GeofoxCoding** [comment]
@andygup Okay thank you, I understand that. For the moment I was able to solve my issue the following way:

Create the Angular component with ViewEncapsulation.ShadowDom as shown above. The template of the component should look like this:

`<div id="esri-map-container"></div>`

This div is now child of the Angular components ShadowRoot. So inside your component you should initialize the map viewer like so:

```
import { Component, OnInit, ChangeDetectionStrategy, ViewEncapsulation, 
         ElementRef,  } from '@angular/core';

import WebMap from "@arcgis/core/WebMap";
import MapView from "@arcgis/core/views/MapView";

@Component({
  selector: 'hwrm-esri-map',
  templateUrl: './esri-map.component.html',
  styleUrls: ['./esri-map.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.ShadowDom
})
export class EsriMapComponent implements OnInit {

  constructor(private host: ElementRef) { }

  ngOnInit(): void {

    const map = new WebMap({
      basemap: "topo-vector"
    });
  
    const view = new MapView({
      container: this.host.nativeElement.shadowRoot.querySelector('#esri-map-container'),
      map: map
    });
  }

}
```

This seems to work
![image](https://user-images.githubusercontent.com/79018547/146522032-81371553-1adf-4080-b28b-343c5207fa12.png)
