### ISSUE TITLE
Bug: canUndo and canRedo are missing

### ISSUE THREAD

**Issue by rscheitlin** [Esri/jsapi-resources#368]
**Describe the bug**
CanUndo and canRedo functions are missing from the typescript definition of SketchViewModel class

**Expected behavior**
These functions exist in the API and work, but are not publicly exposed in the API and thus not in the typescript definition for the SketchViewMdoel class.

**Reproduce the issue**
When importing the SketchViewMdoel class and you attempt to use these functions errors are presented in Visual Studio Code.

**Comment by banuelosj** [comment]
@rscheitlin ,
Thanks for bringing this up! I will take care of documenting these methods in `version 4.23`. I will close this issue out now.
