### ISSUE TITLE
@arcgis/core: Is there a way to speed up the build time when building with React?

### ISSUE THREAD

**Issue by veech** [Esri/jsapi-resources#372]
**@arcgis/core version**
`@arcgis/core@4.22.2`

**Framework and build tools** 
`React 17.0.1`

**Describe the bug**
I'm always deterred from using this library because whenever I add it to a project it increases build times to crazy lengths. I end up having to use something like [esri-loader](https://github.com/Esri/esri-loader) instead.

This issue happens even in the example [create-react-app](https://github.com/Esri/jsapi-resources/tree/master/esm-samples/jsapi-create-react-app)

**Expected behavior**
Faster build time

**Reproduce the issue**
`npm run build` within any react app that pulls this library in

**Comment by odoe** [comment]
Not really. create-react-app has it's own webpack config that you can't really modify too much. You can, but it still won't be great. For create-react-app, you can try craco, which uses esbuild. It is much, much faster for builds. You might be sacrificing some build size, slightly, but I haven't done a thorough comparison for it in this case.
https://github.com/pradel/create-react-app-esbuild

Vite with a React also uses esbuild and would be faster than create-react-app.
https://vitejs.dev/

**Comment by benelan** [comment]
Additionally, the sample we have uses CRA 4x, so bumping it to 5 would likely help a bit as well.

**Comment by veech** [comment]
Thanks for the tips!
