### ISSUE TITLE
🐞 Bug: FeatureLayer fields with parenthesis fail (w/ in memory data) (4.22)

### ISSUE THREAD

**Issue by rustygreen** [Esri/jsapi-resources#379]
**The issue**
When creating a feature layer from an in memory source (array of graphics), version 4.22 of the JS API will throw an error when using a field with a parenthesis in it (ex: `"st_length(shape)"`).

**Expected behavior**
It is expected that this field would be supported as this field is a valid field that can be published from ArcGIS Server.

**Reproduce the issue**
The bug can be demonstrated in the following codepen example:
https://codepen.io/rustygreen/pen/dyZZXMY?editors=1001

If you change the ArcGIS version to 4.21, then it will not throw an error. If you comment out the `st_length(shape)` field (in the 4.22 version), then the example will work (pointing to that field being the issue).

```javascript
  const layer = new FeatureLayer({
    id: "4535209429701526",
    title: "USA - Highways",
    source: graphics,
    visibility: true,
    objectIdField: "objectid",
    geometryType: 'polyline',
    fields: [
      {
        alias: "OBJECTID",
        editable: true,
        length: -1,
        name: "objectid",
        nullable: true,
        type: "oid"
      },
      // Comment out the following field and it will work.
      // If you change to version 4.21 it will work with this field.
      {
        alias: "st_length(shape)", // <----------------- THE PROBLEM FIELD
        editable: true,
        length: -1,
        name: "st_length(shape)",
        nullable: true,
        type: "double"
      }
    ],
    spatialReference: {latestWkid: 4326, wkid: 4326}
  });

  map.add(layer);
});
```

![image](https://user-images.githubusercontent.com/1774477/154184963-071932c3-9311-43a1-b527-45f24e296128.png)

**Comment by ubatsukh** [comment]
Hi there, 

We fixed this issue for 4.23. You can test the fix on our next version: https://codepen.io/U_B_U/pen/yLPEYJe?editors=1001

Thanks for reporting this issue.
