### ISSUE TITLE
@arcgis/core: projection.project has weird type definition

### ISSUE THREAD

**Issue by sandrooco** [Esri/jsapi-resources#381]
**@arcgis/core 4.x (all)**

**Describe the bug**
[projection.project](https://developers.arcgis.com/javascript/latest/api-reference/esri-geometry-projection.html#project) supports `Geometry | Geometry[]`. The return type is defined "wrong-ish" though --> the return type cannot be inferred properly, leading to `Type 'Geometry | Geometry[]' is not assignable to type 'Geometry'.` errors.

Current type definition:
`project(geometry: Geometry | Geometry[], outSpatialReference: SpatialReference | SpatialReferenceProperties, geographicTransformation?: GeographicTransformation): Geometry | Geometry[];`

**Expected behavior**
The type definiton could be like this (I tested it with a mock):
`project<T extends Geometry | Geometry[]>(geometry: T, outSpatialReference: SpatialReference | SpatialReferenceProperties, geographicTransformation?: GeographicTransformation): T;`
This allows compilers and IDEs to safely infer the usage of the type.

**Reproduce the issue**
Use this snippet:
```typescript
const unmappedLocation = new Point({ longitude, latitude }); // Point as WGS
const currentLocation = project(unmappedLocation, { wkid: 2056 }); // Point as LV95/2056

const query = ...; // Query object from @arcgis/core/rest/support/Query
query.geometry = currentLocation; // will throw error with the current definition: Type 'Geometry | Geometry[]' is not assignable to type 'Geometry'.
```

**Comment by Biboba** [comment]
Oups, actually it's my mistake: I was still using the deprecated task module.
After switching to 

`@arcgis/core/rest/support/ProjectParameters`

I no longer have typings issue

**Comment by sandrooco** [comment]
@ubatsukh Maybe @Biboba's problem is resolved, mine still exists though.
I also just checked with latest 4.22.6.

Please reopen?
