### ISSUE TITLE
Bug: DirectionsViewModel stops broken in 4.23

### ISSUE THREAD

**Issue by fadijabi** [Esri/jsapi-resources#390]
I upgraded @arcgis/core to 4.23 and my implementation for the DirectionsViewModel generated a lot of bugs. I read all the breaking changes and I modified as per the changes but I still get too many errors. My guess is that the new "Stop" object is not really auto-casting to a graphic. I noticed that the DirectionsViewModel also does not take the stopSymbols as well and render a dummy black default stop on the map and again my guess because it is not auto-casting to a graphic.

This is also generating a problem when calling getDirections giving an error before even doing a request to the NA server as shown below:

Cannot destructure property 'distanceAttributeName' of 'g' as it is undefined.

**Comment by NoashX** [comment]
Hi @fadijabi, thanks for reporting this issue. We are looking into this now, and will respond back here once we have an update to share.

**Comment by NoashX** [comment]
Hi @fadijabi, we're investigating, and working on a fix for the first two issues, but we're not able to reproduce the error: `Cannot destructure property 'distanceAttributeName' of 'g' as it is undefined.`

Can you share some code that reproduces the issue? And is this a custom NA service, or an Esri NA service?

**Comment by fadijabi** [comment]
Hi again,

No it is not an Esri NA service. It is a default routing service published in our environment and it was working fine for 4.22.x versions. I won't be able to provide reproducible code because all services are geo-restricted and won't be accessed from your end. However, I will share the below code snippets for your reference:

` const getDirections = useCallback(_ => {

        if (!directionsViewModel || !hasValidStops()) return;

        let routeParameters = new RouteParameters({
            returnStops: true,
            returnBarriers: true,
            returnDirections: true,
            returnRoutes: true,
            useHierarchy: true,
            ignoreInvalidLocations: true,
            directionsLengthUnits: 'meters',
            outputLines: 'true-shape',
            directionsLanguage: 'en'
        });

        directionsViewModel.routeParameters = routeParameters;

        setDirectionsViewModelRouteResultsLoading(true);

        directionsViewModel.getDirections()
            .then(result => {

                setDirectionsViewModelRouteError(null);
                setDirectionsViewModelRouteResults(result?.routeResults ?? []);
            })
            .catch(e => setDirectionsViewModelRouteError(new Error(e.message))) <== here I get Cannot destructure property 'distanceAttributeName' of 'g' as it is undefined
            .finally(_ => setDirectionsViewModelRouteResultsLoading(false));

    }, [directionsViewModel, routeParametersPointBarriersRef, hasValidStops])`

And somewhere in my code I am setting the stops on the DirectionsViewModel. Example stops:

`const defaultStops = useMemo(_ => {

        if (!mapView) return [];

        return new Collection([
            new Stop({
                geometry: { type: 'point', x: -1, y: -1, spatialReference: mapView.spatialReference },
                attributes: { id: uuidv4(), value: '' }
            }),
            new Stop({
                geometry: { type: 'point', x: -1, y: -1, spatialReference: mapView.spatialReference },
                attributes: { id: uuidv4(), value: '' }
            })
        ]);

    }, [mapView]);`

Of course, I'm attaching dummy x,y here for the stops. I tried setting locationType for each stop and also did not work. Also, I used to pass a simple array for the stops as simple graphics with attributes and it was working. Now I have to explicitly pass "new Collection" of "Stops" or I will get e.getItemAt is not a function error.

**Comment by NoashX** [comment]
Thanks @fadijabi. Do you know if there is a default travel mode set on the routing service? If not, can you try adding one to the RouteParameters?
https://developers.arcgis.com/javascript/latest/api-reference/esri-rest-support-RouteParameters.html#travelMode

**Comment by NoashX** [comment]
And for the Collection issue, yes, that was a breaking change at 4.23:
https://developers.arcgis.com/javascript/latest/release-notes/#breaking-changes

**Comment by fadijabi** [comment]
> Thanks @fadijabi. Do you know if there is a default travel mode set on the routing service? If not, can you try adding one to the RouteParameters? https://developers.arcgis.com/javascript/latest/api-reference/esri-rest-support-RouteParameters.html#travelMode

The service does not return travel modes and it returns empty array and it was working for previous versions. Because of that yes I did set a TravelMode by hand because I suspected it because of the error "Cannot destructure property 'distanceAttributeName' of 'g' as it is undefined" but still did not work.

**Comment by fadijabi** [comment]
> And for the Collection issue, yes, that was a breaking change at 4.23: https://developers.arcgis.com/javascript/latest/release-notes/#breaking-changes

Regarding the collection why can't I set [Stop1, Stop2] for future versions as before for the graphics instead of new Collection([Stop1, Stop2]). I mean to be consistent with other modules that accepts normal arrays [].

**Comment by fadijabi** [comment]
Small update:

getDirections returns this error when passing a TravelMode to RouteParameters:
TypeError: t.toJSON is not a function at l._writeNetworkFeatures

If no TravelMode passed:
TypeError: Cannot destructure property 'distanceAttributeName' of 'g' as it is undefined

**Comment by odoe** [comment]
@fadijabi for the stops, you don't need to create a new Collection, but the preferred way would be to use the collection methods to add and remove your stops.

```js
// add stops
directionsWidget.viewModel.stops.addMany([stop1, stop2]);

// clear at some point
directionsWidget.viewModel.stops.removeAll();
```

I had to make similar updates to an application as well.
https://github.com/odoe/nearby-app/blob/main/src/data/routing.ts#L23-L24

**Comment by fadijabi** [comment]
> @fadijabi for the stops, you don't need to create a new Collection, but the preferred way would be to use the collection methods to add and remove your stops.
> 
> ```js
> // add stops
> directionsWidget.viewModel.stops.addMany([stop1, stop2]);
> 
> // clear at some point
> directionsWidget.viewModel.stops.removeAll();
> ```
> 
> I had to make similar updates to an application as well. https://github.com/odoe/nearby-app/blob/main/src/data/routing.ts#L23-L24

Correct, this is what I do when modify the stops. However, when initializing the view model with default stops I have to create a new Collection. If I pass an array [stop1, stop2] it will create an error.

`let directionsViewModel = new DirectionsViewModel({
            view: mapView,
            routeServiceUrl,
            maxStops: 10,
            stops: new Collection([stop1, stop2]),
            stopSymbols: {
                first: new SimpleMarkerSymbol({
                    color: '#4caf50',
                    path: 'M12 2C6.47 2 2 6.47 2 12s4.47 10 10 10 10-4.47 10-10S17.53 2 12 2z',
                    size: '28px',
                    outline: null
                }),
                middle: new SimpleMarkerSymbol({
                    color: '#ff9800',
                    path: 'M12 2C6.47 2 2 6.47 2 12s4.47 10 10 10 10-4.47 10-10S17.53 2 12 2z',
                    size: '28px',
                    outline: null
                }),
                last: new SimpleMarkerSymbol({
                    color: '#ef5350',
                    path: 'M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm4 14H8V8h8v8z',
                    size: '28px',
                    outline: null
                })
            },
            routeSymbol: {
                type: 'simple-line',
                cap: 'round',
                join: 'round',
                width: 7,
                color: [41, 182, 246, 1]
            }
        });`

 Or I have to do it on two lines initializing the view model... then viewModel.stops.addMany([stop1, stop2])

**Comment by fadijabi** [comment]
Hello again,

Any update?
Noticed on the docs now DirectiosViewModel has no stops property?

**Comment by fadijabi** [comment]
Hello again,

I upgraded to v4.24 and I still facing issues regarding DirectionsViewModel

1. RouteLayer is not added to the map as expected. It only showed when I added it by hand.
2. Stops lose "attributes" field after solving.
 
I'm stuck in version 4.22.2 that is stable for me.
