### ISSUE TITLE
Bug: FeatureTable's highlightOnRowSelectEnabled not working with FeatureLayer created from Sublayer

### ISSUE THREAD

**Issue by ranga-tolapi** [Esri/jsapi-resources#391]
**Describe the bug**

1. Created a FeatureLayer from Sublayer using sublayer.createFeatureLayer()
2. Created a FeatureTable from the FeatureLayer of step no. 1 above
3. Refer to the enclosed codepen
4. When selected a Row from FeatureTable, corresponding feature on the map is **not getting highlighted**

**Expected behavior**
When selected a Row from FeatureTable, corresponding feature on the map **should get highlight**

**Reproduce the issue**
Refer to codepen sample at https://codepen.io/rangasatishkumar/pen/gOomNBW

**Browser (check https://whatismybrowser.com/)** 
 - Browser: Chrome Version 99.0.4844.82 (Official Build) (32-bit) on Windows 10
 
**Operating System (check https://whatsmyos.com):**
 - OS: Windows 10 64-bit

**Additional context**

**Comment by odoe** [comment]
You need to add the FeatureLayer to the map to see the highlighted results.
https://codepen.io/odoe/pen/KKZmzLm?editors=1000
