### ISSUE TITLE
Label issues when rendering basemap in 3D SceneView

### ISSUE THREAD

**Issue by jlczapski** [Esri/jsapi-resources#399]
**Describe the bug**
When adding a 2D basemap to a 3D SceneView through the ArcGis JS API, the labels for city, town names etc. get cut off in places and the font sizes seem tiny for certain basemaps. I thought the issue may have come from our custom configuration but I can see the same problem on the documentation [here](https://developers.arcgis.com/javascript/latest/display-a-scene). 

2D Map:
![2d_map](https://user-images.githubusercontent.com/16479189/161783035-0b9d6511-da4a-4c70-8991-686a274e7961.PNG)

3D Scene:
![3d_scene](https://user-images.githubusercontent.com/16479189/161783040-4e4dad2c-3d02-490a-a0f6-7eaaf8079927.PNG)

3D Scene on docs:
![docs_issue](https://user-images.githubusercontent.com/16479189/161783106-627b5841-84ec-4687-a895-3014aefec9f5.PNG)

**Expected behavior**
Labels should display the same across 2D and 3D views.

**Reproduce the issue**
Zoom into a country (e.g. UK) on the demo map viewer at [this](https://developers.arcgis.com/javascript/latest/display-a-scene) link to see the labels rendering at very small font sizes & also being clipped after a certain length.

**Browser** 
 - Browser: Firefox 98 on Windows 10
 
**Operating System**
 - OS:  Windows 10* 64-bit
 - Device: Dell Laptop

**Additional context**
Anything else that will help.

**Comment by jlczapski** [comment]
Is anyone able to assist with this?

**Comment by Fuhji** [comment]
The same basemap applied to a Map View works well, but the same basemap applied to a Scene View has the smaller label issue as seen in that official sample. It means our users complain that the font is too small so as to be unreadable.

Using the [ESRI Vector style editor](https://developers.arcgis.com/vector-tile-style-editor/) does let you increase the font size for each element of the basemap, but you then his the issue where labels are cropped/clipped.

Is this something others are finding, or is this Just How It Is and no fixes are likely to be incoming? The ESRI community forums also have discussions on this and the only answer was 'make fonts bigger'.

**Comment by Fuhji** [comment]
A workaround is the set the SceneView `qualityProfile` to `low` so although the basemap becomes fuzzier/less sharp, the labels are now readable. It would be nice to have more granular control as this is a performance setting, but solves the unreadable basemap issue for now.

https://developers.arcgis.com/javascript/latest/api-reference/esri-views-SceneView.html#qualityProfile

**Comment by Fuhji** [comment]
If this is not seen as a bug it feels like a serious flaw that labels are unreadable when in SceneView. Surely this is an issue for anyone using SceneView?!
