### ISSUE TITLE
Typescript subclassing in v4.1

### ISSUE THREAD

**Issue by nickcam** [Esri/jsapi-resources#40]
Hi,

In v4.0 I am creating some custom classes using simple inheritance in typescript. For example:

```
import * as GraphicsLayer from "esri/layers/GraphicsLayer";

export class CustomLayer extends GraphicsLayer {
    constructor(options: __esri.GraphicsLayerProperties) {
            super(options);
    }
   
    //implementation....
}
```
This is no longer working in 4.1 - error occurs on the `super(options)` call in the constructor. Not just for graphics layers, but for a renderer and the popup widget, so I'm assuming this is across the board.

I've had a quick look and from what I can gather the accessor objects metadata property is not getting assigned when subclassing in this way.

Before I dug too deep thought I'd just ask if you're aware of this and if you know of how to handle subclassing in typescript for v4.1?

For a detailed example working in 4.0 - [https://github.com/nickcam/FlareClusterLayer](https://github.com/nickcam/FlareClusterLayer)

Thanks.

**Comment by ycabon** [comment]
Hi @nickcam,

We have been rewritting the layers in typescript/Accessor which requires some specific logic for subclassing. We aren't ready yet to doc how to subclass `Accessor` based classes, as this is still subject to change, but I have put up a repo here https://github.com/ycabon/extend-accessor-example with some example of subclassing.
For your specific need:

```ts
/// <amd-dependency path="esri/core/tsSupport/declareExtendsHelper" name="__extends" />

import { declared, subclass } from "esri/core/accessorSupport/decorators";

import Accessor = require("esri/layers/GraphicsLayer");

@subclass("package.app.ClassA")
class CustomLayer extends declared(GraphicsLayer) {
  // ...
```

**Comment by nickcam** [comment]
Thanks @ycabon. Have it working using the examples in the linked repo now.

**Comment by ycabon** [comment]
:+1:
