### ISSUE TITLE
🐞Bug: PBF parsing issue with HANA DB

### ISSUE THREAD

**Issue by rustygreen** [Esri/jsapi-resources#401]
**Describe the bug**
There appears to be an issue with parsing PBF payloads from a map service pointed to an SAP HANA DB (which is a supported platform).

When adding a FeatureLayer pointed to a Map or Feature service that is referencing HANA data, we get a `Error while parsing FeatureSet PBF payload` error message.

![image](https://user-images.githubusercontent.com/1774477/163002590-d108a36f-ffb8-422a-8016-0232272a4940.png)

We have removed all fields from the data except "OBJECTID" and limited to just 1 feature and we continue to get the error. We see this same behavior for any Map or Feature layers that are published from HANA data. The service can be queried using a `json` response with no issues.

The FeatureLayer from that service will work in a SceneView, but will not work in a MapView:
![image](https://user-images.githubusercontent.com/1774477/163019260-5e0cb0a3-33b9-469a-8ed2-d9de14c89a5f.png)

**Reproduce the issue**
1. Publish a feature service from data pointed to HANA
2. Try to add a FeatureLayer pointed to that service

Here is an example of the issue:
https://www.arcgis.com/apps/mapviewer/index.html?url=https://portal.rizing.com/pipeline/rest/services/HanaCloud/Omni_Water/FeatureServer/0

Example service: https://portal.rizing.com/pipeline/rest/services/HanaCloud/Omni_Water/FeatureServer/0

**Browser (check https://whatismybrowser.com/)** 
 - Browser: any
 - ArcGIS Server version: 10.9.1
 - ArcGIS JavaScript API: 4.22
 
**Operating System (check https://whatsmyos.com):**
 - OS: any
 - Device: any

**Comment by mmgeorge** [comment]
Hi @rustygreen, this looks like a problem with your service. If you open the network tab, you'll notice that the queries are returning 400s: 

{"error":{"code":400,"message":"Unable to complete operation.","details":["Unable to perform query operation."]}}

**Comment by rustygreen** [comment]
Thanks, @mmgeorge.
