### ISSUE TITLE
Bug: Testing Angular component result an ResizeObserver not defined error

### ISSUE THREAD

**Issue by Or05230** [Esri/jsapi-resources#403]
**Describe the bug**
Using the basic template example provided in ArcGIS for angular, running a simple unit test just to initiate the component, result an error:
 ReferenceError: ResizeObserver is not defined

The error is coming from the MapView, if i'm creating a MapView element, i will get the error.
`const view =  new MapView({...mapViewArgs})`
**Expected behavior**
test should run. 

**Reproduce the issue**
Run a simple project of Esri in Angular 13, using Jest for testing.

 
**Operating System (check https://whatsmyos.com):**
 - OS: Mac OSX 
 - Device: Macbook M1

**Comment by andygup** [comment]
Hi @Or05230 I'll take a look and see if I can repro.

**Comment by andygup** [comment]
@Or05230 I did get it working with mocks. You'll need to implement mocks for ResizeObserver as well as all the @arcgis/core classes. I'll try to update that sample later today. In the meantime, you can take a look at these tests from a Vite/Vue implementation of Jest: https://github.com/odoe/nearby-app/blob/main/__tests__/data/map.spec.ts,

**Comment by andygup** [comment]
@Or05230 I updated the jest sample to work with mocks as well as included the ResizeObserver fix from @odoe: https://github.com/andygup/angular-jsapi-jest/blob/main/src/app/app.component.spec.ts. I'll go ahead and close this for now, let us know if any other showstopper issues come up.
