### ISSUE TITLE
@arcgis/core: webpack loader errors with React and TypeScript

### ISSUE THREAD

**Issue by mikepianka** [Esri/jsapi-resources#408]
**@arcgis/core version**
@arcgis/core 4.23.7, @types/arcgis-js-api 4.23.1

**Framework and build tools** 
create-react-app 4.0.3, typescript 4.6.4

**Describe the bug**
I am getting these webpack loader errors during dev for all the @arcgis/core widgets. My IDE and the app itself in the browser seem to run fine otherwise.

![image](https://user-images.githubusercontent.com/47948499/166702260-1fb95900-6eee-403f-8ba6-ef56cfdb401d.png)

**Expected behavior**
The app will still run, but upgrading to create-react-app v5 and the newer version of webpack it uses escalates these warnings to errors and the app will no longer run.

**Reproduce the issue**
This project is a wrapper library around @arcgis/core to make it easier to use in React so there is not a simple way to reproduce the issue. I can provide other info if it would be helpful. Here is the tsconfig:

``` json
// tsconfig.json
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "experimentalDecorators": true,
    "importHelpers": true,
    "noImplicitAny": true
  },
  "include": [
    "src"
  ]
}
```

**Browser (check https://whatismybrowser.com/)** 
Chrome 101 on Windows 10
 
**Operating System (check https://whatsmyos.com):**
 - OS: Windows 10 64bit
 - Device: PC

**Comment by mikepianka** [comment]
Hi @andygup. Thanks for the advice. I am just working with a vanilla create-react-app in this particular case so I don't have any custom config since I haven't ejected (aside from the tsconfig.json). 

Is there an official example of the jsapi in a react + typescript project? I know there is the react example you mentioned and this general typescript example: https://developers.arcgis.com/javascript/latest/typescript-setup/. If not I will just proceed combining what is found in both but I figured I would ask.

**Comment by dasa** [comment]
Can you try setting the `target` in your tsconfig to ES2020?

**Comment by odoe** [comment]
Here is a sample app using the create-react-app TypeScript template. I updated the browserlist and TS target. It still worked with es5, but we suggest es2020 in our guides.
https://github.com/odoe/jsapi-cra-ts

**Comment by mikepianka** [comment]
> Can you try setting the `target` in your tsconfig to ES2020?

@dasa I still have the issue if I change the target to ES2020. Thanks though.

> Here is a sample app using the create-react-app TypeScript template. I updated the browserlist and TS target. It still worked with es5, but we suggest es2020 in our guides. https://github.com/odoe/jsapi-cra-ts

@odoe Thanks for this. I will start a fresh repo with this and then try to migrate my code in to see if I can nail down what is causing the issue. One question I have is that when I started this project last year, I think the docs recommended installing both @arcgis/core and @types/arcgis-js-api. I see your example just has @arcgis/core now. Do the types no longer need to be separately installed?

Thanks everyone for the quick responses!

**Comment by andygup** [comment]
Correct, no need for a separate install. @arcgis/core comes with the TypeScript types included.

**Comment by mikepianka** [comment]
Things work with no webpack issues using @odoe's repo. Must have been some issue with a combination of older dependencies is all I can think of. Thanks again.
