### ISSUE TITLE
@arcgis/core: latest version's components never finish loading in React build

### ISSUE THREAD

**Issue by mikepianka** [Esri/jsapi-resources#409]
**@arcgis/core version**
@arcgis/core 4.23.7

**Framework and build tools** 
react-scripts 5.0.1

**Describe the bug**
After running a React build, no errors are reported in the browser but the @arcgis/core components do not load. There are no errors reported in the terminal during the build either. Everything works as expected during development. I have been using @arcgis/core for over a year and have not encountered this before. Downgrading to @arcgis/core 4.22.2 rectifies the issue.

View during development after `npm run start`. Things working as expected
![image](https://user-images.githubusercontent.com/47948499/166745764-08beb97e-047b-4c92-8abc-ef96271e6026.png)

View running a local server with the build produced by `npm run build`. The map does not load and the search widget has a loading spinner that never finishes.
![image](https://user-images.githubusercontent.com/47948499/166746160-61a57b60-205c-4625-b2dd-6fcf30e983ce.png)

**Expected behavior**
A build should be produced that behaves the same was as the app during development.

**Reproduce the issue**
https://github.com/mikepianka/react-arcgis-latest

I created this example repo using the following steps:
1. `npx create-react-app@latest react-arcgis-latest`
2. `cd .\react-arcgis-latest\`
3. `npm install @arcgis/core`
4. Create a basic `GIS.js` component and import it in `App.js`
5. `npm run start` and the app behaves normally during development
6. `npm run build` and then `npx serve .\build\` and the resulting app in the browser has @arcgis/core components that do not finish loading

Things work as expected in the last version of @arcgis/core:
`npm install @arcgis/core@4.22.2` to downgrade. Re-run `npm run build` and then the resulting build behaves normally

**Browser (check https://whatismybrowser.com/)** 
Chrome 101 on Windows 10
 
**Operating System (check https://whatsmyos.com):**
 - OS: Windows 10 64bit
 - Device: PC

**Comment by benelan** [comment]
Hi @mikepianka, can you try adding this browserlist, as described [here](https://github.com/Esri/jsapi-resources/tree/master/esm-samples/jsapi-create-react-app#misc).

```json
// package.json
{
  "browserslist": {
    "production": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
}
```

**Comment by mikepianka** [comment]
Hi @benelan, I just edited my answer because I found if I downgraded to @arcgis/core 4.22.2 it resolves the issue. So the problem is specifically in 4.23.x.

I will try your suggestion about the browserlist and report back in a few minutes.

**Comment by mikepianka** [comment]
@benelan those browserlist settings resolved the issue with the build. Thanks! Was there a change in 4.23.x that makes those browser targets required now? Because I didn't have those set and 4.22.x builds ran fine.

**Comment by benelan** [comment]
The issue has been around for a while, looks like it was first mentioned in [this commit for v4.18](https://github.com/Esri/jsapi-resources/commit/092aab3811b035b993dda21899ef38ba6eefaf59#diff-2268f29d048d5fff7280490809011534f913c773b73826f60ddddad2dac8c148). I'm not sure why it worked in v4.22.
