### ISSUE TITLE
Typings to @Types?

### ISSUE THREAD

**Issue by zkristov** [Esri/jsapi-resources#41]
Any plans to move away from Typings for 4.x? Similar to what others are doing.

    "@types/core-js": "^0.9.34",
    "@types/dojo": "^1.9.36",
    "@types/jasmine": "^2.5.36",
    "@types/node": "^6.0.46",

**Comment by dasa** [comment]
Yes, pending: https://github.com/Microsoft/types-publisher/issues/3

**Comment by dasa** [comment]
Fixed: https://github.com/Esri/jsapi-resources/blob/master/4.x/typescript/README.md
