### ISSUE TITLE
Bug: jest esri-loader errors

### ISSUE THREAD

**Issue by webmapLee** [Esri/jsapi-resources#415]
when i run esri-loader test with jest , it didn't work

### test case:
`
import { loadModules } from "esri-loader";
test('loadModules test', () => {
    const [Map] = await loadModules(['esri/map'])
    console.log('🐻🐻🐻🐻🐻', Map)
    expect(Map).toBeTruthy()
})
`
### errors:
`
thrown: "Exceeded timeout of 5000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

       6 | beforeAll(() => jest.setTimeout(90 * 1000))
       7 | describe('创建一个图形', () => {
    >  8 |   it('应该返回一个图形', async () => {
Jest.js:407:19)
      at _run10000 (../../node_modules/.pnpm/@jest+core@28.1.0/node_modules/@jest/core/build/cli/index.js:338:7)
      at runCLI (../../node_modules/.pnpm/@jest+core@28.1.0/node_modules/@jest/core/build/cli/index.js:190:3)
`

**Comment by odoe** [comment]
Please make an issue in the esri-loader repo. Thanks.
https://github.com/Esri/esri-loader
