### ISSUE TITLE
Run @arcgis/core test case with pnpm and jest

### ISSUE THREAD

**Issue by webmapLee** [Esri/jsapi-resources#416]
when i install @arcgis/core with pnpm , jest test case running error:

`
Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    C:\develop\learn\web\BDD\jest\jest-demo\node_modules\.pnpm\@arcgis+core@4.23.7\node_modules\@arcgis\core\Map.js:5    
    import{_ as e}from"./chunks/tslib.es6.js";import s from"./Basemap.js..........
`

but when i install @arcgis/core with npm ,it's ok , I don't know what's going on

my demo respo url is :[I don't know what's going on](https://github.com/webmapLee/jest-arcgis-demo.git)

**Comment by odoe** [comment]
I'm not sure if it's an issue with `@arcgis/core` or Jest. We have not tested extensively with pnpm and currently unsure if we need something in the package.json. Everything in core is set up as a pure ESM package, so I'm guessing this is a jest/pnpm issue. Will investigate in the future.

**Comment by webmapLee** [comment]
Thanks for your prompt reply，can you have a try with pnpm ,I will continue to pay attention to this qustion, thanks a lot

**Comment by odoe** [comment]
This is because `pnpm` uses modules installed in `node_modules/.pnpm`, so you need to update the transform in the jest config to take this into account.
```js
{
    ...
    transformIgnorePatterns: ['node_modules/(?!\\.pnpm/)(?!(@arcgis|@esri|@stencil|@popperjs)/)']
    ...
}
```

**Comment by webmapLee** [comment]
awesome👍👍👍, In the end, it is necessary to convert the esm syntax of @arcgis/core，thank you very much.
