### ISSUE TITLE
 qustion:some questions about widgets jsx

### ISSUE THREAD

**Issue by webmapLee** [Esri/jsapi-resources#417]
1. I can't understand what's it mean?  is it mean i can't  use a dependency jsx element
![image](https://user-images.githubusercontent.com/20334500/169731781-c34f23c2-42f2-4166-b5f2-ea2229df79d3.png)

2. can i use babel-plugin-jsx in vue components  and widgets jsx  in one project?

**Comment by andygup** [comment]
Hi @webmapLee, no that won't work with babel or Vue. You won't be able to mix the JSX from a custom widget built with the ArcGIS API for JavaScript with another JSX library. Our widgets are their own JSX library.
