### ISSUE TITLE
Declare public namespace to use classes

### ISSUE THREAD

**Issue by Cezus** [Esri/jsapi-resources#42]
I would like to use the ArcGIS for JavaScript classes like that is possible with AngularJS:

`$q: ng.IQService`

Now it's like this:

First I have to declare the class:
`import Map = require('esri/map');`

then I can do this:
`function (map: Map)`

With kind regards,

Cees van Altena

**Comment by shenningsgard** [comment]
Assuming you're using TypeScript / Esri JS 4.x, unless you're actually creating a new object, you can reference object definitions via the global "__esri" object. In your example, you'd do this:

`function (map: __esri.Map)`

**Comment by jkieboom** [comment]
I tend to use:

```ts
import esri = __esri;
```

At the top of the file, so I can refer to types in the `esri` namespace:

```ts
class A {
  get map(): esri.Map {
  }
}
```

Note that you can't instantiate types like this, for that you'll need to actually import the module still.
