### ISSUE TITLE
@arcgis/core: webpack error in 4.24 - "no loaders are configured to process this file"

### ISSUE THREAD

**Issue by HECHONG999** [Esri/jsapi-resources#424]
**@arcgis/core version**
`@arcgis/cor4.23 
Which version of `@arcgis/core`, for example `@arcgis/core@4.21.2`? Run `npm ls @arcgis/core` in a terminal window. 

Questions related to `next` releases of `@arcgis/core` need to be addressed on the https://github.com/Esri/feedback-js-api-next repo. 

**Framework and build tools** 

rollup2.75.6

**Describe the bug**
why I use @arcgis/core 4.25packeage by rollup but packgageed result is  reference 4.24， and the use of modular import reports an error
![image](https://user-images.githubusercontent.com/49875337/177302398-ed5c1e4e-2a26-4565-827a-41e074561f1b.png)

**Expected behavior**

See https://js.arcgis.com/4.23/esri/copyright.txt

**Reproduce the issue**
Steps to reproduce the behavior. Please provide github repo, codepen or equivalent so that we can reproduce the issue.

**Browser (check https://whatismybrowser.com/)** 
 - Browser: [e.g. "Chrome 87 on Windows 10"]
 
**Operating System (check https://whatsmyos.com):**
 - OS: [e.g. "Apple iOS 15" or "Windows 10* 64-bit"]
 - Device: [e.g. "iPhone 11" or "Samsung Galaxy S21"]

**Additional context**
Anything else that will help.

**Comment by benelan** [comment]
I hit this issue too when bumping the [nuxt sample](https://github.com/benelan/arcgis-esm-samples/tree/main/jsapi-create-nuxt-app) I maintain. I was able to bump the rest of the samples in that repo without issue.

## Repro Steps
```bash
git clone git@github.com:benelan/arcgis-esm-samples.git
cd arcgis-esm-samples/jsapi-create-nuxt-app
npm i @arcgis/core@latest
npm run build
```

![image](https://user-images.githubusercontent.com/10986395/179875395-b260a61c-c992-4e3b-b1bb-a90799bf23f3.png)

**Comment by benelan** [comment]
I remember seeing something similar in #235, but unfortunately [adding the `file-loader` rule](https://nuxtjs.org/docs/features/configuration/#extend-webpack-config) doesn't help in this case
```js
// nuxt.config.js
...
  build: {
    extend(config) {
      config.module.rules.push({
        test: /\.(ttf|eot|svg|png|jpg|gif|ico|wsv|otf|woff(2)?)(\?[a-z0-9]+)?$/,
        loader: 'file-loader'
      })
    }
  }
};
```

**Comment by odoe** [comment]
Weird, I don't know why it would start happening now, but if you add a `.babelrc` that tells babel to preserve ESM when loading.

```json
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "loose": true,
        "modules": false
      }
    ]
  ]
}

```

It still goes into the webpack build pipeline and webpack wraps it in its webpackJsonp goodness, but babel doesn't try to get weird about it.

**Comment by benelan** [comment]
Hmm... I'm still getting the error on my end. I'm on Windows so maybe that's causing the difference in behavior. Just to confirm, does this work on your end?

```bash
git clone git@github.com:benelan/arcgis-esm-samples.git
cd arcgis-esm-samples/jsapi-create-nuxt-app
git checkout nuxt-webpack-loader-error
npm i && npm run build
```

**Comment by andygup** [comment]
@benelan  I was able to repro on a Mac. Possibly related, there are some major issues with the dependencies like core-js. Is there a combination of packages that will let you upgrade the project to vue 3 and webpack 5?

**Comment by dasa** [comment]
Can you check what is at expand.js (5:1897)? 4.24 now includes optional chaining and nullish coalescing operators.

**Comment by andygup** [comment]
@dasa here's what I'm seeing:

<img width="693" alt="image" src="https://user-images.githubusercontent.com/510440/180032031-05888f91-757c-43c6-9723-8321672f7ab9.png">

**Comment by dasa** [comment]
OK, it appears that the parser isn't compatible with `?.`. Can you tell what is doing the parsing and what version it is?

**Comment by odoe** [comment]
I did something that made it work yesterday, trying to recreate that magic

**Comment by dasa** [comment]
Could the parser be in a dependency that got upgraded?

**Comment by benelan** [comment]
> Is there a combination of packages that will let you upgrade the project to vue 3 and webpack 5?

[Nuxt v3 uses Vue v3 and Vite](https://v3.nuxtjs.org/getting-started/migration#feature-comparison), but it is still unstable so I'd prefer to hold off on migrating the sample just yet.

**Comment by andygup** [comment]
@benelan did you try deleting package-lock.json and node_modules then reinstall? I "think"(!) that's what I did to get it working.

**Comment by andygup** [comment]
Thanks everyone for reporting this information. We've identified this as a Known Issue with Webpack 4 and JS API versions 4.24+. A work-around has been posted here: https://github.com/Esri/jsapi-resources/tree/master/esm-samples/webpack#known-issues. 

If possible, we recommend migrating off Webpack 4, it is our understanding that it is getting critical fixes, only.  The last release of Webpack 4 was [4.46.0](https://github.com/webpack/webpack/releases/tag/v4.46.0) in January 2021.

**Comment by andygup** [comment]
I'll go ahead and close this issue. If anything else comes up let us know here or open a new issue, thanks.
