### ISSUE TITLE
TypeScript 2.1.4 issue in .d.ts

### ISSUE THREAD

**Issue by AlainBaslter** [Esri/jsapi-resources#43]
I updated to TypeScript 2.1.4 and I get the error

declare module "esri/request" {
  import request = __esri.request;
  export = request.esriRequest;
}

Error: typings\globals\arcgis-js-api\index.d.ts(7181,12): error TS2702: 'request' only refers to a type, but is being used as a namespace here.

**Comment by jkieboom** [comment]
I think this should be fixed in the upcoming type definitions for 4.2 (should be released before the end of the year). Does that work for you? Otherwise we could patch the 4.1 type definitions.

**Comment by AlainBaslter** [comment]
I tried the above and I get this now...

typings\globals\arcgis-js-api\index.d.ts(7182,12): error TS2702: 'request' only refers to a type, but is being used as a namespace here.
[13:03:39] gulp-notify: [Error running Gulp] Error: typings\globals\arcgis-js-api\index.d.ts(7182,12): error TS2702: 'request' only refers to a type, but is being used as a namespace here.
typings\globals\arcgis-js-api\index.d.ts(7182,20): error TS2339: Property 'esriRequest' does not exist on type '(url: string, options?: requestEsriRequestOptions) => IPromise<any>'.
[13:03:39] gulp-notify: [Error running Gulp] Error: typings\globals\arcgis-js-api\index.d.ts(7182,20): error TS2339: Property 'esriRequest' does not exist on type '(url: string, options?: requestEsriR
equestOptions) => IPromise<any>'.

**Comment by jkieboom** [comment]
Sorry, forgot to mention. You also need to adapt https://github.com/Esri/jsapi-resources/blob/master/4.x/typescript/arcgis-js-api.d.ts#L7181-L7184 to be:

```ts
declare module "esri/request" {
  import request = __esri.request;
  export = request;
}
```

**Comment by AlainBaslter** [comment]
Excellent. That took care of it. Thank you.
