### ISSUE TITLE
Bug: White artifacts on transparent images in MediaLayer

### ISSUE THREAD

**Issue by mikepianka** [Esri/jsapi-resources#433]
**Describe the bug**
Transparent images will randomly have white artifacts where they are supposed to be transparent when used in the new MediaLayer. See the codesandbox below for a working example. You can see that of the image tiles, some render correctly while others have whitespace where the transparency should be. I tested this and had the same issue with two different image sets.

https://codesandbox.io/s/localimagelayer-3zuhty?file=/app.js

![image](https://user-images.githubusercontent.com/47948499/181102446-41b76ccd-0600-4954-a0bf-5ebb953f522d.png)

![image](https://user-images.githubusercontent.com/47948499/181102472-d3479850-8b64-4cf8-abbb-a27630911dd7.png)

**Expected behavior**
All of the images should render with a transparent background and no white artifacts.

**Reproduce the issue**
See this codesandbox: https://codesandbox.io/s/localimagelayer-3zuhty?file=/app.js

**Browser (check https://whatismybrowser.com/)**
 - Browser:
      Chrome 103 on Windows 10

**Operating System (check https://whatsmyos.com):**
 - OS:
      Windows 10* 64-bit"

**Comment by sagewall** [comment]
Hi @mikepianka ,

Thanks for reporting this issue, however this probably isn't the best place to do so.  In the future I'd suggest reporting a bug though Esri support and they will get it assigned to the appropriate team quickly.

This should be fixed as of version 4.25 where we fixed a bug where 24 and 32 bit images with transparent backgrounds were not displayed correctly.

I was able to take a couple of your images with the transparent border and make this codepen showing the transparency being properly honored.

https://codepen.io/sagewall/pen/MWPjyKe
