### ISSUE TITLE
404 error with "jsapi-resources/esm-samples/jsapi-custom-widget" deployment

### ISSUE THREAD

**Issue by LuisRguezEsriSpain** [Esri/jsapi-resources#436]
### IMPORTANT

- [X] My question is related to the samples and content within this repository. For all other issues, open a ticket with [Esri Technical Support](https://support.esri.com/) or post your question in the [community forum](https://community.esri.com/t5/arcgis-api-for-javascript/ct-p/arcgis-api-for-javascript) or .
- [X] I have [checked for existing issues](https://github.com/Esri/jsapi-resources/issues) to avoid duplicates. If someone has already opened an issue for what you are experiencing, please add a 👍 reaction and comment as necessary to the existing issue instead of creating a new one.

### Actual behavior

After running "npm run-script build" I deployed the "dist" directory on IIS (C:\inetpub\wwwroot\jsapi-custom-widget) and when I run the web app I see this errors:

![404_1](https://user-images.githubusercontent.com/13570124/187418954-4d41ca9c-8574-4a1b-b958-13c506a71cc4.png)

Then I did these changes on index.html (I replaced "/assets" with "./assets"):

    <link rel="icon" type="image/svg" href="./assets/favicon.17e50649.svg"/>
    <title>ArcGIS JS API Custom Widget</title>
    <script type="module" crossorigin src="./assets/index.1f0be054.js"></script>
    <link rel="stylesheet" href="./assets/index.5cf709e5.css">

Running again the web app I see this errors:
![404_2](https://user-images.githubusercontent.com/13570124/187419776-862c0b6e-d4e6-49f2-8b7b-fdbb87e01976.png)

### Expected behavior

After running "npm run-script build" and deploying the "dist" directory on IIS (C:\inetpub\wwwroot\jsapi-custom-widget) I expect the web app works properly.

### Reproduction sample

https://github.com/Esri/jsapi-resources/tree/master/esm-samples/jsapi-custom-widget

### Reproduction steps

1. npm run-script build
2. Crearte the "jsapi-custom-widget" in "C:\inetpub\wwwroot"
3. Copy the "dist" directory content in "C:\inetpub\wwwroot\jsapi-custom-widget" directory
4. Open the DevTools console
5. Run the web app
6. See the error messages in DevTools console

### Reproduction browser

Versión 104.0.5112.102 (Build oficial) (64 bits) on Windows 11

### Operating System (check https://whatsmyos.com)

Windows 11 64-bit

**Comment by andygup** [comment]
Hi @LuisRguezEsriSpain, the sample uses Vite and this sounds like a configuration issue. In the console log there are requests going to both `/assets` and `/jsapi-custom-widgets`.

My suggestion is review the Vite guidelines for creating a production build: https://vitejs.dev/guide/build.html, and in particular the Public Base Path doc here: https://vitejs.dev/guide/build.html#public-base-path.
