### ISSUE TITLE
Print Service Generates with Service ID as Title head at legends, how to avoid that.

### ISSUE THREAD

**Issue by vm-pa** [Esri/jsapi-resources#439]
Hello All,

Can someone help me how to avoid feature service's id shows up as title on legend portion of print service response file(PDF url) on point feature services. I want to show just legend and its label, not title on top of it, in the following image 'myPointFtrs' in red highlight is showing I want avoid that.
![image](https://user-images.githubusercontent.com/112712745/188193083-9a2f4646-eb41-4c63-a435-7b8c20623c1d.png)

Here is the inputs for ESRI's print service rest end url.
For 'Web Map as JSON':
---------------------------
{
   "mapOptions":{
      "extent":{
         "xmin":-13630255.86177027,
         "ymin":4547551.685206397,
         "xmax":-13621933.780315502,
         "ymax":4552080.579132413,
         "spatialReference":{
            "wkid":102100
         }
      },
      "scale":18055.954822
   },
   "operationalLayers":[
      {
         "url":"https://services.arcgisonline.com/ArcGIS/rest/services/NatGeo_World_Map/MapServer"
      },
      {
	 "id":"**myPointFtrs**",
         "url":"https://services.arcgis.com/V6ZHFr6zdgNZuVG0/ArcGIS/rest/services/SanFransiscoIncidents/FeatureServer/0"
      }
   ],
   "exportOptions":{
      "outputSize":[
         3300,
         2550
      ],
      "dpi":150
   },
   "layoutOptions":{
	"legendOptions":{
		"operationalLayers":[
			{
				"id":"myPointFtrs"
			}
		]
	}
   }
}

Format:
PDF

Layout Template:
A4 Landscape

Thanks and appreciate for your help.

**Comment by andygup** [comment]
Hi @vm-pa it looks like your first time opening a github issue. My recommendation is to open an issue over on the community site: https://community.esri.com/t5/arcgis-api-for-javascript-questions/bd-p/arcgis-api-for-javascript-questions. That is the best place for questions about print services including most questions about the ArcGIS JS API, and it will get high visibility.

**Comment by andygup** [comment]
Closing.
