### ISSUE TITLE
TypeScript 4.x issue with esri/request

### ISSUE THREAD

**Issue by fhissink** [Esri/jsapi-resources#44]
Hi,

Maybe I'm missing something but I get an error in the typings file for esri/request:

_ERROR in [at-loader] typings\globals\arcgis-js-api\index.d.ts:7181:12
    **'request' only refers to a type, but is being used as a namespace here.**_

All the rest works fine, so I think something is wrong with this typing?

**Comment by jgravois** [comment]
hi there @fhissink!

this will be fixed in 4.2. please check out the info in #43 to resolve the problem now.

**Comment by fhissink** [comment]
Thanks @jgravois!

Sorry for the repost.

(btw, nice work at the DevSummit in Berlin :))

**Comment by jgravois** [comment]
no worries! :honeybee:
