### ISSUE TITLE
IdentityManager

### ISSUE THREAD

**Issue by esride-stm** [Esri/jsapi-resources#45]
Importing the IdentityManager will not give code completion. The object seems not to be valid. The same with the IdentityManagerBase.
![image](https://cloud.githubusercontent.com/assets/6391134/21230217/840898b4-c2e4-11e6-85d4-5aa6d687a5a1.png)

**Comment by dasa** [comment]
Here's a workaround:

```ts
import IdentityManager = require("esri/IdentityManager");

const esriId: IdentityManager = <any> IdentityManager;
esriId.registerOAuthInfos([info]);
```

**Comment by esride-stm** [comment]
I don't understand what I do, but it works ;-) Thanks!
