### ISSUE TITLE
Accessor interface not updated with new handle methods

### ISSUE THREAD

**Issue by COV-GIS** [Esri/jsapi-resources#453]
Accessor `addHandles`, etc. didn't get added in 4.25 @arcgis/core `interface.d.ts` or here.

**Comment by andygup** [comment]
@COV-GIS we missed the window to add these to 4.25. However, you can verify that `addHandles()`, `removeHandles()` and `hasHandles()` are now available via `@arcgis/core@next` and `arcgis-js-api@next`. Thanks again, I'll close this out.
