### ISSUE TITLE
Change JavaScript API URL in custom widget deployment

### ISSUE THREAD

**Issue by LuisRguezEsriSpain** [Esri/jsapi-resources#455]
Hi,

I've developed a custom widget following the directions given in https://github.com/Esri/jsapi-resources/tree/main/esm-samples/jsapi-custom-widget.
 
After running "npm run-script build" on the  output location (**dist** directory), a lot of obfuscated java script files are generated. For a client I need to change the URL of the ArcGIS Java Script 4.25 to point to a local URL. Where can I change that URL?

Regards

**Comment by andygup** [comment]
Hi @LuisRguezEsriSpain we'll need more information, are you getting HTTP 404 errors when you deploy the application to your production webserver? If that's the case, you can find more information in the Vite documentation about setting the public base path: https://vitejs.dev/guide/build.html#public-base-path.

**Comment by andygup** [comment]
Closing for now. If new information comes available feel free to post.
