### ISSUE TITLE
Add globalIdField property to layer interfaces 

### ISSUE THREAD

**Issue by COV-GIS** [Esri/jsapi-resources#464]
Please consider adding `globalIdField` property to those layers' interfaces which have the property. Typing it would be as useful as the `objectIdField` property.

**Comment by andygup** [comment]
Hi @COV-GIS, we recommend opening an [Esri tech support issue](https://support.esri.com/en) for this enhancement or post on [ArcGIS Ideas](https://community.esri.com/t5/custom/page/page-id/arcgis-ideas).

Closing this out, issues opened here should be related to the esm samples in this repository.

**Comment by COV-GIS** [comment]
Sounds good @andygup. I had typescript issues and enhancements resolved through this repo in the past. I'll go through support from now on.
