### ISSUE TITLE
LayerList/LayerListViewModel not there yet?

### ISSUE THREAD

**Issue by AlainBaslter** [Esri/jsapi-resources#47]
I am using ESRI JS API 4.x in TypeScript (2.1). I'd like to use LayerListViewModel. 
It is announced and documented here as part of the 4.2 release
https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-LayerList-LayerListViewModel.html 

Yet I cannot find anything related to the LayerList widget in the .d.ts

Did it not make it in the latest 4.2 code update?

**Comment by dasa** [comment]
This is now fixed at: https://github.com/Esri/jsapi-resources/blob/master/4.x/typescript/arcgis-js-api.d.ts#L8068-L8071

Thank you for reporting this.
