### ISSUE TITLE
Map is not loading. 

### ISSUE THREAD

**Issue by rupalikombade** [Esri/jsapi-resources#476]
### IMPORTANT

- [X] My question is related to the samples and content within this repository. For all other issues, open a ticket with [Esri Technical Support](https://support.esri.com/) or post your question in the [community forum](https://community.esri.com/t5/arcgis-api-for-javascript/ct-p/arcgis-api-for-javascript).
- [X] I have [checked for existing issues](https://github.com/Esri/jsapi-resources/issues) to avoid duplicates. If someone has already opened an issue for what you are experiencing, please add a 👍 reaction and comment as necessary to the existing issue instead of creating a new one. You can also refer to this repo's [troubleshooting guide](../../TROUBLESHOOTING.md) for hints and suggestions.

### Actual behavior

I m using angular application. I am getting below error. This error coming in loop and map is not loading. please find below [screenshot]
Please let me know if I miss anything in code, I am referring code from https://github.com/Esri/jsapi-resources/blob/main/esm-samples/jsapi-angular-cli/src/app/app.component.ts 

![error](https://github.com/Esri/jsapi-resources/assets/67312928/5e7758f3-c80c-4ae1-abba-3aa08e3f90dd)

### Expected behavior

Map should be visible and error should not be there

### Reproduction sample

na

### Reproduction steps

npm install @arcgis/core
created component 
imported below modules
import Map from '@arcgis/core/Map';
import Config from '@arcgis/core/config';

import MapView from '@arcgis/core/views/MapView';
import Bookmarks from '@arcgis/core/widgets/Bookmarks';
import Expand from '@arcgis/core/widgets/Expand';

initilize webmap and mapview
 const webmap = new WebMap({
      basemap:"streets-vector"
    });

    const view = new MapView({
      container:'mapdiv',
      map: webmap
    });

### Reproduction browser

Chrome

### Operating System (check https://whatsmyos.com)

Windows

**Comment by andygup** [comment]
Closing, this issue should be posted to [community.esri.com](https://community.esri.com/t5/arcgis-javascript-maps-sdk-questions/bd-p/arcgis-api-for-javascript-questions) for better visibility on general usage questions.
