### ISSUE TITLE
MapView toScreen() issue

### ISSUE THREAD

**Issue by nickcam** [Esri/jsapi-resources#48]
Hi Guys,

I'm seeing some weird behavior using MapView toScreen() function in 4.2

It works fine on initial draw of a graphic, but when you pan the map all the way around the globe back to the point then the returned x value is way out.

See this plunk for an example: [https://plnkr.co/edit/OPQaau3ULeGlH469Jqpz](https://plnkr.co/edit/OPQaau3ULeGlH469Jqpz)

Hover over the graphic to see the toScreen values returned.

I've worked around it by adding this code to check if the map has been wrapped around using the worldScreenWidth property and adjusting the value, but I feel like toScreen should be returning the correct value all the time, regardless of whether the map has been wrapped around?

```
var sp = mapView.toScreen(<some web merc point>);
var wsw = mapView.state.worldScreenWidth;
//get a ratio to determine how many times the map has been wrapped around.
let ratio = parseInt((sp.x / wsw).toFixed(0)); 
if (sp.x < 0) {
   //x is less than 0. Adjust by the world screen width.
   sp.x += wsw * (ratio * -1);
}
else if (sp.x > wsw) {
   //x is too big, cater for it.
   sp.x -= wsw * (ratio);
}
```
This seems to work for web merc points,  using a geographic SR has a different set of issues I think.

Thanks,
Nick

**Comment by bsvensson** [comment]
Thanks for reporting this @nickcam . It's a bug with the JSAPI, even with the current version (4.5).
