### ISSUE TITLE
Issue with Editor Widget in Esri's JavaScript SDK version 4.27 with Angular

### ISSUE THREAD

**Issue by egonher** [Esri/jsapi-resources#481]
### IMPORTANT

- [X] My question is related to the samples and content within this repository. For all other issues, open a ticket with [Esri Technical Support](https://support.esri.com/) or post your question in the [community forum](https://community.esri.com/t5/arcgis-api-for-javascript/ct-p/arcgis-api-for-javascript).
- [X] I have [checked for existing issues](https://github.com/Esri/jsapi-resources/issues) to avoid duplicates. If someone has already opened an issue for what you are experiencing, please add a 👍 reaction and comment as necessary to the existing issue instead of creating a new one. You can also refer to this repo's [troubleshooting guide](../../TROUBLESHOOTING.md) for hints and suggestions.

### Actual behavior

Hello,

I'm encountering an issue with the Editor widget when using the example from Esri's repository at [jsapi-angular-cli](https://github.com/Esri/jsapi-resources/tree/main/esm-samples/jsapi-angular-cli) to set up an Angular application. When employing the version 4.27 of Esri's JavaScript SDK, I've noticed that the Editor widget does not update data, though it does allow for deletion. Importantly, this behavior is not replicated when using version 4.26 of the same SDK with an identical codebase.

**Actual Result:** 
The Editor widget does not update data but does allow for its deletion.

**Development Environment:**
- Angular 15 or 16 (same behaviour)
- Esri JavaScript SDK version 4.27

Note: Im using a esri arcgis online public webmap from this sample https://developers.arcgis.com/javascript/latest/sample-code/widgets-editor-basic/

Is there any workaround or recommendation to address this issue? Any assistance would be greatly appreciated.

Thank you in advance.

### Expected behavior

The Editor widget should allow data updates seamlessly, as observed with the SDK version 4.26.

### Reproduction sample

https://github.com/egonher/jsapi-resources-widget-editor-4.27-angular-test/tree/main/esm-samples/jsapi-angular-cli

### Reproduction steps

1. Clone the [jsapi-angular-cli] repository.
2. Set up the Angular application as indicated in the guide.
3. Configure the app to use version 4.27 of Esri's JavaScript SDK.
4. Launch the application and access the Editor widget.
5. Attempt to update existing data.

### Reproduction browser

 Chrome Versión 115.0.5790.171 (Build oficial) (64 bits)

### Operating System (check https://whatsmyos.com)

- OS:
    Windows 11, 64 Bit
- Device:
    Intel i7, 16GB Ram Laptop

**Comment by egonher** [comment]
I want to clarify that no event is captured in the browser dev console when you click the submit/update button.

**Comment by andygup** [comment]
@egonher can you reproduce this behavior outside of Angular in a [codepen](https://codepen.io/)? 

If this issue only occurs in Angular, then you'll need to provide a simple, working example from your personal github repo, StackBlitz, CodeSandbox or equivalent. Please refer to our troubleshooting document: https://github.com/Esri/jsapi-resources/blob/main/TROUBLESHOOTING.md#four-triage-steps

**Comment by egonher** [comment]
Thanks @andygup  for your quick response. Angular only. I have forked the repository and made some changes to reproduce the unexpected behavior. https://github.com/Esri/jsapi-resources/compare/main...egonher:jsapi-resources-widget-editor-4.27-angular-test:main

**Comment by andygup** [comment]
Thanks @egonher, I was able to reproduce the issue. We'll take a closer look.

**Comment by egonher** [comment]
I have discovered another unexpected behavior, in this case with the _calcite design system latest version_ (1.6.x). I hope this similar case can help guide the problem. 

**Expected behavior**
The Editor widget should allow data updates seamlessly, as observed with the calcite design system 1.2 version.

**Reproduction sample**
https://github.com/Esri/jsapi-resources/compare/main...egonher:jsapi-resources-widget-editor-4.27-angular-test:calcite-test

**Note**
The unexpected behavior with the widget editor is the same as the SDK´s issue. In this case the problem starts from version 1.3.

If you prefer that there will be a new issue, please let me know.

**Comment by andygup** [comment]
> If you prefer that there will be a new issue, please let me know.

@egonher yes, please open an issue in the calcite repo: https://github.com/Esri/calcite-components-examples/issues. When you are done, leave a link to the issue here. I'll let the calcite team know I'm referring you.

**Comment by egonher** [comment]
Ok @andygup  I opened it, https://github.com/Esri/calcite-components-examples/issues/263

**Comment by andygup** [comment]
[like]  Andy Gup reacted to your message:
________________________________

**Comment by andygup** [comment]
@egonher for the Editor widget issue, we found a workaround by disabling specific monkey patching zone.js using `window.__zone_symbol__UNPATCHED_EVENTS = ['click'];`. Can you give that a try?

Here's the Angular doc on how to do that: https://angular.io/guide/zone#setting-up-zonejs

**Comment by andygup** [comment]
It's possible this is a bug in Angular. We will do some more investigating to see if we can isolate the issue.

**Comment by andygup** [comment]
@egonher check out the diff screenshot below for a list of the changes you'll need to make. Notably, your `zone-flags.ts` file should be JavaScript: `zone-flags.js`. If you are using the latest version of Angular (e.g. v16), `polyfills.js` is automatically created during the build, and you may not need to manually create that file. And you'll need to update angular.json to include `zone-flags.js` as a polyfill, in addition to `zone.js`. This approach is working on our end.

<img width="462" alt="image" src="https://github.com/Esri/jsapi-resources/assets/510440/a1fe1b8e-80b7-4619-9b22-c700eb39674d">

**Comment by andygup** [comment]
@egonher thanks for reporting, after further analysis we believe this is a regression in Calcite. I've opened a new issue on the Calcite repo that we'll be tracking: https://github.com/Esri/calcite-design-system/issues/7729.

**Comment by egonher** [comment]
Thank you very much @andygup  for the support, to those who develop with this popular framework. The workaround you suggested works. I close this issue and I will continue to pay attention to the new one in calcite repository.
