### ISSUE TITLE
MapView hitTest() in IE11 and Edge

### ISSUE THREAD

**Issue by nickcam** [Esri/jsapi-resources#55]
Hi Guys,

I hate IE & Edge as much as anyone - but unfortunately people still use them :(.
It looks like MapView hitTest() isn't returning any results for those browsers when it should be.

You can see it not working in this sample - 
https://developers.arcgis.com/javascript/latest/sample-code/sandbox/index.html?sample=view-hittest

Could be something to do with element ordering, because if I set the z-index of the created layerView's container element to 1 hitTest picks up results...doing this obviously introduces other problems though.
Thanks.

**Comment by hgonzago** [comment]
Hi Nick, we are aware of this bug and have it logged in our system. Will hopefully have it addressed in the near future.

Thanks for letting us know.

**Comment by nickcam** [comment]
I thought you'd be across it already :). Thanks for the info!

**Comment by nickcam** [comment]
Hi @hgonzago, 

Is there a public list of known issues that can be referred to? Might save some spam issues ending up here and would certainly help knowing of any up front from a development perspective.

Thanks,
Nick

**Comment by hgonzago** [comment]
Hi Nick, unfortunately we do not have anything specific out there on this. It is a relatively new bug that we found (a little too late). We most definitely will have it addressed by next release. Sorry for any confusion or inconvenience.

**Comment by nickcam** [comment]
No worries @hgonzago, I understand bugs creep in, it's just part of life :). It would be super cool to have a dynamic list of all known bugs (updated every now and then) for each release that we could refer to as well though. Just a general outline of the problem so we know it exists. Certainly not anything to the level of detail that your internal bug tracking would contain.
