### ISSUE TITLE
Error when loading TemplatePicker using requriejs

### ISSUE THREAD

**Issue by WangJi** [Esri/jsapi-resources#56]
**Version:3.19**

-------------

Gives an error: 'dojo' not found.
Module Tree is:
```
      esri/dijit/editing/TemplatePicker
        dojox/grid/DataGrid
          dojox/grid/_Grid
            dojox/grid/_Layout
              dojox/grid/_RowSelector
                dojox/grid/_View
```

--------------

is it necessary that `dojox/grid/_View.js` has `dojo` as its dependency?

**Comment by odoe** [comment]
I'm still looking into this one, no quick solution yet, but I'll keep you updated.

**Comment by odoe** [comment]
Ok, this can be fixed by adding a `packages` object to the `requirejs:single` option in the Gruntfile.

```js
          packages: [
              'dojo',
              'dijit',
              'dojox',
              'dgrid',
              'dgrid1',
              'xstyle',
              'esri'
          ],
```

We'll update this with the next update for this repo.

**Comment by WangJi** [comment]
My previous hack was to delete that `dojo` dependency in `_View.js` and it worked fine.
While your solution is a more general one eliminating the same error that may potentially exist in any other files.
Glad we can finally close this.
