### ISSUE TITLE
Module "Has no default export"

### ISSUE THREAD

**Issue by dorianboulch** [Esri/jsapi-resources#57]
Hello,

I'm trying to import different objects in an angular 2 app.
To do so, I write this :
`import FeatureLayer from 'esri/layers/FeatureLayer';`

My IDE tells me Module  'esri/layers/FeatureLayer' Has no default export

Should the application has default export ? Maybe I'm using it wrongly...

**Comment by dasa** [comment]
Please see discussion at #37
