### ISSUE TITLE
MapView hitTest on TextSymbols

### ISSUE THREAD

**Issue by nickcam** [Esri/jsapi-resources#59]
Hi Guys,

Not sure if this by design or not, but hitTest() on MapView isn't picking up graphics that are symbolized using TextSymbols.

See this plunk: [https://plnkr.co/edit/WRi5xfMJFKiRITqRqy6q](https://plnkr.co/edit/WRi5xfMJFKiRITqRqy6q)
The standard SimpleMarkerSymbol no problems, but the two text graphics...no joy.

Can get around it in Chrome by setting `pointer-events="bounding-box"` on the `<text>` element. But this is only supported in Chrome it seems. I realize IE/Edge won't work as well.

Thanks,
Nick

**Comment by ycabon** [comment]
Hi Nick,
I will take a look at it for 4.3.
Thanks!

**Comment by ycabon** [comment]
closing, fixed in 4.3

**Comment by nickcam** [comment]
Awesome, thanks mate!

**Comment by ycabon** [comment]
@nickcam do you have an email for a couple of questions?

**Comment by nickcam** [comment]
Yep no worries - ncameron@outlook.com.au
