### ISSUE TITLE
More docs on using types for 3.x and 4.x?

### ISSUE THREAD

**Issue by jwasilgeo** [Esri/jsapi-resources#60]
Can someone explain to me (or just set me straight) why the typings for JSAPI 3.x aren't using a `namespace`?

For example, I see in the 4.x typings that it _does_ explicitly list the [`__esri` namespace](https://github.com/Esri/jsapi-resources/blob/master/4.x/typescript/arcgis-js-api.d.ts#L32).

This question stems from an issue conversation over in 
[angular2-esri-loader](https://github.com/tomwayson/angular2-esri-loader/issues/2), where I am working with JSAPI 3.19 for an Angular2+TypeScript2 demo app.  I installed the types with `npm install @types/arcgis-js-api@3.19.0`, but my VSCode claims it doesn't know anything about the `__esri` namespace.  I poked around and only found "`__esri`" in the 4.x typings.

Is there something else I need to do (in addition to making sure arcgis-js-api typings are/n't excluded in my project's **tsconfig.json**)?

Does the 3.x **arcgis-js-api.d.ts** file need to have this namespace declaration, too?

Thanks!

**Comment by jwasilgeo** [comment]
PS: For reference, please see:

- https://github.com/jwasilgeo/angular2-webpack-starter/commit/67e525ca7f47cdad188092f6fd2a49c277e802b2#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

- https://github.com/jwasilgeo/angular2-webpack-starter/commit/67e525ca7f47cdad188092f6fd2a49c277e802b2#diff-dfb6ed26e7d937014a0dc028762de580R26

**Comment by dasa** [comment]
The 3.x typings have the interfaces in the `esri` module. This way the global namespace isn't polluted and you can call it whatever you'd like. See:
https://github.com/Esri/jsapi-resources/blob/master/3.x/typescript/demo/MapController.ts#L3
https://github.com/Esri/jsapi-resources/blob/master/3.x/typescript/demo/MapController.ts#L19

**Comment by jwasilgeo** [comment]
@dasa thank you for pointing that out.

With @tomwayson's `angular2-esri-loader` I suppose we are trying to avoid having to rely on the `import  xyz = require(...);` syntax since the `angular2-esri-loader` is already imported and used as the mechanism for [loading](https://github.com/jwasilgeo/angular2-webpack-starter/commit/67e525ca7f47cdad188092f6fd2a49c277e802b2#diff-dfb6ed26e7d937014a0dc028762de580R41) specific JSAPI modules.  With some additional experimenting, we've found that TS2 + Webpack within an Angular2 app also starts to do some complaining with 3.x when we tried out the style you pointed out above.

Even though there would be global namespace pollution, is there any possibility in having something similar to the 4.x types' `__esri` namespace being added to 3.20+?  Thanks!

**Comment by dasa** [comment]
Have you tried only using the syntax for this one line? There's only interfaces in the "esri" module so this isn't in the JS code.

`import esri = require("esri");`

You may also be able to use import from syntax to access these interfaces like this:

`import * as esri from "esri";`

**Comment by jwasilgeo** [comment]
Yes, trying either of those lines allows for type support, but only "1 level deep". For example, I can begin typing out `esri.Map` to only get VSCode code completion that includes options such as MapOptions, MapImageOptions, etc.

VSCode will indicate to me that "[ts] Namespace '"esri"' has no exported member 'Map'."

**Comment by dasa** [comment]
Right, "esri" mostly just has the constructor options. To get the typing for the "esri/map" module, you still have to import it.

**Comment by dasa** [comment]
@jwasilgeo - let me know if you have any more questions on this.

**Comment by jwasilgeo** [comment]
Thanks @dasa!
