### ISSUE TITLE
Problem wrapping an Esri class with Typescript

### ISSUE THREAD

**Issue by crain9412** [Esri/jsapi-resources#61]
I'm having issues creating a simple wrapper for a map using typescript.

The relevant code is

```
import Map = require("esri/Map");

export class MapWrapper extends Map {
  constructor(basemap: string) {
    super({
      basemap: basemap
    });

    console.log("Created map with basemap " + basemap);
  }
}
```

This gives me a `Uncaught TypeError: Cannot read property 'basemap' of undefined`.

Any ideas?

**Comment by dasa** [comment]
Which version of the API are you using?

**Comment by crain9412** [comment]
4.2

**Comment by dasa** [comment]
I'm not able to reproduce that error. I put your code in a file called `test.ts` and compiled it using TypeScript 2.2 using `tsc -m amd -t es5 test.ts` and then copied the output to this jsbin and it seems to run fine: https://jsbin.com/jeneribuco/edit?html,output

**Comment by crain9412** [comment]
Adding the `-m amd -t es5` parameters to my tsc scripts solved the issue. 

Thanks!
