### ISSUE TITLE
how to delete VectorTileLayerImpl and IdentityManager  when building Project

### ISSUE THREAD

**Issue by aifang** [Esri/jsapi-resources#62]
I don't need the  VectorTileLayerImpl.js  and IdentityManager.js , then delete them in build.profile.js 。
my build.profile.js like this，but it still loaded in my app.

  **layers: {
       "dojo/dojo": {
      boot: true,
      customBase: true,
      // just like 3.17 
      include: [
        "app/main",
        "dojox/gfx/path",
        "dojox/gfx/svg",
        "dojox/gfx/filters",
        "dojox/gfx/svgext",
        "dojox/gfx/shape",
      ],
      includeLocales: ["en-us"]
    }
  }**

![pg qynh6gs9_2r3b32 chr](https://cloud.githubusercontent.com/assets/7665212/23396413/b9b81a14-fdce-11e6-9b97-cd94061e1288.png)

**Comment by dasa** [comment]
VectorTileLayerImpl is a static dependency, so it's still best to create a VectorTileLayerImpl build layer like this:
https://github.com/Esri/jsapi-resources/blob/master/3.x/bower/dojo/build.profile.js#L111-L116

**Comment by aifang** [comment]
Thanks you, I found  **esri/_coremap**  dependency  **layers/VectorTileLayer**,it means I can not delete VectorTileLayer from  my build.profile.js.  but VectorTileLayerImpl.js  is 234 KB, a big size of js, That I never use !
