### ISSUE TITLE
I get error by the method，please help me

### ISSUE THREAD

**Issue by 275890068** [Esri/jsapi-resources#66]
I am write at here 🥇 

        require.config({
            //baseUrl:url , //gisHome是全局变量，在testAll.js中判断用户是否创建
            map: {
                '*': {
                    css: url+'oss_core/gis/core/js/css.js'
                }
            },
            
    	    packages: [
    	    'myModules',{
    	        "name": "myModules",
    	        "location": url + "oss_map/gis/core/platform/arcgis/ext"
    	    },
    	    'esri',{
    	    	name:'esri',
    	    	location:url+'oss_map/gis/core/platform/arcgis/library/3.13/esri'
    	    } ,
    	    'dojo',{
    	    	name:'dojo',
    	    	location:url+'oss_map/gis/core/platform/arcgis/library/3.13/dojo'
    	    },
       	    'dojox',{
    	    	name:'dojox',
    	    	location:url+'oss_map/gis/core/platform/arcgis/library/3.13/dojox'
    	    },
    	    'dijit',{
    	    	name:'dijit',
    	    	location:url+'oss_map/gis/core/platform/arcgis/library/3.13/dijit'
    	    },
.....
but brower get error:

10.45.50.45:8040/oss/oss_map/gis/core/platform/arcgis/library/3.13/dojo/_base/loader.js:10 Uncaught TypeError: h.initSyncLoader is not a function
    at Object.<anonymous> (10.45.50.45:8040/oss/oss_map/gis/core/platform/arcgis/library/3.13/dojo/_base/loader.js:10)
    at Object.execCb (require.js:1696)
    at Module.check (require.js:883)
    at Module.<anonymous> (require.js:1139)
    at require.js:134
    at require.js:1189
    at each (require.js:59)
    at Module.emit (require.js:1188)
    at Module.check (require.js:938)
    at Module.enable (require.js:1176)

**Comment by bsvensson** [comment]
Hi @275890068 - sorry about the long response time.  If you still have this issue, could you try with the latest version of the API (3.30 instead of 3.13)?
