### ISSUE TITLE
TypeScript definition for InfoWindowLite in 3.* api is incorrect

### ISSUE THREAD

**Issue by TwitchBronBron** [Esri/jsapi-resources#68]
Based on this sample https://developers.arcgis.com/javascript/3/jssamples/widget_infowindow.html (and my own experience), I believe that the InfoWindowLite constructor for the 3.* typescript definitions are incorrect. I'm not positive what they should be, but it appears that the InfoWindowLite actually takes 2 parameters. 

I'm pretty sure it's incorrect in the typescript definitions because it's also incorrect on the api documentation page: https://developers.arcgis.com/javascript/3/jsapi/infowindowlite-amd.html

**Comment by dasa** [comment]
Thanks for the report. This is now fixed in 3.22.
