### ISSUE TITLE
Search Widget "Invalid regular expression" error

### ISSUE THREAD

**Issue by shenningsgard** [Esri/jsapi-resources#69]
The Search Widget appears to use regex in some capacity, which crashes if passed-in an invalid string after search suggestions have appeared. As an example, type in an opening bracket "[". This will crash the widget.

I believe it is the lack of a closing right bracket which causes this error. The Widget can not recover from this error.

**Comment by jgravois** [comment]
i can definitely repro the console error you describe in our live [sample](https://developers.arcgis.com/javascript/latest/sample-code/widgets-search-3d/index.html). thanks for reporting!

**Comment by bsvensson** [comment]
Thanks for reporting. This will be fixed for the next release.
