### ISSUE TITLE
Color definitions do not match the API documentation

### ISSUE THREAD

**Issue by charlie-elverson** [Esri/jsapi-resources#74]
new Color(...) is not recognized as a contructor, and Color.fromArray() only accepts number, not number[]

Using an array to set the color of a SimpleFillSymbol doesn't work either.

**Comment by dasa** [comment]
Which version of the API are you testing?

**Comment by charlie-elverson** [comment]
sorry.

4.3.1. developing an Angular app.

**Comment by dasa** [comment]
> new Color(...) is not recognized as a contructor

Can you double-check that you've imported it?

> Color.fromArray() only accepts number, not number[]

OK, I see that error here: https://developers.arcgis.com/javascript/latest/api-reference/esri-Color.html#fromArray

It'll be fixed in the next release.

**Comment by charlie-elverson** [comment]
yes. It's being imported in the same way as all my other ESRI dependencies

`import * as Color from 'esri/Color';`

I've tried creating the color in the constructor for the SimpleFillSymbol 
`        let highlightSymbol = new SimpleFillSymbol({
            color: new Color("#FF0000"), //this.highlightColor,
            style: "solid"
        });`

as well as by itself
`private highlightColor = new Color([0,0,255,0.5]);`

**Comment by jgravois** [comment]
@charlie-elverson are you able to take advantage of autocasting?

```js
var lineSymbol = new SimpleLineSymbol({
    color: [226, 119, 40],  // or '#bada55' or 'black'...
    width: 4
});
```
([live sample](https://developers.arcgis.com/javascript/latest/sample-code/get-started-graphics/index.html))

**Comment by charlie-elverson** [comment]
That was the first thing I tried. From what I can see in the docs, autocasting works with SimpleLineSymbol but not SimpleFillSymbol.

https://developers.arcgis.com/javascript/latest/api-reference/esri-symbols-SimpleLineSymbol.html#color

https://developers.arcgis.com/javascript/latest/api-reference/esri-symbols-SimpleFillSymbol.html#color

**Comment by jgravois** [comment]
i'm not sure what you mean. the API reference page you shared for `SimpleFillSymbol` explicitly mentions that color can be autocast and the live sample I shared previously takes advantage of that technique.

Get started with graphics
https://developers.arcgis.com/javascript/latest/sample-code/get-started-graphics/index.html

```
var fillSymbol = new SimpleFillSymbol({
  color: [227, 139, 79, 0.8],
  outline: { // autocasts as new SimpleLineSymbol()
    color: [255, 255, 255],
    width: 1
  }
});
```

**Comment by charlie-elverson** [comment]
Yes, the description includes it, but the property labels (the top line of the property's description), which I think is generated from the code, don't include "autocast" in the list, only "color". That makes me think that, for some reason, autocasting is not actually implemented on SimpleFillSymbol. Perhaps I'm mistaken on this part.

I just tried switching this to be a SimpleLineSymbol instead, and autocasting is still not working. It worked previously, so I'm wondering if this is actually tied to my switch from SystemJS to WebPack.

Still, I'm confused why I can't use new Color(...), when that syntax works fine with everything else I've used.

**Comment by dasa** [comment]
- autocast: There is a missing tag in the doc. Thanks for reporting it. It'll be fixed in the next release. In general though it's difficult to use the autocast feature in TypeScript since the properties are typed for the setter, not the getter. You can workaround this if you'd like by using type assertion. e.g., `fillSymbol.color = [227, 139, 79, 0.8] as any as Color;`
- constructor: What is the error you're getting?

**Comment by charlie-elverson** [comment]
1) Thanks for that workaround. asserting to any before color did the trick.

2) The error is simply "Color is not a constructor". Code compiles fine, but the browser complains.

error: 
`core.es5.js:1084 ERROR Error: Uncaught (in promise): TypeError: Color is not a constructor
TypeError: Color is not a constructor  ...`

The service that makes this call looks a bit like this:
`
import * as Color from 'esri/Color';
import * as Extent from 'esri/geometry/Extent';
import * as FeatureSet from "esri/tasks/support/FeatureSet";
import * as Query from 'esri/tasks/support/Query';
import * as QueryTask from 'esri/tasks/QueryTask';
import * as SimpleFillSymbol from "esri/symbols/SimpleFillSymbol";

@Injectable()
export class RoomsService {

    private highlightSymbol = new SimpleFillSymbol({
        // color: this.highlightColor,
        color: new Color([10, 10, 200, 0.5]),
        // color: [10,10,200,0.5] as any as Color,
        style: "solid"
    });
`

**Comment by dasa** [comment]
Can you try this syntax instead?

`import Color = require("esri/Color");`

**Comment by charlie-elverson** [comment]
I'm now having trouble duplicating the original issue, actually. I'm at a loss as to why, but it does make me think the problem was related to an incremental build problem or something else external to the API. I'll close the issue. Thanks again for your help.

**Comment by jgravois** [comment]
glad to hear you're sorted. thanks for pointing out the (minor) doc issues.
