### ISSUE TITLE
Typings for basemap not matching actual javascript

### ISSUE THREAD

**Issue by trockefeller** [Esri/jsapi-resources#77]
I am using types from "https://registry.npmjs.org/@types/arcgis-js-api/-/arcgis-js-api-4.3.1.tgz"

and I'm installing bower package "esri": "arcgis-js-api#4.3.0

I am importing "esri/Map" and trying to create a new map.

    let map = new Map( {
        basemap: 'streets' // [ts] Argument of type '{ basemap: string; }' is not assignable to parameter of type 'MapProperties'. Types of property 'basemap' are incompatible. Type 'string' has no properties in common with type 'BasemapProperties'.
    });

    let map = new Map( {
        basemap: { baseLayers: ['streets'] } //transpiles without error, but does not work at runtime.
    });

    let map = new Map( {
        basemap: { id: 'streets' } //transpiles without error, but does not work at runtime.
    });

The first attempt at creating a map matches the examples given here https://developers.arcgis.com/javascript/latest/sample-code/get-started-mapview/index.html , but it gives the typescript error shown in comments

The next two attempts are just wild guesses as to how it should be set up according to the typescript typings. Both of the attempts are transpiled with typescript without complaint, but they just don't work at runtime in the browser.

If I ignore the typescript error, the first code example does work at runtime in the browser.

Am I creating maps incorrectly using typescript? are the typings wrong? (seems somewhat unlikely since it looks like it has been this way since the typings were changed for 4.x). What's going on here? Thanks for any guidance.

**Comment by dasa** [comment]
The typings reflect the actual types you get when you read the properties. e.g., https://developers.arcgis.com/javascript/latest/api-reference/esri-Map.html#basemap

This makes it more difficult to use "autocasting" but simple to use when you read the properties. TypeScript doesn't support a different type for the setter vs. the getter.

You can workaround this like this:

```ts
let map = new Map();
map.basemap = "streets" as any as Basemap;
```

**Comment by trockefeller** [comment]
Thank you for the quick reply. I found a workaround just before you posted this that I think I like a little better

    import * as Map from 'esri/Map';
    import * as Basemap from 'esri/Basemap';
    
    let map = new Map({
        basemap: Basemap.fromId('streets')
    });

**Comment by jkieboom** [comment]
Note that in the future, we are probably going to manage allowing autocast behavior at least in the constructor.

**Comment by gavinr** [comment]
@dasa I'm having a similar problem with the sample file `MapView` code: https://github.com/Esri/jsapi-resources/blob/master/4.x/typescript/demo/app/main.ts#L8-L13

```
app/main.ts(8,26): error TS2345: Argument of type '{ map: Map; container: string; center: number[]; zoom: number; }' is not assignable to parameter of type 'MapViewProperties'.
  Types of property 'center' are incompatible.
    Type 'number[]' has no properties in common with type 'PointProperties'.
```

The workaround I found was to follow your pattern above, by setting the center after the fact, like this:
https://github.com/Esri/jsapi-resources/compare/master...gavinr:gavinr-patch-1

... is this the correct solution right now?

**Comment by dasa** [comment]
Yes, but it can be done in the constructor also.

**Comment by jkieboom** [comment]
We are looking at a solution for generating better constructor typings for auto-casted properties like the map basemap for 4.5.

**Comment by Abexdatl** [comment]
I was using 4.4 version with typescript and everything was fine except now I am getting 

'{ map: Map; container: any; center: number[]; zoom: number; }' is not assignable to parameter of type 'MapViewProperties'.
  Types of property 'center' are incompatible.
    Type 'number[]' has no properties in common with type 'PointProperties'.

'{ basemap: string; layers: MapImageLayer[]; }' is not assignable to parameter of type 'MapProperties'.
  Types of property 'basemap' are incompatible.
    Type 'string' has no properties in common with type 'BasemapProperties'.

what got changed  .... esri ? 
why do a breaking change after a given version is released ... ?

**Comment by dasa** [comment]
The 4.4 version of the definition file hasn't changed since it was released.
https://github.com/Esri/jsapi-resources/commits/master/4.x/typescript/arcgis-js-api.d.ts

Try the workaround show here:
https://github.com/Esri/jsapi-resources/blob/master/4.x/typescript/demo/app/main.ts#L7

Or something similar to: `center: myCenter as any`

**Comment by Abexdatl** [comment]
Ok. That works ... hopefully it gets better in 4.5 . When do you think 4.5 come out ? I was told during the dev conf in march that "all" of 3.x functionalities will be available in 4.X before the end of the year :)

**Comment by bsvensson** [comment]
Version 4.5 was released in September - https://blogs.esri.com/esri/arcgis/2017/09/29/arcgis-api-for-javascript-version-4-5-released/.
