### ISSUE TITLE
Type checking in Typescript 2.4 breaks valid object properties

### ISSUE THREAD

**Issue by jeff-tenhave** [Esri/jsapi-resources#81]
Stricter type checking on weak types in [typescript 2.4](https://blogs.msdn.microsoft.com/typescript/2017/06/27/announcing-typescript-2-4/)  prevents defining some object properties with basic types. 

Example. The following works correctly for setting MapView center in typescript 2.3, but results in a  compile error in typescript 2.4
```
const view = new MapView({
        ...
        center: [-73.950, 40.702],
        ...
    });
```

Another example is properties that contain a spatial reference. The following compiles in 2.3, but not in 2.4:
```
const extent = new Extent({
            ...
            spatialReference: 102100
     });
```

**Comment by dasa** [comment]
I don't think this is new in TS 2.4. See #77.

**Comment by dasa** [comment]
Duplicates #77
