### ISSUE TITLE
Incorrect TypeScript definition for "StreamLayerConstructor" [4.4]

### ISSUE THREAD

**Issue by shenningsgard** [Esri/jsapi-resources#83]
According to the TypeScript definitions, calling `new StreamLayer()` should return a new StreamLayerView. This must be incorrect, as all other layers' constructors return an instance of themselves.

From line ~3718 of the TypeScript definitions:
`
interface StreamLayerConstructor {
    new(properties?: StreamLayerProperties): StreamLayerView;

    fromJSON(json: any): StreamLayerView;
  }
`

**Comment by dasa** [comment]
I'm not seeing that at: https://github.com/Esri/jsapi-resources/blob/master/4.x/typescript/arcgis-js-api.d.ts?utf8=✓#L3716-L3720

**Comment by shenningsgard** [comment]
Hmm, that's odd. I'm guessing I botched a refactor then; closing this with my tail between my legs now ;)
