### ISSUE TITLE
Property "emit" is missing from Evented class in TypeScript definition [4.4]

### ISSUE THREAD

**Issue by shenningsgard** [Esri/jsapi-resources#84]
Although Evented inherits from dojo.Evented under the hood, the 'emit' function is missing from the TypeScript definitions. As a result, a developer may no longer create and consume custom events on objects which extend Evented (ex. Widget).

**Comment by jkieboom** [comment]
The main reason for this is that we don't want to expose `emit` as a public method (you should not be able to emit events externally to an object), and we currently don't have the ability to generate type definitions for `protected` members.

A simple workaround at the moment is to override the type definition like so (note that you can do this separately from the `arcgis-js-api.d.ts`):

```ts
declare namespace __esri {
  interface Evented {
    emit(type: string, event: any): IHandle;
  }
}
```

**Comment by shenningsgard** [comment]
Thanks for the workaround! If the publish/subscribe pattern is so discouraged, how would you recommend managing inter-widget communication?

**Comment by odoe** [comment]
We haven't standardized inter-widget comm just yet, but some current implementations is Extending Accessor to act as a Store between widgets/viewmodels. So property watching becomes the comm.

**Comment by jkieboom** [comment]
Maybe I was not really clear, I didn't mean that we do not want people to use events, what I meant is that we prefer not to allow users the following:

```ts
const obj = new SomeWidget();
obj.emit("some-event");
```

Emitting events should be only possible from within an implementation, hence we do not want `emit` as a public API. What I'd like to do is to expose `emit` as a `protected` method of `Evented` for 4.5.

**Comment by jkieboom** [comment]
We just merged changes that make `emit` appear as a `protected` method of `Evented` in the upcoming 4.5 typings. @shenningsgard will this cover your uses of `emit`?

**Comment by shenningsgard** [comment]
@jkieboom - assuming this will allow me to extend Evented and call "emit()" from within the class, that should work just fine!

**Comment by jkieboom** [comment]
Should work fine. Closing this, please feel free to reopen if you still encounter problems in 4.5 when it is released.
