### ISSUE TITLE
"geometry" object in "StreamLayerViewDataReceivedEvent" is not Esri Geometry [4.4]

### ISSUE THREAD

**Issue by shenningsgard** [Esri/jsapi-resources#85]
The "geometry" object contained in a StreamLayer update ("StreamLayerViewDataReceivedEvent") is a generic object, not actually an Esri "Geometry" object. If desired, it can of course be passed into a constructor for a new Geometry object, but as the "target" property contains a valid "esri.layers.graphics.controllers.StreamController" (which itself contains valid references to Layer and LayerView objects), I would think it would make more sense for the "geometry" property to be a proper Esri Geometry object.

**Comment by jcardonadcdev** [comment]
The `data-received` event of the `StreamLayer` is meant to be a generic object containing the raw JSON received from the Stream Service. It is there to allow a developer to intercept the message and do some kind of processing. The message is not always going to contain a geometry or have the standard properties of a feature, *attributes*, and *geometry*.  For instance when a filter is set on the Stream Service, a message gets sent that contains a `filter`  property and an `error` property. 

If an Esri "Geometry" object is needed and a `geometry` property is in the message, the JSON can be used to construct the geometry.  Alternatively,  an event handler can be added  for  the  `change` event of the [`StreamLayerView.graphics`](https://developers.arcgis.com/javascript/latest/api-reference/esri-views-layers-StreamLayerView.html#graphics) property. Geometries can be accessed from the graphics in the `added` property of the event.

```ts
view.graphics.on("change", (evt) => {
  const added = evt.added;
  
  for (let item of added) {
    const g = item.geoemetry;

   //do something with the geometry
  }
}
```

**Comment by bsvensson** [comment]
Closing - based on the answer/comment above from @jcardonadcdev
