### ISSUE TITLE
TypeScript definition for StreamLayerView doesn't include "layer" property [4.4]

### ISSUE THREAD

**Issue by shenningsgard** [Esri/jsapi-resources#86]
Although under the hood, StreamLayerView includes "esri.views.layers.LayerView" in its inheritance chain (and thus includes [and populates] its "layer" field (as well as the others inherited from LayerView), its inheritance chain is not reflected in the TypeScript definitions (or in the online documentation). As such, it is not possible to reference the associated StreamLayer in a TypeScript project.

**Comment by shenningsgard** [comment]
StreamLayer is also missing the "source" (and, by extension, "latestUrl") fields, for the same reason.

**Comment by shenningsgard** [comment]
It's also missing the "trackIdField" property

**Comment by dasa** [comment]
`StreamLayerView` was updated to extend `LayerView` at 4.5.
