### ISSUE TITLE
Wrong query library name in the sample

### ISSUE THREAD

**Issue by Vikash2402** [Esri/jsapi-resources#9]
Hi Mr. Paddock,
I found a wrong query library name in the sample of queryCount in  ArcGIS JS 3.12 api; instead it should be "esri/tasks/query".

Please refer below mentioned snapshot and URL for more details.

![query issue](https://cloud.githubusercontent.com/assets/7596498/5563948/920d9658-8ec5-11e4-95df-da7e6ff57455.PNG)

URL : https://developers.arcgis.com/javascript/jsapi/featurelayer-amd.html#querycount

Thank you.

**Comment by dasa** [comment]
Fixed
