### ISSUE TITLE
dojoConfig path error

### ISSUE THREAD

**Issue by AugustusZ** [Esri/jsapi-resources#91]
https://github.com/Esri/jsapi-resources/blob/24d24c7c67fd5aee1668dd090a0a83e9bca598c6/4.x/typescript/demo/index.html#L18

Should it be 

```
var locationPath = location.pathname.replace(/\/[^\/]+$/, "/");
```
?

**Comment by odoe** [comment]
I can add this in next release, I'll make a note. It won't hurt, I think it varies depending on server/browser, it's bit me before.

**Comment by odoe** [comment]
This should be fixed now!
