### ISSUE TITLE
QueryTaskOptions interface options not showing 'source' option

### ISSUE THREAD

**Issue by TwitchBronBron** [Esri/jsapi-resources#93]
The QueryTaskOptions interface does not show all available options. You can see in the documentation  [here](https://developers.arcgis.com/javascript/3/jsapi/querytask-amd.html#querytask1) and also the typescript definition [here](https://github.com/Esri/jsapi-resources/blob/362e88c8c4ef294d9240e1c54b5792694efab51f/3.x/typescript/arcgis-js-api.d.ts#L1832) `  export interface QueryTaskOptions {
    /** Specify the geodatabase version to display. */
    gdbVersion?: string;
  }` that the only property of QueryTaskOptions is gdbVersion. However, when inspecting the source code [here](https://github.com/Esri/arcgis-js-api/blob/master/tasks/QueryTask.js), you can see that there is another property called 'source'. `this.source=r&&r.source`

**Comment by dasa** [comment]
Fixed at 3.23 in commit: 819e5c8be36c98b35d64cf8773c4c59598b8b291
