### ISSUE TITLE
SuggestionResult not declared as module

### ISSUE THREAD

**Issue by hschott** [Esri/jsapi-resources#94]
With version 4.5 many new types where introduced.
I'm missing SuggestionResult returned as Promise from suggestLocations(params, options) as declared module.

**Comment by jkieboom** [comment]
`SuggestionResult` is not a physical module, it's only an interface (see https://github.com/Esri/jsapi-resources/blob/master/4.x/typescript/arcgis-js-api.d.ts#L5937-L5940). To use such a type in your own code, you can use the following:

```ts
import esri = __esri;

// You can now refer to any type from the esri namespace
function processResult(result: esri.SuggestionResult) {
}

// Note that this namespace contains type interfaces only, to instantiate types you still need to actually import the correct module
```
