### ISSUE TITLE
[v4.5] Typings - PopupTemplate - actions

### ISSUE THREAD

**Issue by nickcam** [Esri/jsapi-resources#95]
Hi Guys,

It seems the actions property on PopupTemplates are typed as:
` Collection<Collection<Action>> `

Should this just be?
` Collection<Action> `

Thanks!

**Comment by jkieboom** [comment]
Looks like a documentation issue: https://developers.arcgis.com/javascript/latest/api-reference/esri-PopupTemplate.html#actions. /cc @bsvensson

**Comment by ekenes** [comment]
It looks like this was confused with [ListItem.actionsSections](https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-LayerList-ListItem.html#actionsSections). We'll fix this for the next doc update.

**Comment by nickcam** [comment]
Ok great, thanks. Is the npm typings file generated from your docs (or vice versa) and will therefore also be updated?

**Comment by jkieboom** [comment]
> Ok great, thanks. Is the npm typings file generated from your docs (or vice versa) and will therefore also be updated?

Indeed.

**Comment by nickcam** [comment]
Awesome, thanks again!

**Comment by bsvensson** [comment]
https://developers.arcgis.com/javascript/latest/api-reference/esri-PopupTemplate.html#actions was updated to show `actions    Collection<Action>`.
