### ISSUE TITLE
Module '"esri/core/Collection"' resolves to a non-module entity and cannot be imported using this construct.

### ISSUE THREAD

**Issue by tonicfx** [Esri/jsapi-resources#97]
Hi, I update my project with the latest API version 4.5.0 like this : 

```
"arcgis-js-api": "4.5.0",
"@types/arcgis-js-api": "4.5.0"

```
After npm install, when I try to compile my project, I have this error with at-loader :

```
[at-loader] Checking started in a separate process...
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
Module '"esri/core/Collection"' resolves to a non-module entity and cannot be imported using this construct.

[at-loader] Checking finished with 6 errors
```

It seems there is a problem with the type definition, Collection is defined as an interface and as a class : 

```
declare module "esri/core/Collection" {
  import Collection = __esri.Collection;
  export = Collection;
}

interface Collection<T = any> extends Evented {}
export class Collection<T = any> extends Accessor {...}

```

**Comment by tonicfx** [comment]
So, if I make import like this 

`import * as Collection from 'esri/core/Collection';`  => not work
`import Collection = __esri.Collection;` => work

**Comment by jkieboom** [comment]
You will need to use `import Collection = require("esri/core/Collection");` to import the AMD style classes.

> It seems there is a problem with the type definition, Collection is defined as an interface and as a class :

This is a "trick" to declare multiple inheritance in TS, we use it internally all the time.

**Comment by tonicfx** [comment]
Thanks for the response.

But other import work with import * as XXX from 'YYYYY';

For example, these imports works.
```
import * as Map from "esri/Map";
import * as MapView from "esri/views/MapView";
import * as ScaleBar from "esri/widgets/ScaleBar";
import * as Home from "esri/widgets/Home";
import * as BasemapGallery from "esri/widgets/BasemapGallery"
```

**Comment by jkieboom** [comment]
That only works because the way we define most classes is using a special construct that allows you to define multiple inheritance, separate constructors and allows extending the definitions externally if you want to. This leads to the type definition to be interpreted as a module by TS, even though really it's a class. We can't use the same kind of definition for `Collection` because it is a generic type. The only way that you can import it is using `require` (which is also recommended for other class modules).

**Comment by tonicfx** [comment]
Thanks for your help.

Last question, when I set collection of sub layer of my sublayer, I have this error (not at compilation), but at runtine 

```
let collection : Collection<Sublayer> = new Collection<Sublayer>();
subLayerParent.sublayers = collection;
```

`init.js:327 [esri.core.Accessor] Accessor#set Assigning an instance of 'esri.core.Collection' which is not a subclass of 'esri.core.Collection<esri.layers.support.Sublayer>'`

However I declare explicitaly the type of collection....?

**Comment by jkieboom** [comment]
Yes, this is something that we are looking at fixing (it should be valid to do this). The `Collection<Sublayer>` is a compile time type, but we also have a mechanism to enforce runtime types (and autocasting) for `Collection`. The way this works is by creating a unique subclass for a given element type using `Collection.ofType`, and we will verify at runtime when you set a collection that it has this correct subtype (this is where the error comes from). Hopefully in 4.6 (/cc @ycabon) we will allow automatic up-casting from general `Collection` to subtype `Collection`, but for 4.5 you can do (from the top of my head, not tested):

```ts
// Do this once somewhere, basically returns a new constructor for a dynamically created class
const SublayerCollection = Collection.ofType(Sublayer);

let collection = new SublayerCollection();
sublayerParent.sublayers = collection;
```

**Comment by tonicfx** [comment]
Cool, thanks for the trick ! :)
