### ISSUE TITLE
Error: <image> attribute x/y: Expected length, "NaN"  [ jsapi 4.5 with typescript]

### ISSUE THREAD

**Issue by Abexdatl** [Esri/jsapi-resources#99]
I was loading multiple FeatureLayers . The layers are loaded and I can do search and identify but in the debugger window I see series of errors with the below message. 

Error: <image> attribute x/: Expected length, "NaN"
Error: <image> attribute x/: Expected length, "NaN"

Top of the stack trace ... 

=======================
m.setShape | @ | MapView.js:1838
-- | -- | --
  | C | @ | MapView.js:1862
  | y | @ | MapView.js:1860
  | r.doRender | @ | MapView.js:1853
  
===========================

Eventhough I have multiple FeatureLayers it looks the issue is related to only one of the FeatureLayers. 

I am using the 4.5 version with TypeScript. 

Any idea?

**Comment by jgravois** [comment]
isolating the problematic feature layer would really be helpful here. if its private, hopefully you can at least extract some data from it to share a link.

**Comment by Abexdatl** [comment]
I isolated the feature layer that caused the issue . It is one of sublayers of one FeatureServer. All the other sub layers do not have the issue. 

This particular layer happen to return the most data though . The others return small data by design. 

PS, this feature layer doesnt have the issue on 3.x based app( no Typescript). 

Are you suggesting that this may be a data issue? If so it is a an easy problem to me .
